app/build.gradle, app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt
Also some bonus dependency stuff
=> Fix Login not clearing backstack

app/src/main/java/com/hedvig/app/feature/chat/ChatAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/referral/InvitesAdapter.kt
=> DiffUtil null safety

app/src/main/java/com/hedvig/app/feature/claims/ui/ClaimsFragment.kt, app/src/main/java/com/hedvig/app/feature/dashboard/ui/DashboardFragment.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/BaseTabFragment.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/ProfileFragment.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/referral/InvitesAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/referral/ProgressTankView.kt, app/src/main/java/com/hedvig/app/feature/referrals/ReferralsFragment.kt
Also improve the code massively. Thanks AndroidX!
=> Fix some tab-related bugs

app/src/debug/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/release/AndroidManifest.xml, app/src/staging/AndroidManifest.xml
Hopefully fix the branch issue
=> Fix: Branch key

app/src/main/graphql/com/hedvig/android/owldroid/graphql/cost.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/dashboard.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/incentive.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/perilCategory.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/profile.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/redeemReferralCode.graphql, app/src/main/java/com/hedvig/app/feature/dashboard/ui/DashboardFragment.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferActivity.kt
Also: Fragments can live in their own files!
=> Fix peril order

app/src/main/AndroidManifest.xml, app/src/main/graphql/com/hedvig/android/owldroid/graphql/cashback.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/profile.graphql, app/src/main/graphql/com/hedvig/android/owldroid/graphql/selectCashback.graphql, app/src/main/java/com/hedvig/app/feature/profile/data/ProfileRepository.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/ProfileFragment.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityFragment.kt, app/src/main/res/navigation/logged_in_navigation.xml
Also convert the view to an activity.
Way better.
Also Fragmentize this query. Much nicer.
=> Fix missing text after selecting cashback

app/src/main/java/com/hedvig/app/feature/offer/OfferActivity.kt
=> Animate numbers

app/build.gradle, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatAdapter.kt, app/src/main/res/drawable/ic_chat_record_audio.xml, build.gradle
They look dumb when they actually appear in the chat.
It was not intended
=> Fix audio messages recording whatsoever

app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/BaseActivity.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatTextInput.kt, app/src/main/java/com/hedvig/app/feature/settings/Language.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/java/com/hedvig/app/feature/settings/Theme.kt, app/src/main/java/com/hedvig/app/util/apollo/GraphQLUtils.kt, app/src/main/res/values/arrays.xml, app/src/main/res/xml/preferences.xml
It's not the best thing I've ever seen, but it actually works pretty well.
=> Language as a setting

app/src/main/java/com/hedvig/app/ui/view/SafeWebView.kt, app/src/main/res/layout/activity_licenses.xml, app/src/main/res/layout/activity_trustly.xml
Context:
https://stackoverflow.com/questions/41025200/android-view-inflateexception-error-inflating-class-android-webkit-webview
=> Fix WebViews crashing the app on sub-nougat devices

app/build.gradle, app/src/debug/java/com/hedvig/app/MockProfileViewModel.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/res/layout/next_payment_card.xml, app/src/main/res/layout/price_bubbles.xml
Bonus: Fix a discolouration issue on Offer Screen
=> Support PercentageDiscountMonths on Payment Screen as well

app/src/debug/java/com/hedvig/app/DevelopmentActivity.kt, app/src/debug/java/com/hedvig/app/MockKeyGearViewModel.kt, app/src/debug/java/com/hedvig/app/MockModule.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/Constants.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/keygear/KeyGearFragment.kt, app/src/main/java/com/hedvig/app/feature/keygear/KeyGearItemsAdapter.kt, app/src/main/java/com/hedvig/app/feature/keygear/KeyGearViewModel.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInTabs.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/TabPagerAdapter.kt, app/src/main/java/com/hedvig/app/ui/decoration/BottomPaddingItemDecoration.kt, app/src/main/java/com/hedvig/app/ui/decoration/GridSpacingItemDecoration.kt, app/src/main/java/com/hedvig/app/util/extensions/DimensionExtensions.kt, app/src/main/res/drawable/background_rounded_corners_ripple.xml, app/src/main/res/drawable/ic_key_gear.xml, app/src/main/res/layout/fragment_key_gear.xml, app/src/main/res/layout/key_gear_item.xml, app/src/main/res/layout/key_gear_new_item.xml, app/src/main/res/menu/logged_in_menu.xml, app/src/main/res/values/dimens.xml
Missing right now:
- GraphQL model classes (schema is not ready)
- Translations
We'll use this as a base for the rest of the feature implementation.
There are a lot of unfilled TODOs - these will be filled later
=> Key Gear: Tab

app/src/debug/java/com/hedvig/app/MockKeyGearItemDetailViewModel.kt, app/src/debug/java/com/hedvig/app/MockKeyGearViewModel.kt, app/src/main/AndroidManifest.xml, app/src/main/graphql/com/hedvig/android/owldroid/graphql/keyGearItemFragment.graphql, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatActivity.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatFileUploadBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/ReceiptActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/Category.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CategoryAdapter.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CreateKeyGearItemViewModel.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/PhotosAdapter.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/itemdetail/KeyGearItemDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/itemdetail/KeyGearItemDetailViewModel.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/itemdetail/ReceiptFileUploadBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearItemsAdapter.kt, app/src/main/java/com/hedvig/app/ui/fragment/FileUploadBottomSheet.kt, app/src/main/res/drawable/ic_receipt.xml, app/src/main/res/layout/activity_key_gear_item_detail.xml, app/src/main/res/layout/activity_receipt.xml, app/src/main/res/values-night/colors_dark.xml, app/src/main/res/values-v29/styles.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/colors_light.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Missing: Translation for the bottom sheet to upload a receipt.
Saving this for later as there is currently no translation available.
=> Key Gear Item Detail: Add/View Receipt

app/build.gradle, app/src/main/java/com/hedvig/app/util/extensions/TextViewExtensions.kt
=> Markdown support!

app/build.gradle, app/src/main/graphql/com/hedvig/android/owldroid/graphql/uploadFiles.graphql, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/keygear/data/KeyGearItemsRepository.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CreateKeyGearItemActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CreateKeyGearItemViewModel.kt
=> Concrete implementation of API calls

app/src/debug/java/com/hedvig/app/MockCreateKeyGearItemViewModel.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CreateKeyGearItemActivity.kt, app/src/main/res/layout/activity_create_key_gear_item.xml
Github does not support movie attachments, check the android channel for a preview 🙂
=> Key Gear: Create Item, Transitionary state while uploading

app/src/main/graphql/com/hedvig/android/owldroid/graphql/createKeyGearItem.graphql, app/src/main/java/com/hedvig/app/feature/keygear/data/DeviceInformationService.kt, app/src/main/java/com/hedvig/app/feature/keygear/data/KeyGearItemsRepository.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearViewModel.kt
=> Add device name on auto-added devices

app/build.gradle, app/src/main/java/com/hedvig/app/feature/chat/ui/AudioRecorderView.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatAdapter.kt, app/src/main/java/com/hedvig/app/feature/dashboard/ui/DashboardAdapter.kt, app/src/main/java/com/hedvig/app/feature/dashboard/ui/contractcoverage/ContractCoverageActivity.kt, app/src/main/java/com/hedvig/app/feature/dashboard/ui/contractdetail/ContractDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/KeyGearValuationActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/KeyGearValuationInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/ReceiptActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/createitem/CreateKeyGearItemActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/binders/FactAreaBinder.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/ProfileFragment.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/aboutapp/AboutAppActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/myinfo/MyInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentHistoryAdapter.kt, app/src/main/java/com/hedvig/app/feature/referrals/InvitesAdapter.kt, app/src/main/java/com/hedvig/app/feature/referrals/ProgressTankView.kt, app/src/main/java/com/hedvig/app/feature/referrals/ReferralBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/referrals/ReferralsReceiverActivity.kt, app/src/main/java/com/hedvig/app/feature/referrals/ReferralsSuccessfulInviteActivity.kt, app/src/main/java/com/hedvig/app/service/push/managers/ReferralsNotificationManager.kt, app/src/main/java/com/hedvig/app/util/Textkeys.kt, build.gradle
Old solution is now entirely sunset!
=> Final parts of Lokalise integration

app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt
Fixes https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/db7683f24cf0a360dcd83cfc1cd14795
=> Fix an issue with Charsets causing a crash

app/build.gradle, app/src/main/res/layout/referrals_code.xml, app/src/main/res/layout/referrals_header.xml, app/src/main/res/layout/referrals_row.xml
=> Forever: Make the placeholders shimmer

app/src/main/java/com/hedvig/app/feature/chat/data/ChatRepository.kt, app/src/main/java/com/hedvig/app/feature/chat/viewmodel/ChatViewModel.kt
How did this ever work correctly? :thinking:
=> Fix chat messages coming in the wrong order

app/build.gradle, app/src/androidTest/java/com/hedvig/app/feature/referrals/deeplinks/ForeverDeepLinkTest.kt, app/src/debug/java/com/hedvig/app/feature/referrals/ReferralsMockActivity.kt, app/src/debug/res/values/strings.xml, app/src/main/java/com/hedvig/app/SplashActivity.kt
=> Firebase links with path `/forever` now deep link directly to logged in with referrals tab opened

app/src/androidTest/java/com/hedvig/app/feature/referrals/editcode/MaxChangesErrorTest.kt, app/src/androidTest/java/com/hedvig/app/util/KakaoExtensions.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/editcode/ReferralsEditCodeActivity.kt
=> Forever: Edit code, specific error for max updates

app/src/androidTest/java/com/hedvig/app/feature/offer/ChooseStartDateExistingSwitchableInsuranceTest.kt, app/src/debug/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt
How did this even work in the other test?
=> Fix the change date sheet not working under certain circumstances

app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearItemsAdapter.kt
=> no placeholder

app/src/androidTest/java/com/hedvig/app/feature/home/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/NoFirstNameErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/NoFutureInceptionErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/PendingTest.kt, app/src/androidTest/java/com/hedvig/app/feature/loggedin/LoggedInScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/loggedin/ProfileToolbarMenuTest.kt, app/src/androidTest/java/com/hedvig/app/feature/profile/SuccessTest.kt, app/src/main/java/com/hedvig/app/LoggedInTerminatedActivity.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/ClaimsViewModel.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileFragment.kt, app/src/main/res/layout/profile_subtitle.xml
- About App is now its own row on the Profile Tab
- Settings now actually leads to settings (lol)
- The Toolbar action on the Profile Tab is now the Chat
Also
- A few callback-based functions are now instead coroutines. Woot!﻿
=> App Navigation: Profile Tab Design QA

app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileFragment.kt
Cause was doing IO on the main thread. Boo!
=> Fix app crashing when attempting to log out

app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt
I hope this works? I'm unable to reproduce it locally.
=> Fix logout crash (again)

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/home.graphql, app/src/androidTest/java/com/hedvig/app/feature/home/howclaimswork/HowClaimsWorkTest.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HowClaimsWorkDialog.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/home/builders/HomeDataBuilder.kt
=> Clean up some text key usage

app/src/androidTest/java/com/hedvig/app/feature/splash/NetworkErrorTest.kt, app/src/main/java/com/hedvig/app/service/LoginStatusService.kt
=> Fix app crashing on network errors in splash

app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
=> now opens info activity

app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
Adds the ability to dismiss the tooltip by clicking on it
=> Fix: Tooltip, click to hide

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/BaseActivity.kt, app/src/main/java/com/hedvig/app/ScreenTracker.kt
=> Screen view-tracking

app/src/engineering/java/com/hedvig/app/MockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/chat/ChatMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/home/HomeMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/profile/ProfileMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/referrals/ReferralsMockActivity.kt
- Introduce an abstraction to simplify their creation
- Enforce koin mocking cleanup in this abstraction to prevent crashes
=> Improve Mock Activities

app/build.gradle
=> Only include resources in our supported languages

app/src/debug/AndroidManifest.xml, app/src/engineering/java/com/hedvig/app/DevelopmentActivity.kt, app/src/engineering/java/com/hedvig/app/feature/home/HomeMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/loggedin/LoggedInMockActivity.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/loggedin/Data.kt
=> moved whats new mock screen

app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt
=> Fix app crash when no app can open web URLs

app/src/main/java/com/hedvig/app/feature/chat/ui/ChatFileUploadBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/chat/viewmodel/ChatViewModel.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/itemdetail/ReceiptFileUploadBottomSheet.kt, app/src/main/java/com/hedvig/app/ui/fragment/FileUploadBottomSheet.kt
Also modernize the file upload bottom sheet slightly
=> [HVG-120]: Fix bottom sheet not dismissing

app/src/main/java/com/hedvig/app/feature/marketpicker/MarketItemAdapter.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerFragment.kt, app/src/main/res/values/styles.xml
=> sharedViewModel fix

app/src/main/java/com/hedvig/app/feature/insurance/ui/contractcoverage/ContractCoverageActivity.kt, app/src/main/java/com/hedvig/app/util/apollo/GraphQLUtils.kt, app/src/main/java/com/hedvig/app/util/extensions/ModelExtensions.kt
=> schema update

app/build.gradle, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerFragment.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerViewModel.kt
=> hope this works

app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt
=> opens correct fragment when changing market

app/build.gradle, app/src/engineering/java/com/hedvig/app/feature/marketpicker/MockMarketPickerViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/Market.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketItemAdapter.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerViewModel.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketProvider.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketSelectedFragment.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/PickerAdapter.kt, app/src/main/java/com/hedvig/app/feature/settings/Language.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt, app/src/main/java/com/hedvig/app/util/apollo/GraphQLUtils.kt, app/src/main/res/drawable/ic_flag_dk.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/static_strings.xml
=> HVG-169: Add Denmark, flagged off in production

app/src/engineering/java/com/hedvig/app/MockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/engineering/res/layout/activity_generic_development.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/res/layout/contract_detail_activity.xml, app/src/main/res/layout/long_scrolly_fragment.xml, app/src/main/res/values/dimens.xml
- HVG-187 Edge-to-edgeify mock activies
- HVG-187: contract detail base
- HVG-187: Implement cool scrolling behaviour
Item from design: [insurance tab motion test]
=> App Nav: Contract Detail, Base

app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/ContractDetailScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/DocumentsTest.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsModel.kt, app/src/main/res/layout/contract_detail_documents_document.xml, app/src/main/res/layout/contract_detail_documents_fragment.xml
Item from design: [insurance_details_view_documents]
=> HVG-190: App Navigation, Contract Detail, Documents Tab

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, app/src/androidTest/java/com/hedvig/app/feature/insurance/ui/InsuranceStudentCardTest.kt, app/src/engineering/java/com/hedvig/app/MockInsuranceViewModel.kt, app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/ContractPillAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/util/extensions/ModelExtensions.kt, app/src/main/res/layout/insurance_contract_card.xml, app/src/main/res/layout/insurance_header.xml, testdata/src/main/java/com/hedvig/app/testdata/dashboard/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceDataBuilder.kt
Item from design: [insurance_tab]
=> HVG-229 Feature/new contract card info

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/ContextExtensions.kt, app/src/main/res/layout/contract_detail_activity.xml, app/src/main/res/layout/contract_pill.xml, app/src/main/res/layout/insurance_contract_card.xml, app/src/main/res/values-night/home_gradients.xml, app/src/main/res/values/logged_in_gradients.xml, app/src/main/res/values/text_themes.xml, app/src/main/res/values/theme.xml, app/src/main/res/values/widget_themes.xml
=> HVG-242: App Navigation, Contract Detail, Insurance Card

app/src/main/java/com/hedvig/app/feature/adyen/AdyenConnectPayinActivity.kt, app/src/main/java/com/hedvig/app/feature/adyen/AdyenViewModel.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/Market.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferSignDialog.kt, app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt
=> Fix bugs related to connecting payment

app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerFragment.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerViewModel.kt
=> Invalid language value: null

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt
=> Minor mixed fixes

app/src/main/java/com/hedvig/app/feature/chat/ui/GifPickerBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferSignDialog.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityExplanationBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/redeemcode/RedeemCodeDialog.kt
=> Fix some wacky dialogs

app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt
=> Prevent a crash in offer

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/res/layout/contract_detail_activity.xml, app/src/main/res/layout/insurance_contract_card.xml
=> Make the insurance card ripple again

app/src/androidTest/java/com/hedvig/app/feature/insurance/screens/InsuranceScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/tab/TerminatedContractsTest.kt, app/src/androidTest/java/com/hedvig/app/util/KakaoExtensions.kt, app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceFragment.kt, app/src/main/res/layout/insurance_terminated_contracts.xml, app/src/main/res/layout/insurance_terminated_contracts_header.xml, testdata/src/main/java/com/hedvig/app/testdata/dashboard/Data.kt
Item from design: [insurance_tab_terminated_insurance]
=> HVG-307: Insurance Tab, Terminated contracts row

app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInViewModel.kt
=> HVG-341: Solve the weird inset-bug

app/build.gradle, app/src/main/java/com/hedvig/app/feature/chat/ui/GifPickerBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/marketing/service/MarketingTracker.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityExplanationBottomSheet.kt, app/src/main/java/com/hedvig/app/util/extensions/TextViewExtensions.kt, app/src/main/res/layout/activity_my_info.xml, app/src/main/res/layout/bottom_sheet_charity_explanation.xml, app/src/main/res/layout/bottom_sheet_honesty_pledge.xml, app/src/main/res/layout/fragment_market_selected.xml, app/src/main/res/layout/send_gif_dialog.xml, build.gradle
=> HVG-331, HVG-340: Text key changes

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/updateLanguage.graphql, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/LanguageRepository.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerViewModel.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsViewModel.kt
=> HVG-375: Call `updatePickedLocale` when we switch language

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, app/src/main/res/layout/insurance_contract_card.xml
=> HVG-398: Prevent pills on contract card from eating clicks on the parent card

app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilBottomSheet.kt
=> show X when chevron is pressed

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/SingleVariableTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/CustomTextActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/DefaultTextActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/EmbarkScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetTest.kt, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/MessageAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionSetViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextFieldData.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextInputSetAdapter.kt, app/src/main/res/layout/embark_input_item.xml, app/src/main/res/layout/fragment_text_action_set.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt
=> HVG-482 textActionSet

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/DanishAccidentTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/tab/DanishAccidentContractTest.kt, app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoFragment.kt, app/src/main/res/drawable-night/card_accident_background.xml, app/src/main/res/drawable/card_accident_background.xml, app/src/main/res/values-night/colors_dark.xml, app/src/main/res/values/colors.xml, testdata/src/main/java/com/hedvig/app/testdata/dashboard/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceDataBuilder.kt
=> HVG-455: Support Danish Accident-contracts

app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt
=> HVG-527: Switch to ISO-8601 for date format on `PaymentActivity` and `PaymentHistoryActivity`

app/src/main/java/com/hedvig/app/feature/chat/viewmodel/UserViewModel.kt
=> HVG-575: Avoid crashes when backend returns error when authing

app/src/androidTest/java/com/hedvig/app/feature/payment/NoCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentModel.kt, app/src/main/res/drawable/ic_add_circle.xml, app/src/main/res/layout/payment_redeem_code.xml
=> HVG-597: New design for redeem code

.github/workflows/pr.yml, app/build.gradle.kts, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatTextInput.kt
=> Add a linting action!

app/src/androidTest/java/com/hedvig/app/feature/payment/PayinNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/res/layout/connect_payin_card.xml, app/src/main/res/values/ids.xml
=> HVG-596: Update Connect Payin

app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/res/layout/failed_payments_card.xml
Missing before ready for merge:
=> HVG-594: Update design for failed payments

app/src/androidTest/java/com/hedvig/app/feature/payment/FreeMonthsCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PercentageDiscountTest.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/res/layout/next_payment_card.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/Data.kt
=> HVG-595: Update Next Payment-design

app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenConnectPayoutActivity.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenConnectPayoutViewModel.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/ConnectPayoutResultFragment.kt, app/src/main/res/layout/connect_payout_result_fragment.xml
=> HVG-620: Adyen connect payout, result screen

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/payment.graphql, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutNotConnected.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/NoCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/engineering/java/com/hedvig/app/feature/payment/MockPaymentViewModel.kt, app/src/engineering/java/com/hedvig/app/feature/payment/PaymentMockActivity.kt, app/src/engineering/java/com/hedvig/app/mocks/MockModule.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/Market.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentModel.kt, app/src/main/java/com/hedvig/app/util/extensions/TextViewExtensions.kt, app/src/main/res/layout/payout_details_header.xml, app/src/main/res/layout/payout_details_paragraph.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/PaymentDataBuilder.kt
=> HVG-621: Payment screen, payout not connected

app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/FailedPaymentsTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/FreeMonthsCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/InactiveTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/NoCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PayinNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentHistoryTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PercentageDiscountTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/ReferralCampaignTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/TrustlyConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/TrustlyPendingTest.kt, app/src/engineering/java/com/hedvig/app/feature/payment/PaymentMockActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/res/layout/activity_payment.xml, app/src/main/res/layout/payment_history_header.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/Data.kt
=> HVG-657: Payment Screen, headers and ordering

.editorconfig, .github/workflows/pr.yml, app/build.gradle.kts, app/src/androidTest/java/com/hedvig/app/feature/home/ActiveWithMultiplePSAsAndConnectPayment.kt
=> POC: Add a ktlint github action!

app/src/androidTest/java/com/hedvig/app/feature/embark/BackNavigationTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/CustomSelectActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/CustomTextActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/DefaultSelectActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/DefaultTextActionResponseTest.kt
- [] Functionality is accessible in engineering mode
=> ignored flakey tests

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/payment.graphql, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutPendingTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/engineering/java/com/hedvig/app/feature/adyen/AdyenMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/payment/PaymentMockActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentModel.kt, app/src/main/res/layout/payout_connection_status.xml, app/src/main/res/layout/payout_details_paragraph.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/PaymentDataBuilder.kt
=> HVG-622: Adyen Payout, Connected/Pending

app/src/main/java/com/hedvig/app/feature/embark/EmbarkModel.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ExpressionResult.kt, app/src/main/java/com/hedvig/app/feature/embark/NavigationDirection.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
=> HVG-759: Embark, Passage transitions

app/src/androidTest/java/com/hedvig/app/feature/offer/HouseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/OfferScreen.kt, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt
=> HVG-803: Fix crash on offer screen when user has a house quote and extra buildings

app/src/main/AndroidManifest.xml
This makes it so that we can open URIs with these schemes.
=> HVG-808 HVG-814: Add `bankid` and `https` as intents we query for

app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/Market.kt
=> HVG-824: Fix payout link going to the wrong screen

app/src/androidTest/java/com/hedvig/app/feature/home/UpcomingRenewalTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/ContractDetailErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/ExistingSwitchableInsuranceTest.kt, app/src/androidTest/java/com/hedvig/app/feature/onboarding/ChoosePlanTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutPendingTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/referrals/activated/ReferralsActivatedActivityTest.kt, app/src/androidTest/java/com/hedvig/app/feature/referrals/editcode/SubmitUsingImeTest.kt, app/src/androidTest/java/com/hedvig/app/feature/splash/NetworkErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/trustly/ConnectPayinSwedenTest.kt
=> Attempt to repair tests failing in CI

app/src/main/res/layout/activity_chat.xml, app/src/main/res/layout/activity_key_gear_valuation.xml, app/src/main/res/layout/activity_key_gear_valuation_info.xml, app/src/main/res/layout/activity_receipt.xml, app/src/main/res/layout/activity_web_onboarding.xml, app/src/main/res/values/styles.xml
=> Add toolbar icon style and set for relevant image views.

app/src/androidTest/java/com/hedvig/app/feature/offer/HouseTest.kt, app/src/main/java/com/hedvig/app/feature/onboarding/ui/OnboardingAdapter.kt, app/src/main/res/layout/activity_choose_plan.xml, app/src/main/res/layout/activity_more_options.xml, app/src/main/res/layout/activity_settings.xml, app/src/main/res/layout/more_options_row.xml, app/src/main/res/layout/plan_card.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/theme.xml, app/src/main/res/values/widget_themes.xml
- Fix unnecessary text breaking by removing end constraint and using gravity.
- Add layout weight name text, remove max width and fixed height to allow for text size to increase.
- Show and hide shimmer in animation start and end.
- Set toolbar title text color in theme
- Fix shimmer animation
=> Design adjustments

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/tokenizePayoutDetails.graphql, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/adyen/AdyenRepository.kt, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenConnectPayinActivity.kt, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenConnectPayinViewModel.kt, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenPayinDropInService.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenConnectPayoutActivity.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenConnectPayoutViewModelImpl.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenPayoutDropInService.kt
=> Start using the right mutation for tokenizing payout details

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> Make the `EmbarkStoryQuery` compatible with the server

app/src/androidTest/java/com/hedvig/app/feature/embark/BackNavigationTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkActivityTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/MissingActionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/NetworkErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/SingleVariableTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/SuccessTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/AndExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/EqualsExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/GreaterThanExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/GreaterThanOrEqualsExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/LessThanExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/LessThanOrEqualsExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/NotEqualsExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/OrExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/TemplateValuesTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/messages/UnaryExpressionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/redirects/BinaryExpressionRedirectTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/redirects/MultipleExpressionRedirectTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/redirects/PassedKeyValueRedirectTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/redirects/UnaryExpressionRedirectTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionTest.kt
=> Modernize the entirety of the embark test suite

app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutNotConnectedTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/AdyenPayoutPendingTest.kt, app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentModel.kt, app/src/main/res/layout/payout_details_paragraph.xml
=> HVG-855: Fix payout footer having incorrect text when connected/pending

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextFieldData.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetParameter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextInputSetAdapter.kt
=> Fix text action set default result not strictly speaking working

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/build.gradle.kts, app/src/androidTest/java/com/hedvig/app/feature/embark/numberaction/NumberActionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/EmbarkScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/NumberActionScreen.kt, app/src/androidTest/java/com/hedvig/app/util/KakaoExtensions.kt, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/res/layout/embark_input_item.xml, app/src/main/res/layout/fragment_embark_text_action.xml, app/src/main/res/layout/number_action_fragment.xml, app/src/main/res/values/widget_themes.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/NumberActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PreviousInsurerAction.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
Missing until ready for merge:
=> HVG-849: Embark, `NumberAction`

app/src/androidTest/java/com/hedvig/app/feature/embark/BackNavigationTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkActivityTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/NetworkErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/SingleVariableTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/SuccessTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/GeneratedVariableTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/numberaction/NumberActionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/CustomSelectActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/CustomTextActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/DefaultSelectActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/response/DefaultTextActionResponseTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionAppendHyphen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetValidation.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionValidation.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/FragmentExtensions.kt, app/src/main/res/values-night/colors_dark.xml, app/src/main/res/values/widget_themes.xml
- Fix GraphQL calls not adding 'content-type'
- Fix numberaction not having any messages
- Fix number action validation being exclusive instead of inclusive
- Modernize some tests that I missed before
=> Embark: Various fixes

app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionBirthDateReverseMaskTest.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/DerivedValues.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/Unmasking.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> HVG-872: Support the store-related features for reverse birth date

app/src/main/res/layout/embark_message_item.xml, app/src/main/res/layout/fragment_embark_select_action.xml, app/src/main/res/layout/fragment_embark_text_action.xml, app/src/main/res/layout/fragment_text_action_set.xml, app/src/main/res/layout/previous_insurer_fragment.xml
=> HVG-876: Add margin for embark messages

app/build.gradle.kts, app/src/debug/res/values/strings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferTracker.kt, app/src/release/res/values/strings.xml, app/src/staging/res/values/strings.xml
=> HVG-867: Remove facebook sdk

app/src/main/res/layout/fragment_embark_text_action.xml
=> Use the correct button styling for text action

app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionBirthDateReverseMaskTest.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/DateFormats.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/Remasking.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/Unmasking.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt
- Remask values loaded from store correctly
- Opportunistic refactor: Migrate this test to `TextActionScreen`
=> HVG-891: Handle masks when loading values from store

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/adyenSubmitAdditionalPaymentDetails.graphql, apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/tokenizePayoutDetails.graphql, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenPayoutDropInService.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentRepository.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentViewModel.kt, app/src/main/java/com/hedvig/app/feature/zignsec/ZignSecAuthenticationActivity.kt
- Use the new eventual consistency-feature for payout status (wip)
- Final implementation!
=> HVG-885: Fix eventual consistency re: payouts-issue

app/src/androidTest/java/com/hedvig/app/feature/embark/screens/EmbarkScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/TextActionSetScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetValidation.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextFieldData.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextInputSetAdapter.kt
- Prefill with previous answer for `TextActionSet`
- Opportunistic refactor: Split out `TextActionSet` to its own `KScreen`
=> HVG-892: Load values upon back-navigation for TextActionSet

app/src/main/res/layout/activity_more_options.xml
=> HVG-875: Set correct bottom constraint to fix button over lap in more options

apollo/build.gradle.kts, apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/embark/track/TrackTest.kt, app/src/androidTest/java/com/hedvig/app/util/json/JSONAsserts.kt, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt, app/src/main/java/com/hedvig/app/ApolloClientWrapper.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkTracker.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/util/JSONObject.kt, app/src/main/java/com/hedvig/app/util/apollo/JSONStringAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TrackBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
- Track, base-case
- Support tracking with `includeAllKeys`
- Support tracking for specific keys
- Support `customData`.
- Track when navigating back
Intentionally left out: Tracking for `ExternalRedirect`s, because they are
not yet implemented on the base branch.
=> HVG-894: Embark, Tracking

app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextInputSetAdapter.kt, app/src/main/java/com/hedvig/app/util/extensions/view/ViewExtensions.kt, app/src/main/res/layout/embark_input_item.xml, app/src/main/res/layout/fragment_embark_text_action.xml, app/src/main/res/layout/number_action_fragment.xml
Add listener for IME action done and navigate to next passage when pressed in `TextAction`, `TextActionSet` and `NumberAction`.
=> HVG-932: Embark keyboard next

app/src/androidTest/java/com/hedvig/app/feature/marketpicker/KnownGeoTest.kt, app/src/androidTest/java/com/hedvig/app/feature/marketpicker/NavigationTest.kt, app/src/androidTest/java/com/hedvig/app/feature/marketpicker/UnknownGeoTest.kt, app/src/androidTest/java/com/hedvig/app/feature/marketpicker/screens/MarketPickerScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/marketpicker/screens/MarketSelectedScreen.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/marketing/data/MarketingRepository.kt, app/src/main/java/com/hedvig/app/feature/marketing/ui/MarketingViewModel.kt
Add test for marketing navigation
=> Marketing navigation test

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkActivityTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/MoreOptionsTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/marketselected/MarketSelectedScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/MoreOptionsScreen.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsActivity.kt, app/src/main/java/com/hedvig/app/feature/onboarding/ui/ChoosePlanActivity.kt, app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt, app/src/main/res/layout/embark_message_item.xml, app/src/main/res/layout/fragment_embark_select_action.xml, app/src/main/res/layout/fragment_embark_text_action.xml, app/src/main/res/layout/fragment_text_action_set.xml, app/src/main/res/layout/number_action_fragment.xml, app/src/main/res/layout/previous_insurer_fragment.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/NumberActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PreviousInsurerAction.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> HVG-877: Redirect Offer to Web

app/src/main/java/com/hedvig/app/feature/marketpicker/MarketSelectedFragment.kt, app/src/main/res/layout/fragment_market_selected.xml
=> HVG-704: Remove legal text from marketing screen

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsFragment.kt, app/src/main/java/com/hedvig/app/feature/offer/TermsAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt
Redirect to hard coded url for SE market. Do not show documents if current agreement status is pending.
=> APP-231: Terms and agreements fixes

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/masking/DateFormats.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/res/layout/fragment_embark_date_picker.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/theme.xml, app/src/main/res/values/widget_themes.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/DatePickerActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/NumberActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PreviousInsurerAction.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
Add date picker for embark, used for selecting access date in moving flow.
=> APP-25: Embark date picker

app/build.gradle.kts, app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/ContextExtensions.kt
=> Remove api version dependency for hide key board extension

app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt
Encode quote id only for norwegian market and if offer parameter is present
=> APP-244: Quote id crash

app/src/main/java/com/hedvig/app/util/extensions/ModelExtensions.kt
=> APP-28: Add DK contract translations

app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/res/layout/fragment_embark_date_picker.xml, app/src/main/res/layout/fragment_embark_select_action.xml, app/src/main/res/layout/fragment_embark_text_action.xml, app/src/main/res/layout/fragment_text_action_set.xml, app/src/main/res/layout/number_action_fragment.xml, app/src/main/res/layout/previous_insurer_fragment.xml
Inflate toolbar menu when entering embark view to avoid height change. Add margin top to response view.
=> APP-267: Embark toolbar height

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextFieldData.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetParameter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextInputSetAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
Query title and use for hint instead of placeholder. Use placeholder as placeholder-text.
=> APP-271: Embark text action hints

app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/ContractDetailScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/SwedishApartmentTest.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoModel.kt, app/src/main/res/layout/change_address_button.xml
Add change address button for Swedish apartment in insurance detail view.
Should this be added in any other contract than Swedish apartment?
=> APP-5: Contract details change address button

app/src/main/res/layout/activity_web_onboarding.xml
=> APP-355: Use correct settings icon for embark offer

app/src/main/res/layout/embark_message_item.xml
=> APP-352: Make links in embark chat messages clickable

app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/TextViewExtensions.kt, app/src/main/java/com/hedvig/app/util/extensions/view/ViewExtensions.kt
- Fix embark loading stale quotes
- Bonus: Re-enable submitting with enter
=> APP-351: Prevent Embark from loading stale quotes

app/src/main/res/values/text_themes.xml, app/src/main/res/values/theme.xml
=> APP-279: Align overline-text appearance with design system

app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt, app/src/main/res/layout/activity_web_onboarding.xml, app/src/main/res/layout/embark_input_item.xml
=> APP-357: Add a rudimentary loading state to web offer

app/src/androidTest/java/com/hedvig/app/feature/embark/store/StoreVersionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetValidation.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionTest.kt, app/src/androidTest/java/com/hedvig/app/util/KakaoExtensions.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
- Version the embark store
- Re-add support for placeholders
- Bonus: Repair malfunctioning tests
=> APP-370: Version the Embark-store

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/embark/previousinsurer/PreviousInsurerTest.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerItem.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerParameter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerViewModel.kt, app/src/main/res/layout/fragment_embark_date_picker.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PreviousInsurerActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
- Use `id` for previous insurer
- Bonus: Clean up an XML file I stumbled upon
=> APP-375: Use IDs for Previous Insurer

app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetTest.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt
Both for TextActionSet and NumberActionSet.
Comes with a test for TextActionSet!
=> APP-376: Fix IME Next not doing anything

apollo/build.gradle.kts, app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/BuildLibs.kt, buildSrc/src/main/kotlin/CommonVersions.kt, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/Libs.kt, testdata/build.gradle.kts
This PR will be the basis on which I do some dependency update work.
=> APP-386: Refactor all dependencies to use `buildSrc`

app/src/main/java/com/hedvig/app/feature/claims/ui/pledge/HonestyPledgeBottomSheet.kt
See Jira for more context from Crashlytics.
=> APP-387: Fix lifecycle-related crash in honesty pledge sheet

.github/workflows/pr.yml, app/src/androidTest/java/com/hedvig/app/feature/embark/track/TrackTest.kt
=> APP-415: Upload test reports

app/build.gradle.kts, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/MessageAdapter.kt, app/src/main/java/com/hedvig/app/util/extensions/TextViewExtensions.kt, app/src/main/res/layout/embark_message_item.xml, buildSrc/src/main/kotlin/Libs.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> APP-394: Support Markdown in Embark-messages

.github/workflows/pr.yml
Something in linuxbrew appears to have broken its install.
=> APP-417: Try to fix ktlint action

app/src/androidTest/java/com/hedvig/app/feature/embark/MissingActionTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/EmbarkScreen.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/UpgradeAppFragment.kt, app/src/main/java/com/hedvig/app/feature/ratings/RatingsDialog.kt, app/src/main/java/com/hedvig/app/feature/ratings/Util.kt
=> APP-414: Prevent missing Play Store from crashing app when attempting to open play store

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/BuildLibs.kt, buildSrc/src/main/kotlin/CommonVersions.kt, buildSrc/src/main/kotlin/Libs.kt
=> APP-422: Update dependencies

app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilBottomSheet.kt, app/src/main/java/com/hedvig/app/ui/view/ExpandableBottomSheet.kt, app/src/main/res/layout/expandable_bottom_sheet.xml, app/src/main/res/layout/peril_paragraph.xml
Also, some opportunistic refactoring. Nice!
=> APP-425: Fix empty content leading to empty sections in Peril sheet

app/src/main/java/com/hedvig/app/feature/chat/ui/ChatInputView.kt
=> APP-418: Fix audio recorder cutting off chat messages

app/build.gradle.kts, app/src/main/java/com/hedvig/app/feature/embark/passages/MessageAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerFragment.kt, build.gradle.kts, buildSrc/src/main/kotlin/Libs.kt, gradle/wrapper/gradle-wrapper.properties
Also included:
- Remove one case of jcenter (one is still not possible to remove)
- Remove an unused bintray repository
- Remove synthetics
- Update Gradle
=> APP-432: Update dependencies

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/settings/MarketManager.kt
=> APP-433: Enable Denmark in production

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/changeaddress/ChangeAddressNotEligibleTest.kt, app/src/androidTest/java/com/hedvig/app/feature/changeaddress/UpcomingChangeAddressTest.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/add/AddComponentBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/MultiActionBuilder.kt
=> Use multi action number action

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/Response.kt, app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/Utils.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/res/drawable/background_rounded_corners_surface_6dp.xml, app/src/main/res/layout/embark_response.xml, app/src/main/res/layout/fragment_embark_date_picker.xml, app/src/main/res/layout/fragment_embark_multi_action.xml, app/src/main/res/layout/fragment_embark_select_action.xml, app/src/main/res/layout/fragment_text_action_set.xml, app/src/main/res/layout/number_action_set_fragment.xml, app/src/main/res/layout/text_body1.xml, app/src/main/res/layout/text_body2.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/widget_themes.xml, app/src/test/java/com/hedvig/app/feature/embark/ValueStoreImplTest.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/GroupedResponseBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/MessageBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/MultiActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/GroupedResponse.kt
=> APP-441: Grouped Response

app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkActivityTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/tab/InsuranceActiveAndTerminatedInFutureCardTest.kt, app/src/androidTest/java/com/hedvig/app/util/ApolloMockServer.kt, app/src/androidTest/java/com/hedvig/app/util/MergingResponseWriter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, testdata/src/main/java/com/hedvig/app/testdata/common/ContractStatus.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt
- Fix test data becoming inconsistent when multiple fragments attempt to write data to the same fields
- Fix test using a hardcoded string instead of a localized one
=> APP-457: Fix broken tests on develop

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/home.graphql, app/src/androidTest/java/com/hedvig/app/feature/home/UpcomingRenewalTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/screens/HomeTabScreen.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeModel.kt, app/src/main/res/layout/upcoming_renewal_card.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/home/builders/HomeDataBuilder.kt
=> APP-459: Fix contract display name being missing from renewal cards

app/src/main/java/com/hedvig/app/feature/claims/ui/pledge/HonestyPledgeBottomSheet.kt, app/src/main/java/com/hedvig/app/util/extensions/FragmentExtensions.kt
=> APP-460: Prevent rare lifecycle-related crash in honesty pledge bottom sheet

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/build.gradle.kts, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExtractor.kt, app/src/test/java/com/hedvig/app/feature/embark/VariableExtractorTest.kt, buildSrc/src/main/kotlin/Libs.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/GraphQLVariableBuilder.kt
This got quite messy, suggestion on improvements very welcome.
=> APP-456: Query multi action variable, fetch and cast stored multi action values

app/src/main/java/com/hedvig/app/feature/embark/computedvalues/TemplateExpressionCalculator.kt, app/src/test/java/com/hedvig/app/ComputedValuesTest.kt
=> Remove quotes from parsed computed store value

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, buildSrc/src/main/kotlin/BuildLibs.kt, buildSrc/src/main/kotlin/CommonVersions.kt, buildSrc/src/main/kotlin/Libs.kt, gradle/wrapper/gradle-wrapper.properties
=> Chore: Update dependencies

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/TaskExtensions.kt
=> Ensure that push notification token gets deleted on logout

app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractExt.kt
=> Disable moving flow in contract details if feature flag is not enabled

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileFragment.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt, app/src/main/java/com/hedvig/app/service/push/PushTokenManager.kt
=> APP-464: Fix push tokens not being regenerated in cases where they should

app/src/main/java/com/hedvig/app/util/extensions/ActivityExtensions.kt
This entire thing sucks. Bleh.
=> APP-261: Fix bankid link in chat doing nothing

app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkMenuTest.kt
=> Ignore flaky test

app/src/androidTest/java/com/hedvig/app/feature/offer/ExistingNonSwitchableInsuranceTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/NoExistingInsuranceTest.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/util/apollo/GraphQLUtils.kt, app/src/main/res/layout/offer_header.xml
[Figma design](https://www.figma.com/file/Ds2hXzDbnUt9ZNhg4HSWH3/Moving-Flow-Android?node-id=216%3A13)
Screenshot:
=> APP-454: Redesign price view in offer

app/src/androidTest/java/com/hedvig/app/feature/payment/PaymentScreen.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferRedeemCodeBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/redeemcode/RedeemCodeBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/redeemcode/RefetchingRedeemCodeBottomSheet.kt, app/src/main/res/layout/offer_header.xml, app/src/main/res/layout/promotion_code_dialog.xml
Add discount redesign! Figma [here](https://www.figma.com/file/Ds2hXzDbnUt9ZNhg4HSWH3/Moving-Flow-Android?node-id=226%3A1027)
Bottom sheet: 
Button:
=> APP-449: Redesign add discount

app/src/main/java/com/hedvig/app/ui/view/ExpandableContentView.kt, app/src/main/res/values/dimens.xml
=> APP-453: Design Review-tweaks for Offer Details

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/incentive.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/res/drawable/background_premium_box_with_campaign.xml, app/src/main/res/layout/offer_header.xml, app/src/main/res/values/text_themes.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/Data.kt
Figma [here](https://www.figma.com/file/Ds2hXzDbnUt9ZNhg4HSWH3/Moving-Flow-Android?node-id=216%3A1245)
Screenshot:
=> APP-495: Redesign discount added

app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
=> APP-520: Revert changes and show web offer activity

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/res/layout/offer_header.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-446: Show bundle name in offer

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/res/layout/activity_offer.xml, app/src/main/res/layout/offer_header.xml, app/src/main/res/layout/offer_loading_header.xml
=> APP-506: Offer loading state

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-541: Sign method query

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/SignMethodExt.kt, app/src/main/java/com/hedvig/app/util/extensions/ContextExtensions.kt, app/src/main/res/layout/activity_offer.xml, app/src/main/res/layout/offer_header.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-542: Set sign method view state

app/src/debug/AndroidManifest.xml, app/src/engineering/java/com/hedvig/app/DevelopmentActivity.kt, app/src/engineering/java/com/hedvig/app/feature/checkout/CheckoutMockActivity.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, app/src/main/java/com/hedvig/app/util/Validation.kt, app/src/main/res/layout/activity_checkout.xml
=> APP-544: Validate checkout input

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/androidTest/java/com/hedvig/app/feature/offer/CheckoutScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/CheckoutTest.kt, app/src/engineering/java/com/hedvig/app/feature/checkout/CheckoutMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferQueryExt.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutParameter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, app/src/main/java/com/hedvig/app/util/MonetaryAmountExt.kt, app/src/main/res/layout/activity_checkout.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-545: Checkout state and errors

app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/res/layout/offer_header.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt
=> Offer discount fix

.github/workflows/pr.yml
This should save us some time in the integration test-action.
=> Spring Cleaning: Separated Unit Test-execution

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/home.graphql, app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyActivity.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyData.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/home/builders/CommonClaimBuilder.kt
=> APP-561: Load emergency number from backend

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/OfferQueryInceptionExt.kt, app/src/main/res/layout/activity_offer.xml, app/src/main/res/layout/offer_header.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-599: Offer app configuration

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/res/layout/activity_offer.xml, app/src/main/res/menu/offer_menu.xml, app/src/main/res/menu/offer_menu_logged_in.xml
=> APP-463: Offer menu

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/result/ChangeAddressResultActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/ApproveQuotesUseCase.kt, app/src/main/java/com/hedvig/app/util/apollo/CacheManager.kt
=> Clear network cache on approve

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/HedvigApplication.kt, app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/result/ChangeAddressResultActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/EditStartDateUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/ApproveQuotesUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/SignQuotesUseCase.kt, app/src/main/java/com/hedvig/app/util/apollo/CacheManager.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt
=> APP-8: Show address result screens

app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/Component.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/add/AddComponentBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/add/AddComponentViewModel.kt
=> Multi action dropdown value

app/src/androidTest/java/com/hedvig/app/common/ErrorItem.kt, app/src/androidTest/java/com/hedvig/app/feature/home/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/NoFirstNameErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/NoFutureInceptionErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/screens/HomeTabScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/ErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/screen/OfferScreen.kt, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferRepository.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/RefreshQuotesUseCase.kt
=> APP-507: Offer Redesign, Error State

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, app/src/main/res/layout/progress_dialog.xml
=> Checkout progress

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/editMailAndSSN.graphql, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/SignQuotesUseCase.kt
=> Query editQuotes for all quote ids when signing

app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/util/Validation.kt, app/src/main/res/layout/activity_checkout.xml, app/src/main/res/layout/embark_select_action_item.xml
Please check commit messages to see what fixes this PR contains
=> Various moving flow fixes

app/src/androidTest/java/com/hedvig/app/feature/offer/screen/OfferScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/MultipleMixedSwitchableSwitcherTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/MultipleNonSwitchableSwitcherTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/MultipleSwitchableSwitcherTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/OneNonSwitchableSwitcherTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/OneSwitchableSwitcherTest.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/switching/ThreeMixedSwitchableSwitcherTest.kt, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/res/values/widget_themes.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt
- Use outlined card-style for info- and warning-cards
- Group switcher-rows based on switchability-status
- Abstract away some repeated code
=> APP-505: Offer Redesign, Switch-section, Design Acceptance-fixes

app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionViewModel.kt
=> APP-616: Show added extra buildings in embark response

app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt
=> APP-612: Hide change address on terminated

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt
=> APP-610: Fix footer open chat not working

app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/InsetterExt.kt, app/src/main/res/layout/activity_offer.xml, app/src/main/res/layout/offer_header.xml
=> APP-632, APP-621: Offer design fixes

app/src/main/java/com/hedvig/app/feature/table/TableAdapter.kt
=> APP-615: Table headers

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/EditStartDateUseCase.kt
=> APP-636, APP-613: Change inception on quote bundle instead of start date

app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionViewModel.kt, app/src/main/res/layout/view_multi_action_add.xml, app/src/main/res/layout/view_multi_action_component.xml, app/src/main/res/values/widget_themes.xml
To be honest, I wasn't able to reproduce the off-center effects, but I have some
idea of what might be causing it (the constraints). I changed the constraints
and did some opportunistic refactoring in the process.
=> APP-614: Fix Multi Action-Add having its content off-center

app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt, app/src/main/res/layout/fragment_embark_select_action.xml
Possible to test with Select Action -> Custom Response in engineering mode.
=> APP-619: Embark single button

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/res/layout/activity_checkout.xml
=> APP-634: Offer footer copy

app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/InsetterExt.kt
Also:
- Small formatting fix
- Fix background alpha being incorrect in certain spans
=> APP-642: Fix Offer toolbar inset

app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionItem.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionParams.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/res/layout/view_multi_action_add.xml
=> APP-685: Fix `MultiAction` having the wrong submit label

app/src/androidTest/java/com/hedvig/app/feature/embark/multiaction/MultiActionScreen.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionAdapter.kt, app/src/main/res/layout/view_multi_action_add.xml, app/src/main/res/layout/view_multi_action_component.xml
- Fix close button overlapping with text in multi action
- Bonus: try to fix the issue with text positioning for the add button
=> APP-655, APP-614: Multi action button-fixes

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/redeemcode/RedeemCodeBottomSheet.kt
=> APP-657: Use correct string res and hide price in adapter

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/OfferQueryInceptionExt.kt, app/src/test/java/com/hedvig/app/feature/offer/OfferDateTest.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/ConcurrentInceptionBuilder.kt
=> APP-658: Add tests for offer start date and fix logic

app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> APP-609: Add `ExternalRedirect`s for Close and Chat

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferTracker.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/ApproveQuotesUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/SignQuotesUseCase.kt
=> APP-701: Offer, track signs

app/src/main/java/com/hedvig/app/util/FeatureFlag.kt
=> Enable moving flow

app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/res/layout/contract_detail_activity.xml
=> APP-718: Termination text

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractExt.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoModel.kt, app/src/main/res/layout/additional_buildings_row.xml, app/src/main/res/layout/view_multi_action_add.xml, app/src/main/res/layout/your_info_home.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt
- Add missing house contract detail info
- Bonus: Remove unused code
- Bonus: Fix APP-712
=> APP-720: Add missing house contract detail items

app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutActivity.kt
=> APP-713: Correct Privacy Policy-URL

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/res/drawable/ic_chat.xml, app/src/main/res/drawable/ic_chat_background.xml, app/src/main/res/drawable/ic_chat_black_ripple.xml, app/src/main/res/drawable/ic_round_chat_black.xml, app/src/main/res/layout/activity_web_onboarding.xml, app/src/main/res/layout/menu_chat_icon.xml, app/src/main/res/menu/offer_menu.xml, app/src/main/res/menu/offer_menu_logged_in.xml
=> APP-648: Use new chat button for offer and logged in activity

app/src/main/res/values/widget_themes.xml
Add adjustResize to bottomsheet dialog theme
=> APP-487: Add adjustResize to bottomsheet dialog theme

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheetViewModel.kt
It was not present in the designs.
Incidentally, this also fixes the dialog being shown for moving flow
=> APP-717: Remove warning about switching

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/androidTest/java/com/hedvig/app/feature/embark/screens/TextActionSetScreen.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/selectaction/MultipleOptionApi.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/selectaction/SingleOptionApi.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionApiTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionSetApiTest.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkExtensions.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/multiaction/MultiActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/GraphQLApiBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
This implementation uses the same code path as passage-level API.
It's not ideal, but it will get the job done for now!
=> APP-606: Support action-level API calls

app/build.gradle.kts, app/src/androidTest/java/com/hedvig/app/feature/changeaddress/ChangeAddressScreen.kt
This should also fix the builds on bitrise. I hope.
=> Fix a warning related to crashlytics plugin

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/AttachFileAdapter.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatAdapter.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/GifAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/ReceiptActivity.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/itemdetail/PhotosAdapter.kt, app/src/main/java/com/hedvig/app/feature/perils/PerilBottomSheet.kt, app/src/main/java/com/hedvig/app/util/BroadcastReceiver.kt, app/src/test/java/com/hedvig/app/feature/embark/VariableExtractorTest.kt
Fixes this crash: https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/4ad3af41ecc1cce93bb294d93a998cd3?time=last-seven-days&sessionEventKey=610AD92A0080000145F345392B62FF70_1571086014019419984
=> Catch numberformatexception and try to parse float

app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheetViewModel.kt
=> APP-741: Set start date fix

app/src/androidTest/java/com/hedvig/app/feature/offer/StartDateFromPreviousInsurerTest.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateView.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/Data.kt
=> APP-742: Show current insurer if switchable

app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/SwedishApartmentTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/SwedishHouseTest.kt, app/src/androidTest/java/com/hedvig/app/util/FeatureFlagRule.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
=> Fix failing tests

app/src/engineering/java/com/hedvig/app/mocks/MockKeyGearViewModel.kt, app/src/main/java/com/hedvig/app/feature/keygear/data/DeviceInformationService.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearFragment.kt, app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearViewModel.kt
=> Pass view context to determine device type

app/proguard-rules.pro
This should fix the app crashing when opening adyen.
=> Fix adyen proguard rules

app/build.gradle.kts, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt, app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectFragment.kt, app/src/test/java/com/hedvig/app/feature/embark/VariableExtractorTest.kt
- APP-740: Do not use delegate when binding view (#659)
- APP-739: Variable extractor crash (#658)
=> Release: 6.0.1

app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenPayinDropInService.kt, app/src/main/java/com/hedvig/app/feature/adyen/payout/AdyenPayoutDropInService.kt, app/src/main/res/values-night/colors_dark.xml, app/src/main/res/values/colors_light.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/theme.xml
- Remove permission from adyen services
- Stop using synchronous integration method in adyen services
- Remove unnecessary adyen theme overrides
=> Adyen Fixes

app/build.gradle.kts, app/src/main/java/com/hedvig/app/ui/compose/Colors.kt, app/src/main/java/com/hedvig/app/ui/compose/Theme.kt, buildSrc/src/main/kotlin/Libs.kt
=> Add dependencies for jetpack compose

app/src/main/java/com/hedvig/app/feature/di/KoinInitializer.kt, app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectFragment.kt
- (hopefully) fix crashes related to trustly webview
- Bonus: Make the app not crash on launch
=> Fix Trustly WebView-crashes

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/chat/viewmodel/ChatViewModel.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/util/BroadcastReceiver.kt, app/src/main/java/com/hedvig/app/util/extensions/ActivityExtensions.kt, app/src/main/java/com/hedvig/app/util/extensions/ContextExtensions.kt
=> (hopefully) fix crashes when quote IDs fail to load

app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressActivity.kt
=> Add string resource for title

app/build.gradle.kts
=> Make the test suite run again

app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> Rename type to remain compatible with schema change

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt
=> Fix a crash

app/build.gradle.kts, app/src/engineering/java/com/hedvig/app/DevelopmentActivity.kt, app/src/engineering/java/com/hedvig/app/ShowkaseModule.kt, app/src/engineering/res/values/style.xml, app/src/main/java/com/hedvig/app/feature/insurance/ui/CrossSell.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/Subheading.kt, app/src/main/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignDialog.kt, buildSrc/src/main/kotlin/Libs.kt
- POC: Add Showkase!
- Update showkase to latest version
=> POC: Add Showkase!

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/PostSignScreen.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/GetPostSignDependenciesUseCase.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
This approach has its limitations, and should probably be considered to be
temporary.
=> APP-787: Select the correct post-sign screen on Offer-screen

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/engineering/java/com/hedvig/app/MockContractDetailViewModel.kt, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/CheckoutLabel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/GradientType.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferQueryExt.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/SignMethodExt.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/StartDateLabel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/OfferQueryInceptionExt.kt, app/src/main/java/com/hedvig/app/util/BroadcastReceiver.kt, app/src/test/java/com/hedvig/app/feature/offer/OfferDateTest.kt, app/src/test/java/com/hedvig/app/feature/offer/OfferItemsBuilderTest.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-791: only show gross price for cross selling offer

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt
=> Respect `gradientOption`s newfound nullability

app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultScreen.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt
=> APP-807: Fix typography on cross selling-result screen

app/src/main/res/layout/offer_fact_area.xml
- Remove unnecessary offer sections
=> APP-800: Remove unnecessary offer sections

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
=> APP-798: Accident SE story title

app/src/main/res/layout/offer_header.xml
=> APP-801: Fix start date button

app/src/main/java/com/hedvig/app/ui/view/ExpandableContentView.kt
=> APP-802: Hide expand button in offer

app/src/main/java/com/hedvig/app/feature/table/Generator.kt
=> APP-804: Use correc layout for details table

app/src/main/java/com/hedvig/app/feature/dismissiblepager/DismissiblePager.kt, app/src/main/java/com/hedvig/app/feature/welcome/WelcomeDialog.kt, app/src/main/java/com/hedvig/app/feature/whatsnew/WhatsNewDialog.kt
=> APP-799: Onboarding click listener

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferAdapter.kt, app/src/main/res/layout/list_text_item.xml, app/src/main/res/layout/offer_header.xml
=> Offer design fixes

app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceViewModel.kt, app/src/main/res/layout/fragment_insurance.xml
=> APP-846: Pull refresh for insurance tab

app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultActivity.kt
=> APP-849: Remove backstack history on Cross-Selling Result Screen

app/src/main/java/com/hedvig/app/feature/insurance/ui/CrossSell.kt
=> Cross sell card click listener

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageItems.kt, app/src/main/java/com/hedvig/app/feature/perils/PerilItem.kt, app/src/main/java/com/hedvig/app/feature/perils/PerilsAdapter.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
Also clean up a lot of code in the process! Nice.
=> APP-865: Fix missing text key on contract detail screen

app/src/androidTest/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultScreenTest.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultScreen.kt
- [ X ] Functionality is covered by an integration test
- [ X ] Functionality is accessible in engineering mode
=> APP-868: Missing insurance name

app/build.gradle.kts, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/tracking/FirebaseTracker.kt, app/src/main/java/com/hedvig/app/util/JSONObject.kt, buildSrc/src/main/kotlin/Libs.kt
=> APP-897: Track events to firebase as well

app/src/main/res/layout/connect_payin_card.xml, app/src/main/res/layout/failed_payments_card.xml, app/src/main/res/layout/home_info_card.xml, app/src/main/res/layout/upcoming_renewal_card.xml, app/src/main/res/layout/warning_card.xml, app/src/main/res/values/styles.xml, app/src/main/res/values/widget_themes.xml
Please see the button "Add payment method" in the info card below. This PR removes the border.
=> Remove border on theme to avoid buttons in card to get a border. Use style for card instead

app/src/main/java/com/hedvig/app/feature/insurance/ui/CrossSell.kt
=> APP-837: Fix ripple color on white buttons

app/src/main/java/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt, app/src/main/java/com/hedvig/app/util/extensions/ContextExtensions.kt
=> APP-943: Show keyboard automatically for embark passages with input views

app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt
=> Make it build, despite the schema change

app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
=> Correct the order of tracking parameters for Cross-Sells

app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt, app/src/main/java/com/hedvig/app/feature/embark/util/VariableExtractor.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/SignQuotesUseCase.kt, app/src/test/java/com/hedvig/app/feature/embark/VariableExtractorTest.kt
=> APP-957: Add file upload variable functionality

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/chat/viewmodel/ChatViewModel.kt, app/src/main/java/com/hedvig/app/feature/chat/viewmodel/UserViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/ProfileViewModel.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/ProfileViewModelImpl.kt, app/src/main/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignDialog.kt, app/src/main/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignViewModel.kt
=> APP-906: Fix/no more mr mutable shared flow

app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderScreen.kt
=> Add string resources

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderFragment.kt
=> APP-1017: Enrich all HTTP requests with app version metadata

app/src/androidTest/java/com/hedvig/app/feature/embark/MoreOptionsTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/home/GraphQLErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/ContractDetailErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/tab/ErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/insurance/terminatedcontracts/ErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/keygear/Error.kt, app/src/androidTest/java/com/hedvig/app/feature/offer/ErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/onboarding/MoreOptionsTest.kt, app/src/androidTest/java/com/hedvig/app/feature/profile/ErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/referrals/editcode/GenericErrorTest.kt, app/src/androidTest/java/com/hedvig/app/feature/sunsetting/SunsettingTest.kt, app/src/androidTest/java/com/hedvig/app/util/ApolloMockServer.kt, app/src/engineering/java/com/hedvig/app/DevelopmentActivity.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/sunsetting/ForceUpgradeActivity.kt, app/src/main/java/com/hedvig/app/util/apollo/SunsettingInterceptor.kt
- Revert "Revert "APP-909: Sunsetting Error Middleware (#784)" (#788)"
- Stop using a singletonic interceptor
=> Fix the sunsetting middleware

app/src/main/java/com/hedvig/app/feature/claims/ui/ClaimsViewModel.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/pledge/HonestyPledgeBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/util/featureflags/DebugFeatureFlagProvider.kt, app/src/main/java/com/hedvig/app/util/featureflags/Feature.kt, app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt
=> APP-1026: Add feature flag for embark claims

app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeModel.kt, app/src/main/res/layout/home_start_claim_contained.xml, app/src/main/res/layout/home_start_claim_outlined.xml
=> APP-1007: Start a claim button change to outlined, fix copy and when it appears

app/build.gradle.kts, gradle/libs.versions.toml
Updates after input taken from https://github.com/airbnb/Showkase/issues/189 issue
=> Update build config to only have showkase on non production builds

app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt
=> Set read timeout to 0 for uploads to avoid timeouts on client

app/src/main/java/com/hedvig/app/feature/home/ui/claimstatus/data/ClaimTypeData.kt
Context:
https://hedviginsurance.slack.com/archives/C01UKJRB8JD/p1636365750008600
=> Adjust string keys after change in lokalise

app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/util/featureflags/DebugFeatureFlagProvider.kt, app/src/main/java/com/hedvig/app/util/featureflags/Feature.kt, app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt
=> Hide Claims Status behind a feature flag

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellTracker.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailViewModel.kt, app/src/main/java/com/hedvig/app/service/push/managers/CrossSellNotificationManager.kt
=> APP-999: Track Cross-Sell Notifications

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellTracker.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailViewModel.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellNotificationMetadata.kt, app/src/main/java/com/hedvig/app/service/push/managers/CrossSellNotificationManager.kt
=> Track title and body as well for cross sell-notifications

app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt
=> Enable embark claims flow and claims status for production

app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailActivity.kt
=> Fix cross-sell detail crash

app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt
We'll re-flag it once we have proper notes in place.
=> Unflag claims

app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt
This reverts commit cd6ec4202c6c25234ba83680bb17628f8dc14096.
=> Revert "Unflag claims (#803)"

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/sendOtpCode.graphql, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/askforprice/AskForPriceInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/genericauth/CreateOtpAttemptUseCase.kt, app/src/main/java/com/hedvig/app/feature/genericauth/GenericAuthActivity.kt, app/src/main/java/com/hedvig/app/feature/genericauth/GenericAuthViewModel.kt, app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputActivity.kt, app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputScreen.kt, app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputViewModel.kt, app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/ReSendOtpCodeUseCase.kt, app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/SendOtpCodeUseCase.kt, app/src/main/java/com/hedvig/app/feature/settings/Market.kt, app/src/main/java/com/hedvig/app/ui/compose/composables/ErrorDialog.kt, app/src/main/java/com/hedvig/app/ui/compose/composables/FullScreenProgressOverlay.kt, app/src/main/java/com/hedvig/app/ui/compose/composables/appbar/TopAppBarWithBack.kt, app/src/main/java/com/hedvig/app/util/ErrorEvent.kt, app/src/main/java/com/hedvig/app/util/extensions/ActivityExtensions.kt, app/src/main/res/drawable/ic_hedvig_h_progress.xml, app/src/main/res/values-night/colors_dark.xml, app/src/main/res/values/colors_light.xml, app/src/test/java/com/hedvig/app/feature/genericauth/OtpInputViewModelTest.kt, app/src/test/java/com/hedvig/app/util/coroutines/MainCoroutineRule.kt
=> APP-1039: Generic Auth, OTP Input

app/src/main/java/com/hedvig/app/feature/embark/GraphQLQueryUseCase.kt, app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt, app/src/main/java/com/hedvig/app/feature/embark/computedvalues/TemplateExpressionCalculator.kt
=> Fix nulls being stored as `"null"` in Embark Store

app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/chat/usecase/TriggerFreeTextChatUseCase.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
=> APP-1103: Fix post-claim chat not strictly speaking working

app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceContent.kt, app/src/main/java/com/hedvig/app/ui/compose/textutil/SwedishSSNVisualTransformation.kt
=> Swedish SSN VisualTransormation

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionParameter.kt, app/src/main/res/layout/embark_select_action_item.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> APP-993: Add badge-support to select actions

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerParameter.kt
=> APP-1107: Store selected insurance provider

app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/askforprice/AskForPriceInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceSuccess.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceViewModel.kt, app/src/test/java/com/hedvig/app/feature/embark/passages/RetrievePriceViewModelTest.kt
=> APP-754: Insurely success screen

.github/workflows/pr.yml, apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/embark/util/ExpressionExt.kt, app/src/main/java/com/hedvig/app/feature/embark/util/OfferKeys.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt
=> APP-1128: Handle varianted offer redirects

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/util/featureflags/DebugFeatureFlagProvider.kt, app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt, app/src/main/res/layout/change_address_pending_change_card.xml, app/src/main/res/values/widget_themes.xml
=> APP-1133: Moving flow NO 

app/src/engineering/java/com/hedvig/app/MockContractDetailViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt
=> APP-1134:Insurely information fetching inside offer screen

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/BaseActivity.kt, app/src/main/java/com/hedvig/app/ScreenTracker.kt, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenConnectPayinActivity.kt, app/src/main/java/com/hedvig/app/feature/connectpayin/ConnectPaymentResultFragment.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultActivity.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressActivity.kt, app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/result/ChangeAddressResultActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInTracker.kt, app/src/main/java/com/hedvig/app/feature/marketpicker/MarketSelectedFragment.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/onboarding/ui/ChoosePlanActivity.kt, app/src/main/java/com/hedvig/app/feature/tracking/FirebaseTracker.kt, app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectPayinActivity.kt
=> APP-1137: Analytics screen names

app/src/engineering/java/com/hedvig/app/MockContractDetailViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/claims/service/ClaimsTracker.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderViewModel.kt, app/src/main/java/com/hedvig/app/feature/insurance/service/InsuranceTracker.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt
=> APP-1140: Add events for claims flow

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/adyen/payin/AdyenConnectPayinActivity.kt, app/src/main/java/com/hedvig/app/feature/connectpayin/ConnectPaymentViewModel.kt, app/src/main/java/com/hedvig/app/feature/documents/DocumentAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/documents/DocumentsFragment.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferTracker.kt, app/src/main/java/com/hedvig/app/feature/offer/quotedetail/QuoteDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/feature/perils/PerilsAdapter.kt, app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectFragment.kt
=> APP-1141, APP-1142: Add events for links and connect payment

app/src/main/java/com/hedvig/app/authenticate/insurely/InsurelyDialog.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/GetInsuranceProvidersUseCase.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/askforprice/AskForPriceInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/insurely/RetrievedInfo.kt
=> Store dataCollectionId

app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
=> Embark action API

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/authenticate/insurely/InsurelyAuthViewModel.kt, app/src/main/java/com/hedvig/app/authenticate/insurely/InsurelyDialog.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/askforprice/AskForPriceInfoActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceActivity.kt
=> APP-1159: Persist ssn in value store for insurely

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/authenticate/insurely/InsurelyAuthViewModel.kt, app/src/main/java/com/hedvig/app/authenticate/insurely/InsurelyDialog.kt
=> APP-1158: Start auth automatically for Insurely

app/src/main/java/com/hedvig/app/authenticate/AuthenticateDialog.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/InsurerProviderBottomSheet.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerAdapter.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerItem.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerParameter.kt
=> APP-1165, APP-1161: Pass current insurer id when creating quote

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/upcomingAgreement.graphql, app/src/engineering/java/com/hedvig/app/feature/changeaddress/ChangeAddressMockActivity.kt, app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetUpcomingAgreementUseCase.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoAdapter.kt, app/src/main/java/com/hedvig/app/util/apollo/UpcomingAgreementExt.kt, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/builders/UpcomingAgreementBuilder.kt
Previously we checked upcoming agreement change on contract level, this is not scalable. Since we dont get address for every contract we need to remove this field.
=> APP-1150: Generify upcoming agreement

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql, app/src/main/java/com/hedvig/app/feature/embark/passages/addressautocomplete/AddressAutoCompleteFragment.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/addressautocomplete/AddressAutoCompleteParams.kt, app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt, app/src/main/java/com/hedvig/app/util/featureflags/DebugFeatureFlagProvider.kt, app/src/main/java/com/hedvig/app/util/featureflags/Feature.kt, app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt, app/src/main/res/layout/fragment_embark_address_auto_complete_action.xml, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/DatePickerActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/MultiActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/NumberActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/NumberActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PreviousInsurerActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/SelectActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/TextActionSetBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt
=> APP-1155: Address auto complete embark data

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/providerStatus.graphql, app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/insurely/FailedToRetrieveInfo.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/insurely/InsurelyCard.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/insurely/RetrievedInfo.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/datacollectionstatus/DataCollectionStatus.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/providerstatus/GetProviderDisplayNameUseCase.kt, app/src/main/java/com/hedvig/app/util/compose/preview/PreviewData.kt, app/src/test/java/com/hedvig/app/feature/offer/usecase/GetProviderDisplayNameUseCaseTest.kt
=> APP-1160: Remove prefix before insurance name

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/checkout/CheckoutViewModel.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
=> APP-1174: Pre-fill checkout email

app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/CommonClaimActivity.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyActivity.kt, app/src/main/java/com/hedvig/app/feature/claims/ui/commonclaim/bulletpoint/BulletPointsAdapter.kt, app/src/main/java/com/hedvig/app/feature/dismissiblepager/DismissiblePageNoTitleFragment.kt, app/src/main/java/com/hedvig/app/feature/dismissiblepager/DismissiblePageTitleFragment.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/util/apollo/ThemedIconUrls.kt
=> APP-1175: Common claims icons

app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/askforprice/AskForPriceInfoContent.kt
=> APP-1226: Fix string res for insurely continue button

app/src/main/java/com/hedvig/app/feature/dismissiblepager/DismissiblePageTitleFragment.kt
=> APP-1227: Fix images in welcome carousel

app/src/engineering/java/com/hedvig/app/feature/offer/MockOfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt
=> APP-1224: Fix sign button

app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerAdapter.kt
=> APP-1241: Name parameters and add collection id to "Other" insurer item in order to show info dialog and not crash.

app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeModel.kt
Now correctly does not show the button as outlined when there were claim status cards showing.
=> APP-1236: Home claim button styling issue when claim status cards are showing

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/loggedin/service/TabNotificationService.kt, app/src/main/java/com/hedvig/app/feature/referrals/ui/tab/ReferralsViewModel.kt, app/src/main/java/com/hedvig/app/service/badge/CrossSellNotificationBadgeService.kt, app/src/main/java/com/hedvig/app/service/badge/ReferralsNotificationBadgeService.kt
PR for what was mentioned here https://github.com/HedvigInsurance/android/pull/876/files#r794343159
=> Fix: Don't make flow returning functions suspending

app/src/engineering/java/com/hedvig/app/feature/chat/ChatMockActivity.kt, app/src/engineering/java/com/hedvig/app/feature/referrals/ReferralsMockActivity.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/chat/service/ChatMessageNotificationReceiver.kt, app/src/main/java/com/hedvig/app/feature/chat/service/ChatNotificationSender.kt, app/src/main/java/com/hedvig/app/feature/chat/service/ReplyWorker.kt, app/src/main/java/com/hedvig/app/feature/tracking/LaunchTrackingInitializer.kt, app/src/main/java/com/hedvig/app/feature/tracking/NotificationOpenedTrackingActivity.kt, app/src/main/java/com/hedvig/app/service/push/PushNotificationService.kt, app/src/main/java/com/hedvig/app/service/push/senders/CrossSellNotificationSender.kt, app/src/main/java/com/hedvig/app/service/push/senders/GenericNotificationSender.kt, app/src/main/java/com/hedvig/app/service/push/senders/NotificationSender.kt, app/src/main/java/com/hedvig/app/service/push/senders/PaymentNotificationSender.kt, app/src/main/java/com/hedvig/app/service/push/senders/ReferralsNotificationSender.kt, app/src/main/java/com/hedvig/app/util/extensions/KoinExtensions.kt
- Preparative refactoring before starting the notification analytics events implementation (#897)
- Implement `notificationPermission`
- Implement `notificationOpened`
=> APP-1381: Notification Analytics-Events

app/src/engineering/java/com/hedvig/app/feature/home/HomeMockActivity.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt, app/src/main/java/com/hedvig/app/feature/home/ui/HomeModel.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/home/Data.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/home/builders/HomeDataBuilder.kt
Some combination of items shown in the home screen was not cooperating and the spacing dependencies between all the different combinations make it hard to add it to a specific item.
This simply adds a Space item to serve the purposes of solving this combination which didn't look nice
Accessible through engineering mode: Home > Terminated with ongoing past claims
| before | after |
| :---: | :---: |
| -<img src="https://user-images.githubusercontent.com/44558292/151165625-3dd3d36b-cd10-4fe6-b0a1-6c3cca372402.png" > | <img src="https://user-images.githubusercontent.com/44558292/151164693-90e4a084-3a73-4ce5-ae6c-fa48c967903a.png" > |
=> APP-1303: Home screen spacing issues

app/src/main/java/com/hedvig/app/feature/addressautocompletion/model/DanishAddressStoreKey.kt
This said "Asåvej Asåvej" before instead of "Asåvej 2"
=> APP-1421: wrong offer query variables

app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteScreen.kt
Change screenshots [here](https://hedvig.atlassian.net/jira/software/c/projects/APP/boards/6?modal=detail&selectedIssue=APP-1426)
=> APP-1426: Make screen go edge to edge on the navigation items

app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteScreen.kt
Before it wasn't possible to look at the last item (Can't find my address) while the keyboard was open
=> APP-1454: Make insets also consider IME height

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/ActivePaymentMethodsFragment.graphql, apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/payment.graphql, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentActivity.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/java/com/hedvig/app/feature/profile/ui/payment/PaymentModel.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/payment/PaymentDataBuilder.kt
=> Use new endpoint for active payment methods in order to show information from third party providers.

app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteScreen.kt
Now works with compose 1.1.0+ 🎉
=> Animate to top of list when a new set of addresses come in

app/src/main/java/com/hedvig/app/feature/adyen/AdyenRepository.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt
It was just the default parameter which meant that we forgot to specify it in the call site so it used that. I removed it all-together to avoid such problems in the future. I don't know what kind of rabbit hole I dug myself into while trying to find this, I misunderstood something completely ☠️
=> APP-1475: Fix approve changes buttons not doing the same thing

app/src/main/java/com/hedvig/app/ApplicationModule.kt
Related to https://hedviginsurance.slack.com/archives/C9K7XRQ0G/p1646809339317739
=> Add long read time out since back-end is not responding quick enough. This is a temporary fix.

app/src/main/java/com/hedvig/app/SplashActivity.kt
May also want to consider removing the existing Sunsetting interceptor completely? Didn't do anything like that before we discuss this between ourselves.
But since we're gonna be using this soon, I can imagine how we might stop using that way of showing the update app screen? If we don't ever stop using that on the backend then we might as well have them both co-exist.
Had to put this in our custom SplashScreen since putting it inside the HedvigApplication made some bad sequence of events to happen, like have this trigger, and then the Splash while doing its work on the background also navigates to the market activity, putting the update app activity on the backstack.
I hope this won't complicate things when we eventually stop doing our own splash like this.
=> Make use of force app update from hAnalytics

app/src/main/java/com/hedvig/app/feature/hanalytics/HAnalyticsExperimentManager.kt, app/src/main/java/com/hedvig/app/feature/hanalytics/HAnalyticsImpl.kt
Nothing special, just to look at what we *actually* get from the experiments, in case unleashed isn't configured correctly, or an cached result is returned or whatever.
=> Simple logging to assist looking in the stack trace

app/src/main/java/com/hedvig/app/feature/offer/ui/composable/VariantButton.kt, app/src/main/java/com/hedvig/app/feature/table/Generator.kt
Reduce border width on variant button. Reduce margin on table sections.
=> APP-1626: Offer UI tweaks

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql, app/src/main/java/com/hedvig/app/feature/insurance/ui/ContractCardViewState.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceContractExtensions.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractExt.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/terminatedcontracts/TerminatedContractsActivity.kt, app/src/main/res/layout/insurance_contract_card.xml, testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt
Draft until the backend is complete (currently errors on many types of contracts)
=> APP-1662: Support variable logos for contract cards

app/build.gradle.kts, app/src/engineering/java/com/hedvig/app/feature/offer/OfferMockActivity.kt, app/src/main/java/com/hedvig/app/authenticate/LoginStatus.kt, app/src/main/java/com/hedvig/app/authenticate/LoginStatusService.kt, app/src/main/java/com/hedvig/app/feature/chat/ui/ChatActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt, app/src/main/java/com/hedvig/app/util/extensions/ActivityExtensions.kt
=> Fix runtime Koin crash when QuoteCartId is null for a non-null field

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/quoteBundleFragment.graphql, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkStoryTesterActivity.kt, testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt
This was never used, and gave an error if not present in PCMS. Talked to Sam and they dont use it on iOS either.
=> APP-1730: Remove unused query field to fix car mutation

app/src/main/java/com/hedvig/app/feature/checkout/CheckoutViewModel.kt, app/src/main/java/com/hedvig/app/feature/checkout/EditCheckoutUseCase.kt, app/src/main/java/com/hedvig/app/feature/insurance/data/GetContractsUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferRepository.kt, app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheetViewModel.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/QuoteCartEditStartDateUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/CreateAccessTokenUseCase.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/StartCheckoutUseCase.kt
Arrow 1.1.x changed some imports around and sequenceEither -> sequence
Plus I saw there are some files that should've been deleted but in some revert we've done the files came back being empty. The lint step had failed as well and after removing them it didn't fail. I think this was a coincidence but good to get rid of those files anyway.
=> Use new import for arrow's `either`

.github/workflows/pr.yml, .github/workflows/staging.yml, ci-prebuild.sh, ci-staging-prebuild.sh
=> Attempt to build for staging target as well

app/src/main/java/com/hedvig/app/ApplicationModule.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceModel.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceFragment.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/terminatedcontracts/TerminatedContractsActivity.kt, app/src/main/java/com/hedvig/app/feature/offer/usecase/StartCheckoutUseCase.kt, app/src/main/java/com/hedvig/app/feature/settings/SettingsViewModel.kt, app/src/main/java/com/hedvig/app/util/apollo/NetworkCacheManager.kt, app/src/main/java/com/hedvig/app/util/apollo/SafeQuery.kt
Also another commit with some additional error handling.
=> APP-1789: Clear cache on language change

app/src/debug/AndroidManifest.xml, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkStoryTesterActivity.kt, app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderScreen.kt
Also snuck in a change inside `EmbarkStoryTesterActivity` to make sure the content is at least inside a clickable area, didn't pay much attention since it's developer only.
=> APP-1899: Audio recorder insets

.editorconfig, app/build.gradle.kts, app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkStoryTesterActivity.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/hedvig/app/feature/claimdetail/ui/FailedAudioPlayerCard.kt, app/src/main/java/com/hedvig/app/feature/claimdetail/ui/FakeWaveAudioPlayerCard.kt, app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailScreen.kt, app/src/main/java/com/hedvig/app/feature/insurance/ui/CrossSell.kt, app/src/main/java/com/hedvig/app/feature/marketing/MarketingActivity.kt, app/src/main/java/com/hedvig/app/feature/marketing/marketpicked/MarketPickedScreen.kt, app/src/main/java/com/hedvig/app/feature/marketing/pickmarket/PickMarketScreen.kt, app/src/main/java/com/hedvig/app/feature/marketing/ui/BackgroundImage.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/insurely/InsurelyCard.kt, app/src/main/java/com/hedvig/app/feature/offer/ui/composable/variants/VariantButton.kt, app/src/main/java/com/hedvig/app/ui/compose/composables/BlurredFullScreenProgressOverlay.kt, app/src/main/java/com/hedvig/app/ui/compose/composables/banner/InfoBanner.kt, app/src/main/java/com/hedvig/app/ui/compose/theme/Colors.kt, core-design-system/build.gradle.kts, core-design-system/src/main/java/com/hedvig/android/core/designsystem/component/BottomSheetHandle.kt, core-design-system/src/main/java/com/hedvig/android/core/designsystem/theme/Colors.kt, core-ui/build.gradle.kts, core-ui/src/main/java/com/hedvig/android/core/ui/scaffold/Scaffold.kt, gradle/libs.versions.toml
Remove the insets dependency completely but keep the insets-ui from accompanist as there's no alternative for that yet.
More details on each individual commit.
=> APP-1900: Marketing screen bottom sheet fixes

gradle/libs.versions.toml
Brings in all the necessary classes for the IDE to know about as well.
=> Depend on moneta core.

app/build.gradle.kts, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/BackNavigationTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlmutation/GraphQLErrorTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlmutation/NetworkErrorTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlmutation/SuccessTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlquery/GeneratedVariableTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlquery/GraphQLErrorTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlquery/NetworkErrorTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/api/graphqlquery/SuccessTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/redirects/PassedKeyValueRedirectTest.kt, app/src/androidTest/kotlin/com/hedvig/app/feature/embark/selectaction/MultipleOptionApi.kt, app/src/main/kotlin/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderScreen.kt, app/src/main/kotlin/com/hedvig/app/feature/embark/passages/selectaction/ui/SelectActionGrid.kt, app/src/main/kotlin/com/hedvig/app/feature/marketing/pickmarket/PickMarketScreen.kt, core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/theme/HedvigTheme.kt
One with testTagsAsResourceId and one without to test both scenarios
Testing to see if this helps in improving the testing story for the QA ui tests.
=> Add test tags on the two pickers in PickMarketScreen

app/src/main/AndroidManifest.xml
Add adjustResize in android manifest to allow for keyboard to not push view off screen
=> CLX-48: AdjustResize claims flow activity

app/src/main/kotlin/com/hedvig/app/feature/claims/ui/ClaimsFlowActivity.kt
Use odyssey theme to get correct colors
=> CLX-51: Odyssey theme 

README.md, renovate.json
These credentials are encrypted and can only be used by renovate.
=> Add renovate configuration to auth to jitpack

app/src/debug/res/values/strings.xml, app/src/main/kotlin/com/hedvig/app/feature/claims/ui/ClaimsUtil.kt, app/src/release/res/values/strings.xml, app/src/staging/res/values/strings.xml, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ClaimsFlowActivity.kt
Staging still needs to target dev backend which was not the case with the previous setup
=> Add Odyssey url back to :app strings.

app/src/main/res/layout/chat_message_user.xml
Look mum, I can edit xml files 😂
=> Fix chat extra message not rendering properly

auth/src/main/kotlin/com/hedvig/android/auth/interceptor/AuthTokenRefreshingInterceptor.kt
Having the chain.proceed() inside the lock meant that it was locking until the entire request was finished and *then* the lock was released, making the request unnecessarily slow. The only thing we need to be locked behind the mutex is the token acquisition, so this change does this exactly, and continues with the token outside of the lock.
Noticed it when a refresh took 7 seconds to complete, since it was waiting for the entire home query to resolve, and *then* it had a change to continue with the next request that was waiting in line for the entire request to finish, while the token was already fetched and refreshed, and it could've grabbed it from storage and used it to perform the requests in parallel.
=> Mutex lock only the token acquisition part

app/src/main/AndroidManifest.xml
In order to not reset odyssey when rotated
=> Set portrait orientation for claims flow activity 

app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt, app/src/main/kotlin/com/hedvig/app/util/firebase/FirebaseBreadcrumbTimberTree.kt, auth/auth-android/src/main/kotlin/com/hedvig/android/auth/android/AuthenticatedObserver.kt, auth/auth-core/src/main/kotlin/com/hedvig/android/auth/AndroidAccessTokenProvider.kt, auth/auth-core/src/main/kotlin/com/hedvig/android/auth/AuthTokenServiceImpl.kt, auth/auth-core/src/main/kotlin/com/hedvig/android/auth/storage/AuthTokenStorage.kt
And only log Debug and higher in crashlytics
=> Move more logging to verbose for cleaner crashalytics logs

app/src/engineering/kotlin/com/hedvig/app/ShakeInitializer.kt, app/src/engineering/kotlin/com/hedvig/app/feature/tracking/ActivityChangeTracker.kt, app/src/engineering/kotlin/com/hedvig/app/feature/tracking/TrackingInitializer.kt, app/src/main/kotlin/com/hedvig/app/HedvigApplication.kt, app/src/main/kotlin/com/hedvig/app/feature/tracking/LaunchTrackingInitializer.kt
Creates a Application.ActivityLifecycleCallbacks which simply logs all activity creations
=> Log all new activity changes to firebase

app/src/main/kotlin/com/hedvig/app/feature/claims/ui/ClaimsUtil.kt, app/src/main/kotlin/com/hedvig/app/feature/claims/ui/commonclaim/CommonClaimActivity.kt, app/src/main/kotlin/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailScreen.kt, app/src/main/kotlin/com/hedvig/app/feature/home/ui/HomeFragment.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ClaimsFlowActivity.kt, testdata/src/main/kotlin/com/hedvig/app/testdata/dashboard/Data.kt
It breaks when entering the flow. Might be due to `1.2.10` not working properly.
=> Send down common claim ID instead of itemType+itemProblem

app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationActivity.kt, app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationViewModel.kt
Nothing special, just some logs I added while testing DK login locally with my newly made fake member, might help deducing what's going on.
=> CLX-351: Add some logs to simple sign

app/src/main/AndroidManifest.xml
We didn't have it before and it's a new one for >=SDK 33. Better add it since I noticed it's missing
=> Add POST_NOTIFICATIONS permission

feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/InputViewModel.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/DateOfOccurenceAndLocation.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/InputRoot.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/MonetaryAmountInput.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/SingleItem.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/summary/EditClaimScreen.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/model/Claim.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/model/Input.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/network/UpdateAutomationClaimRequest.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/repository/MockClaimsFlowRepository.kt
Did only include edit functionality for now, not this one: https://www.figma.com/file/klLSfgShhdy1n37O2nXf3d/Claims-1.1?node-id=1325%3A32947&t=UWWSv4mk1dAT0BdP-0
=> CLX-381: Summary screen

app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoAdapter.kt, core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigTypography.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/OdysseyClaimsFlowActivity.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/model/SearchableClaim.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/GetNetworkClaimEntryPointsUseCase.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchActivity.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchViewModel.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/ui/CommonClaims.kt, feature-odyssey/src/main/res/drawable/ic_list_item_indicator.xml
Not getting the correct claim flows for some of these entrypoints, talking to Linus about that. We also want to get the "Other" option last in the list.
=> CLX-339: Claims triaging design

app/src/release/res/values/strings.xml
Same as iOS
https://github.com/HedvigInsurance/ugglan/commit/b186ae10ee43318148c9263d75213815eecfbba5
=> Point prod hAnalytics to K8S

apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/payment.graphql, apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/profile.graphql, apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/referrals.graphql, app/src/main/kotlin/com/hedvig/app/feature/profile/ui/payment/PaymentAdapter.kt, app/src/main/kotlin/com/hedvig/app/feature/profile/ui/tab/ProfileQueryDataToProfileUiStateMapper.kt, app/src/main/kotlin/com/hedvig/app/feature/referrals/ui/tab/ReferralsAdapter.kt, app/src/main/res/layout/campaign_information_section.xml, testdata/src/main/kotlin/com/hedvig/app/testdata/feature/payment/PaymentDataBuilder.kt, testdata/src/main/kotlin/com/hedvig/app/testdata/feature/profile/builders/ProfileDataBuilder.kt, testdata/src/main/kotlin/com/hedvig/app/testdata/feature/referrals/builders/ReferralsDataBuilder.kt
`insuranceCost` is not working correctly and will be deprecated soon. `chargeEstimation` is the new way to go!
=> CLX-520: Show correct charge amount

app/src/main/kotlin/com/hedvig/app/feature/crossselling/ui/CrossSellData.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchActivity.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchViewModel.kt
=> CLX-467: Search claim error handling

apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/FragmentAudioContent.graphql, apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/claimflow/FragmentClaimFlowStepFragment.graphql, app/src/main/kotlin/com/hedvig/app/feature/referrals/ui/tab/ReferralsAdapter.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/ClaimFlowStep.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/di/OdysseyModule.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowDestination.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowGraph.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingDestination.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingViewModel.kt, feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/ui/AudioRecorder.kt
Adapts to the changes in the backend
Context:
https://studio.apollographql.com/graph/Octopus-fxevz/variant/staging/launches/1f281c0c-ada8-4076-b7fd-1efe5a01f749
and
https://hedviginsurance.slack.com/archives/C03RP2M458V/p1681979224772009
=> Use AudioContent from audio claim flow step

app/feature/odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/di/OdysseyModule.kt
Was crashing the app when Feature.CLAIMS_TRIAGING was off
=> Add SearchViewModel to the di graph

app/core/design-system/src/main/res/drawable/ic_checkmark.xml, app/core/ui/src/main/kotlin/com/hedvig/android/core/ui/ValidatedInput.kt, app/feature/changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ChangeAddressUiState.kt, app/feature/changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ChangeAddressViewModel.kt, app/feature/changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressOfferDestination.kt, app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/TravelCertificateUiState.kt, app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/AddCoInsured.kt, app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/GenerateTravelCertificateInput.kt
=> Add composables for travel certificate input and add co-insured views

build-logic/convention/src/main/kotlin/ApolloConventionPlugin.kt
Context:
https://github.com/apollographql/apollo-kotlin/issues/4925#issuecomment-1562693336
=> Fix breaking configuration for apollo download task

app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/data/DownloadTravelCertificateUseCase.kt, app/feature/travel-certificate/src/main/res/xml/file_paths.xml
Do this to avoid "Failed to find configured root"-crash
=> Download travel certificate to internal app storage directory

app/feature/odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/dateofoccurrence/DateOfOccurrenceViewModel.kt
Fixes the screen not being interactive due to this functionality.
This was probably due to a different assumption we had in the past that for this screen you *had* to submit a date, but not submitting any state should be a valid input too.This change fixes this so that the button is considered interactive when we are in this state without a date selection, and also allows the date card itself to be clickable in that scenario too.
=> Allow date step to submit null date

app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/Forever.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/ForeverFilled.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/Home.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/HomeFilled.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/Insurance.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/InsuranceFilled.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/Profile.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/nav/ProfileFilled.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/hedviguikit/HedvigIcons.kt
=> GEN-733: Navigation icons

.idea/runConfigurations/Design_Showcase.xml, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/colored/Chat.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/colored/ColoredCircleWithCampaign.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/colored/FirstVet.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/compose/NotificationCircle.kt, app/core/icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/compose/NotificationCircleWithSubtractingPadding.kt, app/feature/odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/honestypledge/PledgeAcceptingSlider.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/hedviguikit/HedvigIcons.kt
=> GEN-731: Colored misc icons with the notification circle on them + nav icons

app/apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/profile.graphql, app/apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/updateEmail.graphql, app/apollo/giraffe/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/updatePhoneNumber.graphql, app/apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/member/FragmentMemberData.graphql, app/apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/member/MemberUpdatePhoneEmail.graphql, app/apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/member/MemberUpdatePhoneNumber.graphql, app/apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/profile/profile.graphql, app/app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/data/ProfileData.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/data/ProfileRepository.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/ui/myinfo/MyInfoActivity.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/ui/myinfo/MyInfoViewModel.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/ui/tab/ProfileDestination.kt, app/app/src/main/kotlin/com/hedvig/app/feature/profile/ui/tab/ProfileViewModel.kt, app/app/src/test/kotlin/com/hedvig/app/feature/profile/ui/tab/ProfileViewModelTest.kt, app/market/market-core/src/main/kotlin/com/hedvig/android/market/Market.kt, app/testdata/src/main/kotlin/com/hedvig/app/testdata/feature/profile/builders/ProfileDataBuilder.kt
Use queries and mutations from octopus instead of giraffe. Refactor profile viewmodel and repository.
=> Refactor profile queries and mutations

app/app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/yourinfo/EditInsuranceBottomSheetContent.kt, app/app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/yourinfo/YourInfoTab.kt, app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeContainedButton.kt, app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeTextButton.kt
=> GEN-720: Edit bottom sheet content

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/appbar/m3/ToolbarChatIcon.kt
=> Fix hedvig chat icon on the top right on Home screen

app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/di/HomeModule.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenter.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeViewModel.kt, app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenterTest.kt, app/member-reminders/member-reminders-ui/src/main/kotlin/com/hedvig/android/memberreminders/ui/MemberReminderCards.kt
We simply do not want to show this specific reminder in the home screen
=> Remove notification reminder from the home screen

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/changeaddress/MutationMoveIntentCreate.graphql, app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/changeaddress/MutationMoveIntentRequest.graphql, app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ChangeAddressViewModel.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/ChangeAddressRepository.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressEnterNewAddressDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressOfferDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressSelectHousingTypeDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/di/ChangeAddressModule.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/navigation/ChangeAddressGraph.kt, hedvig-lint/lint-baseline/lint-baseline-data-settings-datastore-public.xml, hedvig-lint/lint-baseline/lint-baseline-data-settings-datastore-test.xml
=> Temporarily comment out most of the new moving_flow

app/app/src/main/kotlin/com/hedvig/app/feature/marketing/pickmarket/PickMarketScreen.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/settings/SettingsDestination.kt, app/market/market-core/src/main/kotlin/com/hedvig/android/market/Language.kt, app/market/market-core/src/main/kotlin/com/hedvig/android/market/Market.kt
Also availableLanguages was not used anywhere it seems
=> Move to `val` from `fun`

app/core/core-icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/flag/FlagUk.kt, app/core/core-icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/logo/HedvigLogotype.kt
UK flag and the logo for login screen
=> More vector icons

app/app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt, app/datadog/datadog-core/src/main/kotlin/com/hedvig/android/datadog/core/OkHttpDatadogUtil.kt
Should fix datadog APM integration
=> Add firstPartyHosts for giraffe and octopus

app/apollo/apollo-giraffe-public/src/main/graphql/com/hedvig/android/apollo/giraffe/graphql/home.graphql, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCaseDemo.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCaseImpl.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenter.kt, app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/data/GetHomeUseCaseTest.kt, app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenterTest.kt
New design specifies no name to be shown there anymore
=> Remove "name" from home screen

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/PaymentOverviewDestination.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/PaymentOverviewPresenter.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/PaymentOverviewViewModel.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/di/PaymentsModule.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/navigation/PaymentsDestination.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments2/navigation/PaymentsGraph.kt
=> Add payments overview screen

app/app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt, app/app/src/main/kotlin/com/hedvig/app/feature/chat/service/ChatMessageNotificationReceiver.kt, app/app/src/main/kotlin/com/hedvig/app/feature/chat/service/ChatNotificationSender.kt, app/app/src/main/kotlin/com/hedvig/app/feature/chat/service/ReplyWorker.kt, app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/DebugBorder.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatPresenter.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatViewModel.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/di/ChatModule.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatDestination.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt
* Remove unused error message
* Remove unused DisabledByFeatureFlag state
It was never used anymore ever since Demo implementation ChatRepository
was added.
* Properly hookup ReplyWorker to the new ChatRepository
=> Chat bug fixes

app/core/core-icons/src/main/kotlin/com/hedvig/android/core/icons/hedvig/compose/NotificationCircle.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
Render a notification dot on the chat icon
=> Use the unread chat information from HomePresenter

app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryDemo.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryImpl.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/di/ChatModule.kt
When new messages arrive, mark the newest one as the newest timestamp seen
=> Chat notification update latest timestamp

app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt, app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt
Also open web url instead of defaulting to home deeplink.
=> Center quick links and common claims text

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterGraph.kt
It was already there, this just hooks it up to the right destination
=> Use the deep link to help-center

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/referrals/QueryReferrals.graphql, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryImpl.kt, app/tracking/tracking-core/src/main/kotlin/com/hedvig/android/core/tracking/LogAction.kt, build-logic/convention/src/main/kotlin/KotlinLibraryConventionPlugin.kt, build-logic/convention/src/main/kotlin/com/hedvig/android/KotlinAndroid.kt
This also sets it up so that the module which adds logError and logAction is available to *all* other modules
=> Analytics for chat fetching error

app/feature/feature-connect-payment-trustly/build.gradle.kts, app/feature/feature-connect-payment-trustly/src/main/kotlin/com/hedvig/android/feature/connect/payment/trustly/ui/TrustlyDestination.kt, app/feature/feature-connect-payment-trustly/src/main/kotlin/com/hedvig/android/feature/connect/payment/trustly/webview/TrustlyJavascriptInterface.kt, app/feature/feature-connect-payment-trustly/src/main/kotlin/com/hedvig/android/feature/connect/payment/trustly/webview/TrustlyWebChromeClient.kt
Add trustly javascript interface and webchrome client to webview in order to listen to url scheme and open bankid.
=> Fix connect payment BankID signing

app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt, app/tracking/tracking-core/src/main/kotlin/com/hedvig/android/core/tracking/LogAction.kt, app/tracking/tracking-core/src/main/kotlin/com/hedvig/android/core/tracking/RumLogger.kt, app/tracking/tracking-datadog/src/main/kotlin/com/hedvig/android/tracking/datadog/ActionLoggerInitializer.kt, app/tracking/tracking-datadog/src/main/kotlin/com/hedvig/android/tracking/datadog/DatadogRumLogger.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcaseActivity.kt
As discussed the previous week, just forgot to push this 🥸
=> Rename action logger to RumLogger

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/FilesLazyVerticalGrid.kt, app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/ui/AddFilesDestination.kt, app/feature/feature-delete-account/src/main/kotlin/com/hedvig/android/feature/deleteaccount/DeleteAccountPresenter.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/fileupload/AddFilesScreen.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/fileupload/FileUploadScreen.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/ui/ClaimFlowScaffold.kt
Before:
https://github.com/HedvigInsurance/android/assets/44558292/e71fd9df-e42a-4cf0-866e-0a14193e9d8e
After:
https://github.com/HedvigInsurance/android/assets/44558292/2236ccb0-493e-4d9b-beda-92544ec801c6
=> Fix claim flow scrollable screens

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/grid/HedvigGrid.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterPresenter.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterViewModel.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/question/HelpCenterQuestionDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/topic/HelpCenterTopicDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/ui/HelpCenterSection.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/ui/StillNeedHelpSection.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewhen/TravelCertificateDateInputViewModel.kt, app/language/language-test/src/main/kotlin/com/hedvig/android/language/test/FakeLanguageService.kt
While at that screen, also fixed the chat section at the bottom to go under the system bar as per the design
The color difference under the bottom part of the screen is visible here
Before:
After:
=> Fix grid bug

app/app/build.gradle.kts, gradle/libs.versions.toml
I think we are no longer using this at all, wanna see if CI passes after removing it now
=> Remove mockk

app/feature/feature-changeaddress/build.gradle.kts, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/ChangeAddressRepository.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/di/ChangeAddressModule.kt
Report a successful self serve when the moving flow is finished successfully
=> Moving flow self serve completion

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/scaffold/ClaimFlowScaffold.kt, app/feature/feature-claim-triaging/build.gradle.kts, app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/ClaimTriagingGraph.kt, app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/claimentrypointoptions/ClaimEntryPointOptionsDestination.kt, app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/claimentrypoints/ClaimEntryPointsDestination.kt, app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/claimgroups/ClaimGroupsDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/AudioRecordingDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/dateofoccurrence/DateOfOccurrenceDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/dateofoccurrencepluslocation/DateOfOccurrencePlusLocationDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/fileupload/AddFilesScreen.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/fileupload/FileUploadScreen.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/honestypledge/HonestyPledgeDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/ConfirmEmergencyDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectCarOtherDamageDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectGlassDamageDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectPestsDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectTowingDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/location/LocationDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/notificationpermission/NotificationPermissionDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/phonenumber/PhoneNumberDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/selectcontract/SelectContractDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/singleitem/SingleItemDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/singleitemcheckout/SingleItemCheckoutDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/summary/ClaimSummaryDestination.kt
Change Triaging destinations scaffolds to ClaimFlowScaffold, so it would show the warning dialog when trying to close the claimFlow from these three screens too.
=> change triaging scaffolds to ClaimFlowScaffold

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/preview/ConvenienceCollectionPreviewParameterProvider.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/history/PaymentHistoryDestination.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/overview/data/GetPaymentOverviewDataUseCase.kt
This avoids doing list operations in-between the UI code mostly
=> Make PaymentHistoryDestination use a local PaymentHistory

app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddOrRemoveDestination.kt
tiniest change: add missing spacing
=> add missing

app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/data/Discount.kt
Oops! Without this it didn't know how to serialize ExpiredState
=> Fix missing serialization annotation

app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt, app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt
Add visual transformation to ssn with a mask and check explicitly for ssn.length of 12
=> add visual transformation to ssn

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/travelcertificate/QueryTravelCertificateSpecifications.graphql, app/data/data-travel-certificate/data-travel-certificate-public/src/main/kotlin/com/hedvig/android/data/travelcertificate/GetTravelCertificateSpecificationsUseCase.kt, app/data/data-travel-certificate/data-travel-certificate-public/src/test/kotlin/com/hedvig/android/data/travelcertificate/GetTravelCertificateSpecificationsUseCaseTest.kt
the infosections in the travelCertificateSpecifications are deprecated now
=> delete unused infosections

app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/swedishlogin/SwedishLoginPresenter.kt
tiny fix: navigate to demo mode
=> navigate to demo mode

lokalise-gradle-plugin/lokalise/src/main/kotlin/com/hedvig/android/lokalise/task/DownloadStringsTask.kt
This also stops downloading the FR translations, and removes the workaround we had in there.
The important change comes from the POST body we send with `put("escape_percent", true)` here, which is described here https://developers.lokalise.com/reference/download-files. It turns `[%]` from lokalise translations to `%%` in our xml result
=> Fix lokalise translations

app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/preview/HedvigPreview.kt, app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/HedvigDateTimeFormatter.kt, app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/FetchCoInsuredPersonalInformationUseCase.kt, app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt, app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt, app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt
- not enforcing to fill every Co-insured missing info anymore
- auto-toggle manual info and show explanation if fetching personal info by ssn comes empty. better explained here : [link](https://hedviginsurance.slack.com/archives/C05TQ9TFQ6M/p1717074624499319?thread_ts=1717062641.851049&cid=C05TQ9TFQ6M)
=> GEN-2108 Fix/coinsured underage

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/claimflow/MutationFlowClaimStart.graphql, app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowRepository.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/ui/TerminationInfoCard.kt
this ticket: [link](https://www.notion.so/hedviginsurance/Feature-flag-Available-steps-from-App-to-Odyssey-59679402cb404707b891ecc3ea6af510?pvs=4)
=> GEN-2071 Fix/supported claimflow steps

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/CheckBoxGroup.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Checkbox.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/RadioGroup.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/RadioOption.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/CheckboxTokens.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/RadioOptionTokens.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/choose/ChooseInsuranceToTerminateDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt, app/feature/feature-travel-certificate/build.gradle.kts, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewho/TravelCertificateTravellersInput.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/radio/RadioGroups.kt
checkbox and some padding fix for radio-buttons too
=> New design checkbox

app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/terminatedcontracts/TerminatedContractsDestination.kt
Context:
https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1719482725173669
=> Remove info card

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/termination/FragmentTerminationFlowStepFragment.graphql, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminationSurveyOption.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyViewModel.kt, app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyPresenterTest.kt
* Query description and button text for the suggestion card 
* Disable continue button if selected option contains a suggestion
=> GEN-2431: Update termination survye

app/feature/feature-chat/src/main/graphql/MutationChatSendFile.graphql, app/feature/feature-chat/src/main/graphql/MutationChatSendMessage.graphql, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryImpl.kt
Context:
https://hedviginsurance.slack.com/archives/C075NGQ600Z/p1719491720899459?thread_ts=1719473535.561569&cid=C075NGQ600Z
=> Stop querying for unused status

app/feature/feature-chat/src/main/graphql/FragmentConversationInfo.graphql, app/feature/feature-chat/src/main/graphql/QueryChatConversations.graphql, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/CbmChatRepository.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/CbmChatViewModel.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/data/CbmChatRepositoryDemo.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/data/GetAllConversationsUseCase.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/inbox/InboxDestination.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/model/InboxConversation.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/ui/ChatDestination.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/ui/ChatLoadedScreen.kt
https://hedviginsurance.slack.com/archives/C075NGQ600Z/p1723024876361639
=> title and subtitle are removed in favor of claimType and fallbacks

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/BottomSheetTokens.kt
forgot to set up actual arrow colors :)
=> set up arrow colors

app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/cbm/CbmChatRepository.kt
Ref: https://hedviginsurance.slack.com/archives/C075NGQ600Z/p1723556945645839?thread_ts=1723555145.651149&cid=C075NGQ600Z
=> Make sure to always fetch from network as well to avoid stale info

app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/payments/PaymentsDestination.kt
=> switch pending and connected

app/design-system/design-system-hedvig/build.gradle.kts, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigTextField.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/freetext/FreeTextOverlay.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/freetext/FreeTextTriggerDisplay.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/internal/HedvigTextFieldImpl.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/FreeTextTokens.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcase.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/freetext/FreeTextShowcase.kt
That's basically 2 separate elements. Interactive full screen FreeTextOverlay which is also a container for the content that it is shown above of, and it can be triggered by anything, ex. by some button or by the second element, FreeTextDisplay.
Basically what we done in the Termination Survey
=> GEN-2337 New design/free text

app/app/build.gradle.kts, app/design-system/design-system-hedvig/build.gradle.kts, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Button.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/datepicker/DatePicker.kt, app/design-system/design-system-internals/build.gradle.kts, app/design-system/design-system-internals/src/main/AndroidManifest.xml, app/design-system/design-system-internals/src/main/kotlin/com/hedvig/android/design/system/internals/DatePicker.kt, app/feature/feature-changeaddress/build.gradle.kts, app/feature/feature-connect-payment-trustly/build.gradle.kts, hedvig-lint/lint-baseline/lint-baseline-design-system-internals.xml, micro-apps/design-showcase/build.gradle.kts, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcase.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/datepicker/DatePickerShowcase.kt
So now design-system-internals has dependency on material:)
=> GEN-2346 date picker

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterGraph.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/commonclaim/emergency/EmergencyDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetQuickLinksUseCase.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/navigation/HelpCenterDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/navigation/ClaimFlowGraph.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectEmergencyDestination.kt, app/ui/ui-emergency/src/main/kotlin/com/hedvig/android/ui/emergency/EmergencyScreen.kt
ticket: [ticket](https://www.notion.so/hedviginsurance/a4c35052b6794b36a4b0d58b537cc325?v=c74a8cb958ab4ba6ba4c904d8540b106&p=6c50bcf6955f477588039ccb61ad2641&pm=s)
figma: [figma](https://www.figma.com/design/WlwFCAWywXNcXVgPfYVmWu/Final-Design?node-id=13270-61431&t=2iQkzOUKKfWnH5LV-0)
Also, as a thought - this seems to be a good place to start implementing the new DS. It's a small separate module and it's hectic with the old DS
=> GEN-2507 SOS url button

app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/myinfo/MyInfoDestination.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileGraph.kt, app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt
First half of this
https://www.notion.so/hedviginsurance/Add-new-push-notification-TYPE-handling-in-the-apps-OPEN_CONTACT_INFO-0ada803c184343cb83f8f8b2ebf841bd?d=c579f34f37354cb9aa2ae9e98ada6f33
Next we need the notification itself too
Links to the screen where the phone number or email can be changed
=> First part of adding support for the new notification type by adding the deep link support

app/feature/feature-movingflow/build.gradle.kts, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt, app/ui/ui-tiers-and-addons/build.gradle.kts, app/ui/ui-tiers-and-addons/src/main/AndroidManifest.xml, app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteDisplayItem.kt, hedvig-lint/lint-baseline/lint-baseline-ui-tiers-and-addons.xml
Issue: https://www.notion.so/hedviginsurance/130c3f71cb0a80249219eb8a7589a637?v=130c3f71cb0a81d6bc17000c33cc9b68&p=130c3f71cb0a80e0bc0be32d4a4b202b&pm=s
Make moving flow use it as a first step
=> Extract QuoteCard into a common module

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-connect-payment-trustly/src/main/kotlin/com/hedvig/android/feature/connect/payment/trustly/navigation/ConnectTrustlyPaymentGraph.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/navigation/HomeGraph.kt
Improves the error message to refer to the chat, and adds a back button too on the top left too
=> Make non SE payment screen open chat instead of just going back

app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/FetchCoInsuredPersonalInformationUseCase.kt
smol fix related to this crash: [log](https://app.datadoghq.eu/rum/sessions?query=%40type%3Asession&agg_m=count&agg_m_source=base&agg_t=count&event=AwAAAZMQc5ODtv9GJwAAABhBWk1RYzVPREFBQ0UyLWVZUmt4ek8zMV8AAAAkMDE5MzEwY2ItOTIxOS00ZTVkLWJiZTMtNDdlNGRlOTBiZTFmAAABUw&fromUser=false&track=rum&viz=stream&from_ts=1731682766568&to_ts=1731683666568&live=true)
=> fix outOfBonds crash

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/b314366e-b2ba-4b7d-a4e2-4ba0e31336d0) | <img width="572" alt="image" src="https://github.com/user-attachments/assets/cdb7d8e4-7ec9-49f4-a0e3-4e359bdc54ff"> |
=> Make sheet handle always take up full width

app/feature/feature-force-upgrade/build.gradle.kts, app/feature/feature-force-upgrade/src/main/kotlin/com/hedvig/android/feature/force/upgrade/ForceUpgradeBlockingScreen.kt
| before | after |
| --- | --- |
| <img width="244" alt="image" src="https://github.com/user-attachments/assets/1cf69024-464f-4902-ad41-01a412a15037"> | <img width="244" alt="image" src="https://github.com/user-attachments/assets/f3a8624a-db69-425b-817d-7791ea1455f6"> |
=> GEN-2538: Migrate force-upgrade screen to new DS

app/compose/compose-pager-indicator/build.gradle.kts, app/compose/compose-pager-indicator/src/main/kotlin/com/hedvig/android/compose/pager/indicator/PagerIndicator.kt
Forgot to remove the dependency so we were using 1 wrong composition local it seems
=> pager indicator

app/data/data-product-variant/data-product-variant-public/src/main/kotlin/com/hedvig/android/data/productvariant/ProductVariant.kt
not sure what scar_table is, put it to unknown for now
=> fix scar-table doc type

app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/enternewaddress/EnterNewAddressDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/entervillainfo/EnterVillaInformationDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/selecthousingtype/SelectHousingTypeDestination.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/enternewaddress/EnterNewAddressDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/start/StartDestination.kt
vertical scroll bug from [here](https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1732714163142739)
=> fix for scrolling

app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleViewModel.kt
Persist the selected choice on disk on each selection
This ensures that we persist this choice even for scenarios when we go
to the comparison screen and come back to this after the ViewModel's
StateFlow already turned cold
=> Fix deleting input coming back from comparison table

app/feature/feature-changeaddress/src/main/graphql/MutationMoveIntentCreate.graphql, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/ChangeAddressRepository.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/MoveIntent.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/enternewaddress/EnterNewAddressDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/enternewaddress/EnterNewAddressViewModel.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/entervillainfo/EnterVillaInformationDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/entervillainfo/EnterVillaInformationViewModel.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/selecthousingtype/SelectHousingTypeDestination.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/selecthousingtype/SelectHousingTypeViewModel.kt, app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/navigation/ChangeAddressDestination.kt, app/feature/feature-changeaddress/src/test/kotlin/com/hedvig/android/feature/changeaddress/destination/TestFakes.kt, app/feature/feature-changeaddress/src/test/kotlin/com/hedvig/android/feature/changeaddress/destination/entervillainfo/EnterVillaInformationPresenterTest.kt, app/feature/feature-changeaddress/src/test/kotlin/com/hedvig/android/feature/changeaddress/destination/selecthousingtype/SelectHousingTypePresenterTest.kt, app/feature/feature-movingflow/src/main/graphql/FragmentMoveIntent.graphql, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/data/MovingFlowState.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/addhouseinformation/AddHouseInformationDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/addhouseinformation/AddHouseInformationViewModel.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/enternewaddress/EnterNewAddressDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/enternewaddress/EnterNewAddressViewModel.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/start/StartDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/start/StartViewModel.kt
opening the pr, but want to test better on Monday when the tiers will be back.
=> GEN-2922 Fix/old home insurance duration

app/data/data-contract/data-contract-public/src/main/kotlin/com/hedvig/android/data/contract/ContractType.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/placeholder/Placeholder.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatLoadedScreen.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleViewModel.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileDestination.kt, app/feature/feature-travel-certificate/src/main/graphql/QueryCurrentContracts.graphql, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/data/CheckTravelCertificateAvailabilityForCurrentContractsUseCase.kt, app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverDestination.kt, app/ui/cross-sells/src/main/kotlin/com/hedvig/android/crosssells/CrossSells.kt
We checked if travel certificates "create certificate" button is enabled by checking locally. We have now BE for that (for quite some time, I guess)), and now I stumbled upon it when the button was not there for tiered contracts
=> fix checking travel certificate availability locally

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/RichText.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/ColorLightTokens.kt
Context:
https://www.figma.com/design/SNVLvLq7ztclXiDqqMNXgY/Tiers-%26-Addons-(App)?node-id=3345-34628&t=4NsuAI2044uGXIiw-1
=> Use the new link color from design

app/data/data-addons/src/main/kotlin/com/hedvig/android/data/addons/data/GetTravelAddonBannerInfoUseCase.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Toggle.kt, app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt, app/feature/feature-movingflow/src/main/graphql/MutationMoveIntentRequest.graphql, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/data/MovingFlowQuotes.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/history/CertificateHistoryViewModel.kt
=> Change bottom sheet info to not come from backend

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigScaffold.kt, app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/travelinsuranceplusexplanation/TravelInsurancePlusExplanationDestination.kt
I thought I'd have to go over all call-sites, but this should suffice to not clip the items at the bottom, but this suffices.
=> Scaffold without insets clipping

app/app/build.gradle.kts, app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatDestination.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatLoadedScreen.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/navigation/CbmChatGraph.kt, app/feature/feature-image-viewer/build.gradle.kts, app/feature/feature-image-viewer/src/main/AndroidManifest.xml, app/feature/feature-image-viewer/src/main/kotlin/com/hedvig/android/feature/imageviewer/ImageViewerDestination.kt, app/feature/feature-image-viewer/src/main/kotlin/com/hedvig/android/feature/imageviewer/navigation/ImageViewer.kt, app/feature/feature-image-viewer/src/main/kotlin/com/hedvig/android/feature/imageviewer/navigation/ImageViewerGraph.kt, gradle/libs.versions.toml, hedvig-lint/lint-baseline/lint-baseline-feature-image-viewer.xml
Clicking on any image should take one to the full screen version of it The image is also zoomable
=> Add image viewer for images in chat

app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/travelinsuranceplusexplanation/TravelInsurancePlusExplanationDestination.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceDestination.kt, app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt
From https://www.notion.so/hedviginsurance/128c3f71cb0a819e8688c5b0277c0944?v=128c3f71cb0a81d69c3c000c910c7e8e&p=188c3f71cb0a80c1a512e4da1a979eec&pm=s
=> Design: Adjust UI according to feedback

app/apollo/apollo-core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/icon/CollapseContent.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/icon/ExpandContent.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/ControllerState.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/Media.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/MediaState.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/ResizeMode.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/SimpleVideoController.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/videoplayer/TimeBar.kt, app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/data/GetTravelAddonOfferUseCase.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatLoadedScreen.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt
Just fixed all the errors ktlint was upset about.
Also moved all things in the ExoPlayer creation into the `remember` so they don't accidentally run more than we need, and added all inputs as keys so they don't accidentally become stale if the inputs were ever to change
=> Chat video ktlint fixes

app/feature/feature-help-center/src/main/graphql/QueryHelpCenterFAQ.graphql, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterGraph.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterPresenter.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterViewModel.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetHelpCenterFAQUseCase.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetHelpCenterQuestionUseCase.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetHelpCenterTopicUseCase.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/di/HelpCenterModule.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/navigation/HelpCenterDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/question/HelpCenterQuestionDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/question/HelpCenterQuestionViewModel.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/topic/HelpCenterTopicDestination.kt, app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/topic/HelpCenterTopicViewModel.kt
sorry, last commit's name is just accidentally copied) added deeplinks to destinations there
=> GEN-3238 Feature/help center from be

app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetQuickLinksUseCase.kt
=> GEN-3288: Move "Change address" to "Quick actions"

app/app/src/main/kotlin/com/hedvig/android/app/apollo/LoggingInterceptor.kt, app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt, app/data/data-addons/build.gradle.kts, app/data/data-addons/src/main/kotlin/com/hedvig/android/data/addons/data/DemoGetTravelAddonBannerInfoUseCase.kt, app/data/data-addons/src/main/kotlin/com/hedvig/android/data/addons/data/GetTravelAddonBannerInfoUseCaseProvider.kt, app/data/data-addons/src/main/kotlin/com/hedvig/android/data/addons/di/DataAddonsModule.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/di/InsurancesModule.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenter.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsuranceViewModel.kt, app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt
Add demo mode impl of GetTravelAddonBannerInfoUseCase for InsurancePresenter, but also avoid force logging out in general on unathenticated errors if we are in demo mode already anyway
=> Fix demo mode stop force logout

app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileGraph.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/data/GetCoInsuredForContractUseCase.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewho/TravelCertificateTravellersInput.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewho/TravelCertificateTravellersInputViewModel.kt
I think 1 sec is okay for here - this screen is not used that often, and in the case where info is missing we kind of need to update
=> GEN-3306 eagerly update fellow travellers

app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt
little change, Richard asked for it to be able to change copy to a longer one
=> finePrint instead of label

app/feature/feature-terminate-insurance/build.gradle.kts, app/feature/feature-terminate-insurance/src/main/graphql/FragmentTerminationFlowStepFragment.graphql, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminationSurveyOption.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt, app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyPresenterTest.kt
added Markdown just in case, if there will be any links in the info (probably not, but wouldn't hurt I guess)
=> add SurveyOptionSuggestionInfo

app/feature/feature-payments/src/main/graphql/QueryUpcomingPayment.graphql, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/data/MemberCharge.kt
new breakdown api to include addons too
=> GEN-3282 new chargeBreakdown for memberCharge

app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/history/PaymentHistoryDestination.kt, app/notification-permission/src/main/kotlin/com/hedvig/android/notification/permission/NotificationPermission.kt
there was a small todo for LocalActivity
=> LocalActivity comp local

app/data/data-claim-flow/src/main/graphql/FragmentClaimFlowStepFragment.graphql, app/data/data-claim-flow/src/main/graphql/MutationFlowClaimAudioRecordingNext.graphql, app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowDestination.kt, app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowRepository.kt, app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowStep.kt, app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowStepExt.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/freetext/FreeTextTriggerDisplay.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/di/OdysseyModule.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/navigation/ClaimFlowGraph.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/AudioRecordingDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/AudioRecordingViewModel.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/ui/AudioRecorder.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/summary/ClaimSummaryDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/summary/ClaimSummaryViewModel.kt, app/feature/feature-odyssey/src/test/kotlin/com/hedvig/android/feature/odyssey/data/TestClaimFlowRepository.kt
- added free text fallback it is allowed by BE on audio recording step
- added free text if there is any i the summary step
- redid summary a lil bit so the empty entries are not shown
=> GEN-3413 Feature/text fallback claim flow

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/a11y/DoubleTitleHeading.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/a11y/FlowHeading.kt, app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonDestination.kt, app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/selectinsurance/SelectInsuranceForAddonDestination.kt, app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/travelinsuranceplusexplanation/TravelInsurancePlusExplanationDestination.kt, app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepcustomize/SelectTierDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/addhouseinformation/AddHouseInformationDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/enternewaddress/EnterNewAddressDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/start/StartDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/honestypledge/HonestyPledgeDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/notificationpermission/NotificationPermissionDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/choose/ChooseInsuranceToTerminateDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/deletion/InsuranceDeletionDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationdate/TerminationDateDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationreview/TerminationConfirmationDestination.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/ui/TerminationScaffold.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/choose/ChooseContractForCertificate.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewhen/TravelCertificateDateInput.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewho/TravelCertificateTravellersInput.kt, app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt
From feedback from https://github.com/HedvigInsurance/android/pull/2479
=> A11y: Double title component in termination and travel flow

app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt, app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/app/src/main/kotlin/com/hedvig/android/app/notification/senders/ClaimClosedNotificationSender.kt, app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/navigation/ClaimDetailDestinationGraph.kt, app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/navigation/ClaimDetailDestinations.kt, app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt
Handling CLAIM_CLOSED notification type.
=> GEN-3388 Feature/claim closed flow

app/ui/ui-emergency/src/main/kotlin/com/hedvig/android/ui/emergency/FirstVetScreen.kt
https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1742460671346779
=> Update FirstVetScreen deep link

app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/di/PaymentsModule.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/overview/data/AddDiscountUseCase.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/AddDiscountBottomSheetContent.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/DiscountsDestination.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/DiscountsPresenter.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/DiscountsViewModel.kt, app/featureflags/feature-flags-public/src/main/kotlin/com/hedvig/android/featureflags/flags/Feature.kt, app/featureflags/feature-flags-public/src/main/kotlin/com/hedvig/android/featureflags/flags/UnleashFeatureFlagProvider.kt
With/without video
https://github.com/user-attachments/assets/a9b10fe6-2e53-4a7c-a4f5-6f9f76a28106
=> Feature flag/disable redeem campaign

app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/ui/ClaimDetailsDestination.kt, app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/ui/ClaimDetailsViewModel.kt
smol fix + proposal for the claimIsInUndeterminedState to be part of the state itself
=> Adjust the card spacings a bit

app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/di/HomeModule.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenter.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeViewModel.kt, app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenterTest.kt
This will mark it as seen so we don't always force-show the sheet again and again
=> Also call the cross sell seen on cross sell sheet showing

app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/ClaimFlowRepository.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/AddonBanner.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigCard.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HorizontalItems.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/NavigationBar.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Notification.kt, app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Tab.kt, app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/ui/ClaimDetailsDestination.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/documents/DocumentsTab.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/selectcontract/SelectContractDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/summary/ClaimSummaryDestination.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/aboutapp/AboutAppDestination.kt, app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverExplanationBottomSheet.kt, app/ui/claim-status/src/main/kotlin/com/hedvig/android/ui/claimstatus/ClaimStatusCard.kt, app/ui/cross-sells/src/main/kotlin/com/hedvig/android/crosssells/CrossSells.kt, micro-apps/design-showcase/build.gradle.kts, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcase.kt, micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/materialBottomSheet/MaterialExperiment.kt
tab role for tabs, merge description for horizontal items, material modal sheet in design showcase
=> a11y various things and showcase with material bs

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigAppState.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt, app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/navigation/TravelCertificateDestination.kt
We can start the flow of adding an add-on from in there so we must show it there too
=> Make travel cert history also show cross sell sheet

app/core/core-file-upload/src/main/kotlin/com/hedvig/android/core/fileupload/FileService.kt
Context:
https://github.com/HedvigInsurance/bot-service/pull/543
=> Adjust file size limit to new backend limits

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt, app/feature/feature-insurance-certificate/src/main/graphql/InsuranceEvidenceInitialData.graphql, app/feature/feature-insurance-certificate/src/main/kotlin/com/hedvig/android/feature/insurance/certificate/data/GetInsuranceEvidenceInitialDataUseCase.kt, app/feature/feature-profile/src/main/graphql/member/QueryInsuranceEvidenceAvailability.graphql, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/certificates/CertificatesDestination.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/certificates/CertificatesViewModel.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/data/CheckCertificatesAvailabilityUseCase.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/data/CheckInsuranceEvidenceAvailabilityUseCase.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/data/CheckTravelCertificateDestinationAvailabilityUseCase.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/di/ProfileModule.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/navigation/ProfileDestinations.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileDestination.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileGraph.kt, app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileViewModel.kt, app/feature/feature-profile/src/test/kotlin/com/hedvig/android/feature/profile/tab/ProfilePresenterTest.kt
- changes in the Profile tab ui (extra screen for all certificates)
- navigation to the new Insurance evidence flow
=> GEN-3538 Feature/insurance certificate profile changes

app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/history/TravelCertificateHistory.kt, app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt
small UI change as per: [ticket](https://www.notion.so/hedviginsurance/Travel-certificate-UX-updates-1d5c3f71cb0a803887fdd7d2f5df4dc8?pvs=4)
=> GEN-3586 Fix/travel certificate ui - tooltip

app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatLoadedScreen.kt, app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/TextWithClickableUrls.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/overview/data/GetForeverInformationUseCase.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/DiscountsDestination.kt, app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/di/MemberRemindersModule.kt
=> markdown in messages

app/feature/feature-payments/src/main/graphql/QueryDiscounts.graphql, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/data/GetDiscountsUseCase.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/overview/data/GetForeverInformationUseCase.kt, app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/discounts/DiscountsDestination.kt, app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/di/MemberRemindersModule.kt
[ticket](https://www.notion.so/hedviginsurance/Update-discounts-screen-UI-content-1eac3f71cb0a80fa8ab9c5967c3bff35?pvs=4)
=> GEN-3671 shorter displayName and exposure for contracts in Discounts

app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepcustomize/SelectCoverageViewModel.kt
=> fix min premium

app/data/data-chat/build.gradle.kts, app/database/database-core/build.gradle.kts, build-logic/convention/build.gradle.kts, build-logic/convention/src/main/kotlin/com/hedvig/android/HedvigGradlePluginExtension.kt, build.gradle.kts, gradle/libs.versions.toml
Common setup for adding ksp plugin, room plugin, adding the ksp room dependency and finally pointing the schema to a configurable path
=> Add room setup in hedvig gradle plugin

app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/AudioRecordingDestination.kt, app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/audiorecording/ui/AudioRecorder.kt
Now announces the following when focusing on the voice recording button: "Voice recording. Button. Double tap to start recording"
=> GEN-3820: Add label to the voice recording button

app/design-system/design-system-internals/src/main/kotlin/com/hedvig/android/design/system/internals/HedvigBottomSheet.kt
=> put windowInsetsPadding on bottomSheet

app/feature/feature-cross-sell-sheet/src/main/kotlin/com/hedvig/android/feature/cross/sell/sheet/CrossSellSheetViewModel.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCase.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCaseDemo.kt, app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt, app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenterTest.kt, app/ui/cross-sells/src/main/kotlin/com/hedvig/android/crosssells/CrossSells.kt
discount changes for phase 2: [figma](https://www.figma.com/design/cPsNUYT5LvPTKSmRhCFoXL/X-Sell-In-App?node-id=628-31597&m=dev)
=> GEN-3862 Feature/cross sell v2 discount UI

app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/success/ClaimSuccessDestination.kt
=> fix scroll in ClaimSuccessScreen

app/app/src/debug/res/values/strings.xml, app/app/src/main/AndroidManifest.xml, app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt, app/app/src/release/res/values/strings.xml, app/app/src/staging/res/values/strings.xml, gradle/libs.versions.toml, hedvig-lint/lint-baseline/lint-baseline-umbrella.xml
https://github.com/user-attachments/assets/93b19580-4b7b-480d-9e9a-6dc0e6d729e7
=> New deep link host

app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverDestination.kt
missing argument in string and fix jumping placeholder
=> fix placeholder jumping and missing argument

app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/di/TerminateInsuranceModule.kt, app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationreview/TerminationConfirmationViewModel.kt
see [slack](https://hedviginsurance.slack.com/archives/C03HT2JRDPG/p1756111442935909)
=> GEN-4082 fix crush in termination flow confirmation screen

app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt, app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/documents/DocumentsTab.kt
remove addon labels if their perils/docs are empty in insurance details
=> Fix addon labels

app/core/core-resources/src/main/res/values-sv-rSE/strings.xml, app/core/core-resources/src/main/res/values/strings.xml, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/MovingFlowGraph.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/di/movingFlowModule.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/storage/MovingFlowRepository.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleDestination.kt, app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleViewModel.kt
Hardcoded parts that assume this is in fact a travel insurance
May or may not require additions from backend to avoid such hardcoding
(Video recorded before commit 8062bbf5ccbcc577cc99ebafe78016f78acc3335)
https://github.com/user-attachments/assets/1d9a9501-9539-4f8d-8a58-4ebd3ab4d055
=> Allow removing addon from coverage choosing screen
