app/src/main/java/com/hedvig/app/feature/chat/ui/AudioRecorderView.kt

From experience there is not much we can do when the MediaPlayer fails :/
https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/4ba4a14827f505f3fbb1ab8bac54e30b?time=last-seven-days&sessionId=5D70F8A000D000010956DED0132BA0F3_DNE_0_v2

Handle playback failed

---

app/src/androidTest/java/com/hedvig/app/feature/referrals/ReferralsFeatureActivatedNotificationTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/ReferralsInformationActivityTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabCodeSnackbarTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabEmptyTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabMultipleReferralsTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabOneRefereeTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabOtherDiscountTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabShareTest.kt
app/src/main/graphql/com/hedvig/android/owldroid/graphql/loggedIn.graphql
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/ReferralsInformationActivity.kt
app/src/main/res/layout/activity_referrals_information.xml

- The incentive described in the translation is no longer hardcoded, but instead properly inserted through a placeholder
- The up-button in the toolbar now actually navigates up

Forever: Information screen fixes

---

app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ReferralTabScreen.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ShareTest.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/tab/ReferralsFragment.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/referrals/Data.kt

I've decided against using `Kakao`s support for `Intent`s, as it is too limiting.

Forever: URL Encode codes before placing them inside URLs

---

app/src/androidTest/java/com/hedvig/app/feature/referrals/tab/ShareTest.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/tab/ReferralsFragment.kt

This one behaves as expected with regards to spaces, encoding them as `%20` instead of `+`.
For shame, `URLEncoder`. For shame.

Forever: Replace `URLEncoder.encode` with `Uri.encode`

---

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt
app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt
app/src/main/res/layout/offer_header.xml
app/src/main/res/layout/offer_switch.xml
app/src/main/res/values-v27/styles.xml
app/src/main/res/values/button_themes.xml

- `ChangeDateBottomSheet` now dismisses properly
We were accidentally using `hide()`, which caused the bottom sheet to reappear when the activity resumed because the `Dialog` never actually disappeared
- The theme now looks correct on API levels 27 and 28
- Remove background not being continuously applied in all circumstances on `Toolbar`
This remove an issue where the `Toolbar`-background does not get to its correct color when users scroll really, really fast

Offer: Various bug fixes

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/home.graphql
app/src/androidTest/java/com/hedvig/app/feature/home/PendingTest.kt
app/src/androidTest/java/com/hedvig/app/util/KakaoExtensions.kt
app/src/debug/AndroidManifest.xml
app/src/debug/java/com/hedvig/app/DevelopmentActivity.kt
app/src/debug/java/com/hedvig/app/GenericDevelopmentAdapter.kt
app/src/debug/java/com/hedvig/app/feature/home/HomeMockActivity.kt
app/src/debug/java/com/hedvig/app/feature/home/MockHomeViewModel.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/HedvigApplication.kt
app/src/main/java/com/hedvig/app/feature/home/data/HomeRepository.kt
app/src/main/java/com/hedvig/app/feature/home/ui/HomeAdapter.kt
app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt
app/src/main/java/com/hedvig/app/feature/home/ui/HomeModel.kt
app/src/main/java/com/hedvig/app/feature/home/ui/HomeViewModel.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInTabs.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/TabPagerAdapter.kt
app/src/main/java/com/hedvig/app/util/GenericDiffUtilCallback.kt
app/src/main/java/com/hedvig/app/util/extensions/ViewBindingExtensions.kt
app/src/main/res/layout/home_big_text.xml
app/src/main/res/layout/home_body_text.xml
app/src/main/res/layout/home_fragment.xml
app/src/main/res/menu/logged_in_menu.xml
app/src/main/res/menu/logged_in_menu_key_gear.xml
app/src/main/res/menu/logged_in_menu_no_referrals.xml
testdata/src/main/java/com/hedvig/app/testdata/feature/home/Data.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/home/builders/HomeDataBuilder.kt

- Home tab is now shown by default instead of the old insurance tab
- If all contracts are pending, show a Big Text item (copy pending)
- Test and mock-infra for Home tab are in place
Also included:
- Ergonomic `viewBinding`-delegates
- A type-safe builder for `GenericDevelopmentAdapter`
Missing for now:
- API support for insurance switching. We're pretending that everyone is non-switchable for the time being.

App Navigation: Home Tab, Pending

---

app/src/androidTest/java/com/hedvig/app/feature/loggedin/PostSignTest.kt
app/src/androidTest/java/com/hedvig/app/feature/loggedin/WelcomeScreen.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/loggedin/Data.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/loggedin/builders/WelcomeDataBuilder.kt

- Opportunistic cleanup
- Add a test to ensure post sign-behaviour
- Remove some unused await-statements
- Remove some unused code
- Remove some purposeless code (?)
- The correct tab is now shown after activity recreation, and the toolbar inset is also correct after such an event

Fix: Weird activity recreate-related navigation behaviours

---

app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt

Prevent crashing if referrals info has not been loaded when trying to open the referrals info screen

---

app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectFragment.kt
app/src/main/java/com/hedvig/app/util/extensions/ViewBindingExtensions.kt

Should hopefully fix cases where the `WebViewClient`
causes crashes by attempting to access by trying to access
the `ViewModel`/`ViewBinding` after the `TrustlyConnectFragment`-view is destroyed.

HVG-392: Attempt to fix Trustly-related crashes

---

app/src/main/java/com/hedvig/app/feature/embark/passages/SelectActionAdapter.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/SelectActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/TextActionSetFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/Utils.kt
app/src/main/java/com/hedvig/app/util/extensions/view/ViewExtensions.kt

- Refactor animateResponse to suspend function and start a coroutine from fragments to avoid crashing.
- Add view extension to create callbackFlow for click listeners. Use when animating views in embark.

HVG-757 Fix select action crash

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/profile.graphql
app/src/androidTest/java/com/hedvig/app/feature/profile/AdyenConnectedTest.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/AdyenNotConnectedTest.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/CommonTestData.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/DirectDebitConnectedTest.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/DirectDebitNotConnectedTest.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/ProfileTabScreen.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/SuccessTest.kt
app/src/engineering/java/com/hedvig/app/feature/profile/ProfileMockActivity.kt
app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileFragment.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/profile/Data.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/profile/builders/ProfileDataBuilder.kt

- Add bankAccount and activePaymentMethods to profile query. Only show direct debit connected if bankAccount has status active.
- Add test for direct debit connected. Add clickable item in ProfileMockActivity.
- Add Adyen connected and not connected tests. Add clickable items in ProfileMockActivity. Extract MockMarketProvider to separate file.

HVG-738 Add states for adyen and bank account connections

---

app/src/androidTest/java/com/hedvig/app/feature/embark/numberaction/NumberActionTest.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/screens/NumberActionScreen.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/screens/TextActionScreen.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/textaction/TextActionTest.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt

- Prefill with previous answer for `TextAction`
- Prefill with previous answer for `NumberAction`
- Validate prefilled data
- Validate prefilled data for `TextAction`
- Opportunistic refactor: Modernize the tests a bit and improve naming

HVG-878: Persist input in Embark between passages

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/cashback.graphql
app/src/main/java/com/hedvig/app/feature/profile/ui/charity/CharityActivity.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/profile/builders/ProfileDataBuilder.kt

Reason: `paragraph` and `description` contained similar data,
but `description` is used by iOS and `paragraph`
is missing for some charities.

HVG-897: Charity: Switch from `paragraph` to `description`.

---

app/src/main/java/com/hedvig/app/feature/embark/passages/numberaction/NumberActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/selectaction/SelectActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/textactionset/TextActionSetFragment.kt
app/src/main/res/layout/fragment_embark_select_action.xml
app/src/main/res/layout/fragment_embark_text_action.xml
app/src/main/res/layout/number_action_fragment.xml
app/src/main/res/layout/previous_insurer_fragment.xml

Postpone enter transitions to allow smoother animations when navigating between embark screens. Add margins to response text view.

HVG-890: Improve embark transitions

---

app/src/androidTest/java/com/hedvig/app/feature/embark/EmbarkActivityTest.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsActivity.kt
app/src/main/java/com/hedvig/app/feature/onboarding/ui/ChoosePlanActivity.kt

Any idea how we can simulate a press on the overflow menu button in the progress toolbar? Couldn't figure out how to do that, which is need if we want to write an integration test for this.

HVG-904: Restart embark from more options

---

.github/workflows/pr.yml
apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql
app/build.gradle.kts
app/src/androidTest/java/com/hedvig/app/feature/embark/computedvalues/ComputedValuesTest.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/screens/EmbarkScreen.kt
app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkStoryExt.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt
app/src/main/java/com/hedvig/app/feature/embark/computedvalues/TemplateExpressionCalculator.kt
app/src/test/java/com/hedvig/app/ComputedValuesTest.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/EmbarkStoryDataBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt

Adds support for computed store values in embark. 
Whats not included: 
Support for computed store values in responses. Please point me in the right direction on where I should implement this, `preProcessResponse` perhaps? Thanks
I also had problems verifying a `KTextInputLayout` - the test framework could not find the view for some reason. Please take a look in `ComputedValuesTest` 🙏

HVG-941: computed store values

---

app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/HedvigApplication.kt
app/src/main/java/com/hedvig/app/feature/claims/data/ClaimsRepository.kt
app/src/main/java/com/hedvig/app/feature/home/data/HomeRepository.kt
app/src/main/java/com/hedvig/app/feature/insurance/data/InsuranceRepository.kt
app/src/main/java/com/hedvig/app/feature/keygear/data/KeyGearItemsRepository.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInRepository.kt
app/src/main/java/com/hedvig/app/feature/marketing/data/MarketingRepository.kt
app/src/main/java/com/hedvig/app/feature/marketpicker/LanguageRepository.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferRepository.kt
app/src/main/java/com/hedvig/app/feature/onboarding/ChoosePlanRepository.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/tab/ReferralsFragment.kt
app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt
app/src/main/java/com/hedvig/app/feature/webonboarding/WebOnboardingActivity.kt
app/src/main/java/com/hedvig/app/feature/welcome/WelcomeRepository.kt
app/src/main/java/com/hedvig/app/feature/whatsnew/WhatsNewRepository.kt
app/src/main/java/com/hedvig/app/util/LocaleManager.kt
app/src/main/java/com/hedvig/app/util/apollo/GraphQLUtils.kt

Use a LocaleManager in order to fetch a locale instead of creating the locale when initialising the dependency graph. When initialising the locale in the dependency graph, changes will not be reflected when setting a new locale. Use `defaultLocale()` in LocaleManager to get the most recent locale and avoid stale data.

APP-223: LocaleManager

---

app/src/engineering/java/com/hedvig/app/feature/marketpicker/MarketPickerMockActivity.kt
app/src/main/java/com/hedvig/app/SplashActivity.kt
app/src/main/java/com/hedvig/app/feature/settings/MarketManager.kt
app/src/main/java/com/hedvig/app/feature/settings/SettingsActivity.kt

Check market shared string preference to determine if market has been selected instead of using separate boolean preference

APP-243: Market selected preferences

---

app/src/main/java/com/hedvig/app/feature/embark/TextValidationUtil.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt

Show email autofill hints in embark. Use input hint instead of text field hint.

APP-264: Embark email autofill

---

app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/MaterialProgressToolbar.kt

Initiate embark data in viewmodel init to avoid reload when recreating activity. Wait for progressbar to be laid out by using post.

APP-353: Embark lifecycle

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/addressFragment.graphql
apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql
apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/selfChangeEligibility.graphql
apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/upcomingAgreement.graphql
app/src/engineering/java/com/hedvig/app/feature/changeaddress/ChangeAddressMockActivity.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressActivity.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressViewModel.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetSelfChangeEligibilityUseCase.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetUpcomingAgreementUseCase.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/Data.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/builders/SelfChangeEligibilityBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/builders/UpcomingAgreementBuilder.kt

Use updated schema to query an embark story id and use in order to start embark for moving flow. Note that the current id is not the final story to be used.

APP-372: Start embark from moving flow intro 

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/embarkStory.graphql
app/src/engineering/java/com/hedvig/app/feature/embark/EmbarkMockActivity.kt
app/src/engineering/java/com/hedvig/app/feature/embark/MockEmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/ExpressionBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/MessageBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/PassageBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/builders/RedirectBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/embark/data/Data.kt

As it turns out, these are functionally equivalent to `EmbarkMessage`.
However, we need to support both.
I also did some opportunistic refactoring. Nice!
- Kill SubExpression in favor of BasicExpression
- Make the MockEmbarkViewModel work again
- Support `EmbarkResponseExpression`

APP-374: Support Expression-based responses

---

app/src/main/java/com/hedvig/app/feature/zignsec/ui/ZignSecWebViewFragment.kt

I swear it used to redirect to an URL containing `failure`, not `fail`.
Whatever.

Show error on `fail` instead of `failure` in Simple Sign-authentication screen

---

.github/CODEOWNERS

Automatically add the Android team as reviewers on PRs.

Add CODEOWNERS to enable automatic review requests

---

app/src/androidTest/java/com/hedvig/app/feature/marketpicker/KnownGeoTest.kt
app/src/androidTest/java/com/hedvig/app/feature/marketpicker/UnknownGeoTest.kt
app/src/main/java/com/hedvig/app/feature/marketing/ui/MarketingActivity.kt
app/src/main/java/com/hedvig/app/feature/marketpicker/MarketPickerViewModel.kt

- Fix language never being sent to backend for default language selection
- Verify that it happens for unknown market as well

APP-442: Fix update language never being called for default language

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/upcomingAgreement.graphql
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetUpcomingAgreementUseCase.kt
testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/changeaddress/builders/UpcomingAgreementBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt

Could not get the include annotation to work when the mutation also took an input parameter, so had to remove it. Always querying `upcomingAgreementDetailsTable` should be fine anyway.

Pass locale to upcoming agreement query. Remove include annotation.

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql
app/src/main/java/com/hedvig/app/feature/insurance/data/InsuranceRepository.kt

Remove unused parameter from insurance query to avoid crash when fetching insurances

Remove unused query parameter from insurance query

---

app/src/main/java/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt

I looked around in the docs and there is a callback [onFinishInflate](https://developer.android.com/reference/android/view/View#onFinishInflate()), but could not get it to work properly. This works even though it is a bit hacky. Damn transitions...

Delay starting transition to avoid glitchy input layouts

---

app/build.gradle.kts
app/src/androidTest/java/com/hedvig/app/feature/offer/ChooseStartDateExistingSwitchableInsuranceTest.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/ChooseStartDateTest.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/ExistingNonSwitchableInsuranceTest.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/NoExistingInsuranceTest.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/OfferScreen.kt
app/src/androidTest/java/com/hedvig/app/util/KMaterialDatePicker.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/HedvigApplication.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/datepicker/DatePickerViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheet.kt
app/src/main/java/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheetViewModel.kt
app/src/main/java/com/hedvig/app/util/extensions/FragmentExtensions.kt
app/src/main/java/com/hedvig/app/util/extensions/LocalDateTimeExt.kt
app/src/main/res/layout/dialog_change_start_date.xml
app/src/main/res/values/styles.xml
buildSrc/src/main/kotlin/Libs.kt

Redesigned start date bottom sheet in offer screen. Added a viewmodel to handle events from view and supply an observable viewstate. The viewmodel is using StateFlow instead of LiveData, I think we should move to StateFlow since it has better coroutines support. See this article: https://medium.com/androiddevelopers/migrating-from-livedata-to-kotlins-flow-379292f419fb
We will need to be able to support multiple start dates as well, but that is another PR :)

APP-455: Redesign start date bottom sheet

---

app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/yourinfo/UpcomingChangeBottomSheet.kt

Looks like it's never truly been fully expandable. This is the same solution as is in place on the peril bottom sheet.

APP-644: Add some padding to the upcoming change bottom sheet

---

app/src/main/java/com/hedvig/app/feature/home/ui/HomeFragment.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceFragment.kt
app/src/main/java/com/hedvig/app/feature/keygear/ui/tab/KeyGearFragment.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/src/main/java/com/hedvig/app/feature/profile/ui/tab/ProfileFragment.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/tab/ReferralsFragment.kt

I noticed the transition between tabs were quite glitchy. This is because we need to postpone enter transitions, and wait until the recylerview in the enter fragment has been laid out. After trying different approaches for this and getting it to work quite well, I removed the transition just to compare the differences. Conclusion: the tabs feel more responsive and less glitchy when disabling the transitions altogether.
Please try it out and see what you think. I could spend some more time getting the original transitions to work if we really want to, but I think this is works well - especially when we have loading states for each tab.

Remove tabs transition

---

app/src/main/java/com/hedvig/app/feature/trustly/TrustlyConnectFragment.kt

Trying to fix this: https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/dcb21560ba705b789ee6f32fffa67fdf?time=last-thirty-days&sessionEventKey=61093E3B024A00012F17C310AF9B5648_1570634230566486193
I think it may have something to do with starting bankId and then returning to this fragment and trying to access bindings which no longer exist (because view no longer exists?). Tried using "dont keep activities" with no success. Removing the binding delegate was the only thing I could think of worth trying.
Do you have any ideas what might cause this?

APP-740: Do not use delegate when binding view

---

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferActivity.kt
app/src/main/res/menu/offer_menu.xml

Remove back pressed dispatcher to allow access to embark once offer is shown. Add item in overflow menu to allow discarding offer.

APP-744: Refactor discard offer

---

app/src/main/java/com/hedvig/app/feature/chat/service/ChatNotificationManager.kt

Notifications with replies must be mutable, or the app crashes.

Fix chat notification-`PendingIntent` being immutable

---

app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt
app/src/main/java/com/hedvig/app/feature/embark/computedvalues/TemplateExpressionCalculator.kt

Allow `TemplateExpressionCalculator` to see values from both `savedValues` and `stage`

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/insurance.graphql
apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/offer.graphql
app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/CoverageTest.kt
app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/PerilBottomSheetTest.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/MultipleQuotesTest.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageFragment.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageItems.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilAdapter.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferItemsBuilder.kt
app/src/main/java/com/hedvig/app/feature/offer/quotedetail/ItemBuilders.kt
app/src/main/java/com/hedvig/app/feature/perils/PerilsAdapter.kt
testdata/src/main/java/com/hedvig/app/testdata/dashboard/builders/InsuranceDataBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/InsuranceContractBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/insurance/builders/PerilBuilder.kt
testdata/src/main/java/com/hedvig/app/testdata/feature/offer/builders/OfferDataBuilder.kt

APP-838: Use `contractPerils` instead of the deprecated `perils`

---

app/src/engineering/java/com/hedvig/app/feature/changeaddress/MockChangeAddressViewModel.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressActivity.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressViewModel.kt
app/src/main/java/com/hedvig/app/util/coroutines/RunSuspendCatching.kt
app/src/test/java/com/hedvig/app/util/coroutines/RunSuspendCatchingTest.kt

Bonus: `suspend fun`-safe `runCatching`!
Draft for the time being, as this code is not testable due to a backend bug.

APP-850: Fix opening chat from Moving Flow sometimes not allowing free text-chat

---

app/src/main/java/com/hedvig/app/ScreenTracker.kt

We now track screen views on the event name `screen_view` with a property `name`.

APP-854: Use a single event name for tracking screen views

---

app/src/androidTest/java/com/hedvig/app/feature/crossselling/ui/CrossSellingResultScreenTest.kt
app/src/engineering/java/com/hedvig/app/feature/insurance/InsuranceMockActivity.kt
app/src/engineering/java/com/hedvig/app/feature/insurance/MockInsuranceViewModel.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/insurance/data/GetContractsUseCase.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceAdapter.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/InsuranceModel.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/NotificationSubheading.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/Subheading.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceFragment.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceViewModel.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/Items.kt
app/src/main/java/com/hedvig/app/feature/loggedin/service/GetCrossSellsUseCase.kt
app/src/main/java/com/hedvig/app/feature/loggedin/service/TabNotificationService.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInViewModel.kt
app/src/main/java/com/hedvig/app/service/badge/CrossSellNotificationBadgeService.kt
app/src/main/java/com/hedvig/app/service/badge/NotificationBadge.kt
app/src/main/java/com/hedvig/app/service/badge/NotificationBadgeService.kt
app/src/main/java/com/hedvig/app/ui/animator/ViewHolderReusingDefaultItemAnimator.kt
app/src/test/java/com/hedvig/app/feature/insurance/ui/tab/ItemsTest.kt
app/src/test/java/com/hedvig/app/feature/loggedin/service/TabNotificationServiceTest.kt

Checklist
This PR is a follow-up on #744 (and what #761 should have been), as it one was merged but then reverted.
Difference with #761 being that this was continued in git history after reverting the revert of the original #744 PR.

APP-863: Missing red dot on the add more coverage title. Branched from reverting the revert of the old PR #744

---

app/src/main/java/com/hedvig/app/feature/embark/passages/audiorecorder/AudioRecorderFragment.kt
app/src/main/java/com/hedvig/app/util/extensions/ActivityExtensions.kt

Tried to implement compose-style permission handling (more info [here](https://github.com/google/accompanist/blob/main/sample/src/main/java/com/google/accompanist/sample/permissions/RequestPermissionSample.kt)), but didnt quite get it to work 100%. Used our already existing implementation since we are using a fragment here anyway. We can look at the compose implementation together later if you want.

APP-998: Ask for permissions when pressing start record button

---

app/src/androidTest/java/com/hedvig/app/feature/embark/MoreOptionsTest.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlmutation/GraphQLErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/embark/api/graphqlquery/GraphQLErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/home/GraphQLErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/insurance/detail/ContractDetailErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/insurance/tab/ErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/insurance/terminatedcontracts/ErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/keygear/Error.kt
app/src/androidTest/java/com/hedvig/app/feature/offer/ErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/onboarding/MoreOptionsTest.kt
app/src/androidTest/java/com/hedvig/app/feature/profile/ErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/referrals/editcode/GenericErrorTest.kt
app/src/androidTest/java/com/hedvig/app/feature/sunsetting/SunsettingTest.kt
app/src/androidTest/java/com/hedvig/app/util/ApolloMockServer.kt
app/src/engineering/java/com/hedvig/app/DevelopmentActivity.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/sunsetting/ForceUpgradeActivity.kt
app/src/main/java/com/hedvig/app/util/apollo/SunsettingInterceptor.kt

- Preparative refactor: Allow errors to have more fields than simply 'message'
- Implement sunsetting-middleware

APP-909: Sunsetting Error Middleware

---

app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt
app/src/main/res/layout/contract_detail_activity.xml

Context:
https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1635932572116000
Optimally this should be shown in the case where specifically a previous
contract was over after the member went through the moving flow, but
there is no way to know that when we get a new clean contract, therefore
it was decided to show nothing instead.
The information about the old contract being active 30 days after the
moving is presented at the end of the moving flow.

APP-1018: Remove termination info which was showing faulty information

---

app/src/main/java/com/hedvig/app/feature/embark/EmbarkRepository.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/util/apollo/SafeQuery.kt

When graphQL returns an ok 200 result with partial data but an error in
the errors body, before it was considered a successful response,
breaking some embark flows. This change makes it so that such responses
are interpreted as a failed response, making the logic continue on the
unhappy path instead.
Should probably test as many other embark flows as possible before releasing with this change, I tried going through some of them to see that we were not relying on this behavior and it's looking okay so far, but I'm never sure with making embark changes. Let's see what the tests have to say too.

APP-1237: Alter safeQuery to handle error responses

---

app/src/main/java/com/hedvig/app/feature/embark/util/VariableExt.kt
app/src/main/java/com/hedvig/app/feature/embark/util/VariableExtractor.kt
app/src/test/java/com/hedvig/app/feature/embark/VariableExtractorTest.kt

Boolean values default as "false" regardless if they are present in the
store or not.
This functionality is needed since some embark flows depend on it.
Context:
- https://hedvig.atlassian.net/browse/APP-1259
- https://hedviginsurance.slack.com/archives/C016KUN61U3/p1643022424096600?thread_ts=1643021296.091300&cid=C016KUN61U3

APP-1259: Adapt embark to handle missing boolean values

---

app/src/main/java/com/hedvig/app/feature/claimdetail/ui/ClaimType.kt

Sometimes the backend may return an empty subtitle. Best we can do
client side is to make the UI look a bit smoother.
https://hedvig.atlassian.net/jira/software/c/projects/APP/boards/6?modal=detail&selectedIssue=APP-1296&quickFilter=51

APP-1296: Center the title text if subtitle is non existent

---

app/src/main/java/com/hedvig/app/feature/claimdetail/model/ClaimDetailResult.kt
app/src/main/java/com/hedvig/app/feature/claimdetail/ui/ClaimResultSection.kt

Before, since the monetaryAmount can't be shown yet due to backend
limitations, the pill was hidden altogether. This simply changes the
handling so that the pill does show only with no money amount shown.

APP-1311: Add the PAID pill when the claim is paid out

---

app/src/androidTest/java/com/hedvig/app/feature/embark/MissingActionTest.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/noaction/NoActionFragment.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/noaction/NoActionParameter.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/EmbarkActivity.kt
app/src/main/res/layout/fragment_embark_no_action.xml

We can now show error messages like this: 
Before, since the passage did not have an action, we showed the "update app" passage.

APP-1359: Show error messages in embark

---

app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteActivity.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteScreen.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteViewModel.kt

Dealing with the cursor itself is a tiny bit weird. In my solution, I am somewhat breaking the "Single Source of Truth" pattern, but making the address internally hold the input data while also pushing it to the ViewModel on change.
This was the approach I took since whenever I was sending the data to the VM and it was coming back down to the composable, there was no way to know if that action was done by the user entering letters or clicking on an address suggestion. Since there was no distinction between the two, I couldn't find a way to know when to move the cursor at the end of the word or not. We wanted this behavior as when we click an address we want the cursor to go to the end of the word to allow for further modification. If we do this on *every* change, this then means that if …

APP-1371: dk autocomplete cursor fix

---

app/src/androidTest/java/com/hedvig/app/util/ValueStoreRule.kt
app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/ValueStore.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt

The problem was as follows. The getList/get functions first look into
the stored values and if not existing then look into for example the
`stage` list. This means that if the key exists in both places, the
stored values are looked into first and the ones in staging are
disregarded.
This solves the bug where one may go through the entire flow, reach the
offer page. Then go back by pressing the back button to go and change
some input, and then continue the flow again. Then in the offer stage,
the old saved value is used instead of the latest one.
It was also considered to do a proper commit at this stage and a pop
after we're back into it, but was considered not a possible solution due
to how some passages are skipped when coming back like OfferSuccess

APP-1422: Make offer query fetch the quoteIds from the most recent selection

---

app/src/main/java/com/hedvig/app/feature/addressautocompletion/data/GetDanishAddressAutoCompletionUseCase.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/data/GetFinalDanishAddressSelectionUseCase.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/model/DanishAddressInput.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteActivity.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteScreen.kt
app/src/main/java/com/hedvig/app/feature/addressautocompletion/ui/AddressAutoCompleteViewModel.kt
app/src/main/java/com/hedvig/app/util/featureflags/FeatureManager.kt
app/src/main/java/com/hedvig/app/util/featureflags/ProductionFeatureFlagProvider.kt

Before on every address selection, we did the same network request for 
the address autocomplete twice. Once for populating the list and once 
for getting the final address. These then individually reported to the 
viewState through a `combine` of their flows, meaning that the results 
came in an unexpected order. Specifically, almost all the time, they 
list result would come either first or so close to the final address 
result that the list was updating and then instantly after that the 
screen would dismiss the screen. This made the UI look jumpy when 
clicking on the final address as explained here 
https://hedvig.atlassian.net/browse/APP-1154?focusedCommentId=11349
This change makes it so that this process is all streamlined from the 
same source, `currentInput`. …

APP-1455: Select dk address fluid selection

---

app/src/main/java/com/hedvig/app/feature/embark/ui/Tooltip.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/TooltipBottomSheet.kt

Apparently `getParcelableArrayList` relies on the type of the list being a `ArrayList<T>` explicitly as when it unpacks the bundle it literally *casts* it to one, so passing it a `List` doesn't work... most of the time.
Passing this list to the bundle does *not* work
```kotlin
val listThatDoesNotWork = listOf(foo)
```
This also does *not* work
```kotlin
val listThatDoesNotWork = buildList { add(foo) }
```
But doing it this way (among other ways) it *does* work.
```kotlin
val list = buildList { add(foo) }
val listThatDoesWork = listOf(list).flatten()
```
That's because as an optimization, doing `listOf` with one element specifically creates a java.util.Collections.SingletonList which *can not* be cast to an ArrayList.
And `buildList{}` is a `List` but under the hood it's a …

APP-1473: Fix bottom sheet not receiving any of the tooltips

---

app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/usecase/getquote/GetQuoteIdsUseCase.kt
app/src/main/java/com/hedvig/app/feature/offer/usecase/getquote/GetQuotesUseCase.kt

Return empty list of ids when not using quote cart apis, to avoid showing error when entering offer screen with ids from embark.

Offer error state

---

app/src/main/java/com/hedvig/app/feature/claimdetail/ui/ClaimDetailViewModel.kt
app/src/main/java/com/hedvig/app/feature/embark/ui/MoreOptionsAdapter.kt
app/src/main/java/com/hedvig/app/feature/loggedin/ui/LoggedInViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/model/quotebundle/ViewConfiguration.kt
app/src/main/java/com/hedvig/app/feature/profile/ui/aboutapp/AboutAppActivity.kt
app/src/main/java/com/hedvig/app/feature/referrals/ReferralsReceiverActivity.kt
app/src/main/java/com/hedvig/app/feature/referrals/ui/redeemcode/RedeemCodeBottomSheet.kt
app/src/main/java/com/hedvig/app/ui/compose/composables/CenteredContentWithTopBadge.kt
app/src/main/java/com/hedvig/app/util/apollo/DeviceIdInterceptor.kt
app/src/main/java/com/hedvig/app/util/coroutines/HistoryOfLastValue.kt
app/src/main/res/layout/promotion_code_dialog.xml

Since we use this step https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname it should work to simply add it on that screen. I didn't know we do that before, so I thought this wouldn't just work :D

Add version build number in the about app screen

---

app/src/main/java/com/hedvig/app/HedvigApplication.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/previousinsurer/PreviousInsurerFragment.kt

This screen has the same UI and works super similar with the `ExternalInsurerFragment`. Took inspiration from how that one handles this case here https://github.com/HedvigInsurance/android/blob/ee3d88a1ce79a4f39fdbd2320eec367b9b91461e/app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/ExternalInsurerFragment.kt#L162 .
Now it continues without adding anything to the value store, as I assume is the correct approach to this problem.
I do however wonder if this ever worked in the first place, I did not find any code in the history that would indicate so to try and revert to that instead. I might've missed smth though.

APP-1575: Make embark continue when selecting "other" as insurer

---

app/src/main/java/com/hedvig/app/feature/offer/model/quotebundle/ViewConfiguration.kt
app/src/main/java/com/hedvig/app/feature/offer/ui/composable/VariantButton.kt
app/src/main/java/com/hedvig/app/util/compose/HorizontalTextsWithMaximumSpaceTaken.kt
app/src/main/java/com/hedvig/app/util/compose/RadioButton.kt

Some changes to do the following:
- Allow the card to expand vertically when it needs more space instead of hiding the text
- Make the radio button go away from the material fixed size specs and allow it to be bigger so that it matches the design
- Add a layout which allows two texts that are side to side to not squish each other or to have to use fixed widths to avoid this interaction. Instead this layout lets each text take the minimum space they need as possible, before expanding to take on the rest of the space if it's available.
Please if you can find a better name than `HorizontalTextsWithMaximumSpaceTaken` suggest it 😅

Variant cards UI tweaks

---

app/src/main/java/com/hedvig/app/feature/embark/EmbarkViewModel.kt

We were using the wrong instance of `valueStore` for the function `getSelectedContractTypes`. Inside the `withCommittedVersion` scope we have access to `this` which is the "committed" version of the current `valueStore`.
Doesn't necessarily solve something in particular that I am aware of, but the way it was before was like that by accident as far as I can see.

Use committed valueStore inside `withCommittedVersion` block

---

app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/model/OfferModel.kt
app/src/main/java/com/hedvig/app/feature/offer/model/QuoteCartFragmentToOfferModelMapper.kt
app/src/test/java/com/hedvig/app/feature/offer/TestOfferModelBuilder.kt

Not sure how exactly it happened, but during some merge this change was overwritten.
This PR reintroduces the changes done in this PR https://github.com/HedvigInsurance/android/pull/956/files
Tested manually for all markets
This makes APP-1497 ready to be QAd again

Reintroduce ConnectPaymentAtSign after merge deleting it

---

app/src/engineering/java/com/hedvig/app/feature/impersonation/ImpersonationReceiverActivity.kt

This counts as a login, and as such features must be invalidated
in order to be correct when requested once more.

APP-1636: Fix impersonation not invalidating experiments

---

app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/insurance/data/GetContractsUseCase.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/tab/InsuranceViewModel.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/terminatedcontracts/TerminatedContractsActivity.kt
app/src/main/java/com/hedvig/app/feature/offer/usecase/SignQuotesUseCase.kt

Judging from the logs:
`2022-05-05T08:12:41.157000+00:00 com.hedvig.test.app: 23377:23474 D/a: Cache HIT for operation InsuranceQuery`
The cache is hit when it should actually try to fetch from the network.
Tested this change by using the original code:
- signing a new member
- approved the accident cross sell
- refreshing the page and seeing the cache being hit despite the giraffe query returning both contracts at this point
After this commit, did this:
- unsigned old member and started fresh
- signed a new member
- approved the accident cross sell
- now the page even before refreshing properly fetches the new data that the screens should be showing.

APP-1651: Make insurance query not show stale data after approving a moving flow

---

app/src/engineering/java/com/hedvig/app/MockContractDetailViewModel.kt
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/home/model/HomeItemsBuilder.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetAddressChangeStoryIdUseCase.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/ContractExt.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/detail/GetContractDetailsUseCase.kt
app/src/test/java/com/hedvig/app/feature/insurance/ui/detail/YourInfoItemsTest.kt

Related to [this](https://hedvig.atlassian.net/jira/software/c/projects/APP/boards/6?modal=detail&selectedIssue=APP-1613&quickFilter=51) ticket. We will use a new mutation for moving flow with quote cart. 
Moving flow can be disabled while that mutation is being implemented, in order to release faster.

APP-1184: Disable moving flow

---

app/src/main/java/com/hedvig/app/feature/embark/quotecart/CreateQuoteCartUseCase.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/ChangeAddressViewModel.kt
app/src/main/java/com/hedvig/app/feature/home/ui/changeaddress/GetAddressChangeStoryIdUseCase.kt

Specifically changes it so that `arrow.core.Either.Right` isn't used for the unhappy path. Uses `either` to short-circuit in the case of reaching the unhappy path and have the logic happen sequentially from top to down.

Simplify GetAddressChangeStoryIdUseCase with `eager {}`

---

apollo/src/main/graphql/com/hedvig/android/owldroid/graphql/quoteCartStartCheckout.graphql
app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/checkout/CheckoutViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/OfferViewModel.kt
app/src/main/java/com/hedvig/app/feature/offer/usecase/StartCheckoutUseCase.kt
app/src/main/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignDialog.kt
app/src/main/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignViewModel.kt
app/src/main/java/com/hedvig/app/util/apollo/SafeQuery.kt

Only call start checkout once and check if offer is in pending status. Throw cancellation exception in safe query to avoid showing error messages related to cancelled coroutines.

APP-1671: Check offer checkout status

---

app/src/main/java/com/hedvig/app/authenticate/LoginDialog.kt
app/src/main/res/layout/dialog_authenticate.xml

Add button in QR code dialog which opens generic auth flow. This will only work for Qasa members, but we should be able to activate it for all members without doing any changes in the clients.

APP-1661: Generic auth login

---

app/build.gradle.kts

Just a small fix to hide the false positive
Context:
https://youtrack.jetbrains.com/issue/KTIJ-19369/False-positive-can-t-be-called-in-this-context-by-implicit-recei#focus=Comments-27-5181027.0-0
https://hedviginsurance.slack.com/archives/GKMA95VV1/p1652965054166069

Suppress false positive IDE hint

---

apollo/build.gradle.kts
app/build.gradle.kts
build.gradle.kts
gradle/libs.versions.toml
renovate.json

Bonuses:
- Add annotations to remove false positive redlines
- Use Version Catalog to handle Kotlin Serialization-dependency

Ignore some dependencies in our renovate configuration

---

app/src/main/java/com/hedvig/app/feature/offer/ui/OfferQueryExt.kt

Check app config when checkout method is approve only in order to show correct text in offer

Fix offer approve button text

---

.github/workflows/pr.yml

Sometimes some PRs might not have an associated Jira ticket. Let the
build still show as successful when this happens

Allow finding the jira ticket to fail

---

apollo/build.gradle.kts

This is a simple QoL change to make the schema a bit more readable.
This is similar to how the schema was generated for apollo v2.x.
No steps need to be different to get this result, this simply intercepts the existing `./gradlew :apollo:downloadGiraffeApolloSchemaFromIntrospection` command and edits the resulting file by removing the double line breaks. Simply run this command again to get it to show like that on your IDE as well
| before | after |
| --- | --- |
| <img width="2168" alt="image" src="https://user-images.githubusercontent.com/44558292/178441573-b25f621f-19e4-4ba8-a09e-ac922fdcaa8a.png"> | <img width="2168" alt="image" src="https://user-images.githubusercontent.com/44558292/178441787-14c72067-108e-4080-8ee7-02f3a09432b7.png"> |

Remove double line breaks from schema.graphqls

---

.github/ci-gradle.properties
.github/workflows/integration-test.yml
.github/workflows/pr.yml
.github/workflows/staging.yml
.github/workflows/unused-resources.yml
build.gradle.kts

According to the issue https://github.com/gradle/gradle/issues/19750
setting org.gradle.jvmargs in gradle.properties potentially breaks the
runner from Github Actions, something that has made all of our CI runs
fail lately.
Inspired from this PR https://github.com/android/nowinandroid/pull/191
this hopes to change that.
More context in both aforementioned links.

Add custom gradle.properties for CI

---

app/build.gradle.kts
app/src/androidTest/java/com/hedvig/app/util/FeatureFlagRule.kt
app/src/test/java/com/hedvig/app/feature/embark/passages/ExternalInsurerViewModelTest.kt
app/src/test/java/com/hedvig/app/feature/home/model/HomeItemsBuilderTest.kt
app/src/test/java/com/hedvig/app/feature/profile/ui/tab/ProfileQueryDataToProfileUiStateMapperTest.kt
app/src/test/java/com/hedvig/app/feature/swedishbankid/sign/SwedishBankIdSignViewModelTest.kt
hanalytics-test/src/main/java/com/hedvig/android/hanalytics/test/FakeFeatureManager.kt

I want some feedback regarding the impl of FakeFeatureManager.
Using lambdas is I think a good improvement, so that if we want more control over what it will return depending on other local state we can simply do that inside the lambda. So I am confident about this decision.
However for the decision to error out if some feature is asked from the map but wasn't explicitly set I'd like your opinion.
If we let it default to `false` by doing `getOrDefault()` as we did before, that means that some tests may be using that return value in a way that is crucial for the test to pass. If we error out as I've done it, one *needs* to be explicit about what the return value would need to be for that particular test.
With that said, we do have tests where sometimes a value may be asked from the …

Testing: Use fake feature manager

---

lokalise-gradle-plugin/lokalise/build.gradle.kts

Works the same, minus some extra config which turns out isn't needed.

Cleanup build.gradle inside lokalise gradle plugin

---

app/src/main/java/com/hedvig/app/ApplicationModule.kt
app/src/main/java/com/hedvig/app/feature/crossselling/ui/detail/CrossSellDetailScreen.kt
app/src/main/java/com/hedvig/app/feature/embark/passages/externalinsurer/retrieveprice/RetrievePriceContent.kt
app/src/main/java/com/hedvig/app/feature/genericauth/EmailInputScreen.kt
app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputActivity.kt
app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputScreen.kt
app/src/main/java/com/hedvig/app/feature/genericauth/otpinput/OtpInputViewModel.kt
app/src/main/java/com/hedvig/app/feature/insurance/ui/CrossSell.kt
app/src/main/java/com/hedvig/app/feature/marketing/ui/BackgroundImage.kt
app/src/main/java/com/hedvig/app/ui/compose/composables/ErrorDialog.kt
app/src/main/java/com/hedvig/app/ui/compose/composables/FullScreenProgressOverlay.kt
app/src/main/java/com/hedvig/app/util/compose/RememberBlurHash.kt
app/src/test/java/com/hedvig/app/feature/genericauth/OtpInputViewModelTest.kt
core-design-system/src/main/java/com/hedvig/android/core/designsystem/theme/Theme.kt

Get started with migrating to the new insets APIs.
tl;dr is that if you want to simply add the paddings to safely draw your items away from the system bars and the IME you can use the modifier `fun Modifier.windowInsetsPadding(insets: WindowInsets): Modifier` which takes in `WindowInsets` and you can decide which one you want from this list [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation-layout/src/androidMain/kotlin/androidx/compose/foundation/layout/WindowInsets.android.kt;l=379-405) and then there's a list of convinience modifiers [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/foundation/foundation-layout/src/androidMain/kotlin/androidx/compose/foundation/layout/WindowInsetsPaddi …

APP-1879: Migrate insets otp screen

---

.github/workflows/upload-to-play-store.yml
ci-release-prebuild.sh

- Add upload to play store workflow
- Configure Play Store upload-step
- Fix release pre-build script
- Add gradle copy-step
- Split the calls up, maybe that fixes it?
- Add debugging
- Revert "Add debugging"
- smh
- Bump deploy action version

APP-1816: Migrate release builds from Bitrise to Github Actions

---

app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt
app/src/main/kotlin/com/hedvig/app/feature/checkout/CheckoutViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/OfferRepository.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/OfferViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/SelectedVariantStore.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/ui/changestartdate/ChangeDateBottomSheetViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/usecase/EditCampaignUseCase.kt
app/src/main/kotlin/com/hedvig/app/feature/offer/usecase/ObserveOfferStateUseCase.kt

https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/de950c400675366c7eaca57c86487b2c?time=1661682966000:1664274966000&sessionEventKey=632A11AD02A2000179993FC3B51FDF76_1723988857574285009
main diff is changing `private fun OfferModel.getBundleVariant(` return type to a nullable one, and handle it from there.

Fix relying on `.first()` on list which can very well be empty

---

app/build.gradle.kts
build-logic/convention/src/main/kotlin/com/hedvig/android/KotlinAndroid.kt

Figured a way to remove build types from android library modules. They don't need to know about staging, pullrequest or whatever anyway.

Android libraries without staging build type

---

app/src/engineering/kotlin/com/hedvig/app/mocks/MockMarketManager.kt
app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt
app/src/main/kotlin/com/hedvig/app/authenticate/LogoutUseCase.kt
app/src/main/kotlin/com/hedvig/app/authenticate/UserViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/genericauth/otpinput/OtpInputViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/marketing/MarketingViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/marketing/data/UploadMarketAndLanguagePreferencesUseCase.kt
app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationViewModel.kt
app/src/test/kotlin/com/hedvig/app/feature/genericauth/OtpInputViewModelTest.kt
app/src/test/kotlin/com/hedvig/app/feature/marketing/ui/MarketingViewModelTest.kt
hedvig-market/src/main/kotlin/com/hedvig/android/market/MarketManager.kt

Call the mutation only after there was an auth success on BankID success, and on simple sign success. Basically looked at the options that start from here https://github.com/HedvigInsurance/android/blob/ce396d51a817a5d620b5762e627e9fccb9a4ef64/app/src/main/kotlin/com/hedvig/app/util/navigation/NavUtil.kt#L20-L32 , https://github.com/HedvigInsurance/android/blob/dabb98db9d2042e9b61da630a6ab4a4e97d85e44/app/src/main/kotlin/com/hedvig/app/feature/marketing/MarketingActivity.kt#L100-L111 and for the OTP case.
We're still setting these values in the marketing screen, and in the settings screen and the single source of truth about them is `LanguageService` where this use case is fetching the info from.
hasSelectedMarket was only being set in two places but seemingly not used anywhere, just …

CLX-120: fix updating language before logging in

---

.github/workflows/staging.yml

The `token` approach is now deprecated. More info on the migration here https://github.com/wzieba/Firebase-Distribution-Github-Action/wiki/FIREBASE_TOKEN-migration

Update token used by Firebase Distribution.

---

app/src/main/kotlin/com/hedvig/app/feature/settings/SettingsActivity.kt

So the way that we use this preferences screen is kind of odd, since we do not actually store a bunch of this information inside shared preferences, so these changes may look a bit odd.
In the migration from shared prefs to the official language APIs, we did not update this screen to let the preference row know where to now fetch this information. So instead what it did is that it looked at shared prefs, which we've cleared in the migration, and didn't find anything.
Then when selecting a new language, it'd set the shared prefs again, something that we don't want, since it'd then trigger the migration again on next launch in LanguageService::performOneTimeLanguageMigration The two changes I'm introducing here, are a quick fix without changing this screen too much, but letting …

Make settings screen not show "not set" initially

---

app/src/main/kotlin/com/hedvig/app/authenticate/LogoutUseCase.kt

Had a case where logging out and in again was showing some stale information, which I suspect may have been from having cached data inside the apollo cache. Regardless, it's a good thing to do when logging out anyway.

Also clear apollo cache when logging out

---

app/src/main/kotlin/com/hedvig/app/authenticate/BankIdLoginDialog.kt
app/src/main/kotlin/com/hedvig/app/authenticate/BankIdLoginViewModel.kt
app/src/test/kotlin/com/hedvig/app/authenticate/BankIdLoginViewModelTest.kt
auth/auth-test/src/main/kotlin/com/hedvig/android/auth/FakeAuthRepository.kt

Also made the case where the initial attempt to fetch the `BankIdProperties` also represent an Error case, with the generic `We couldn\'t reach Hedvig right now, are you sure you have an internet connection?` error message showing on the dialog, since that is most likely to happen when the network request fails, which would probably mean the internet connection is down, or our backend is dead, so it will like 100% of the time be a network error.

BankIdLoginViewModel tests

---

app/src/main/kotlin/com/hedvig/app/util/extensions/ActivityExtensions.kt

If getting the labeled intents fails, simply continue with the first email app found instead of giving all the options. Worst case scenario not their preferred email app is opened, and they need to open it themselves.
The crash itself specified here https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/06823149a4ff8a411f4508e0cbfae9f4?time=last-seven-days shows that it's a OnePlus specific issue, and I found nobody else referencing it on the internet.

Workaround OnePlus crash finding all email app intents

---

app/src/main/kotlin/com/hedvig/app/feature/embark/passages/numberactionset/NumberActionFragment.kt
app/src/main/kotlin/com/hedvig/app/feature/embark/passages/textaction/TextActionFragment.kt
app/src/main/kotlin/com/hedvig/app/util/extensions/ContextExtensions.kt

The way it was handled before, it seems like the reference to the view
is captured, but the coroutine runs later at which point it may be null
again. Or it is never found in the first place, but we cast to non-null
but it findViewById can in fact return null.
This guards against both cases by searching for the view only when the
coroutine actually runs, but also guards against null by simply not
showing the keyboard.
Better not to show the keyboard than to crash the app in such cases.
https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/48c40244c6e862963a93a09287bf5add?time=last-ninety-days

Do nothing if the View passed inside showKeyboard is null

---

app/src/main/kotlin/com/hedvig/app/HedvigApplication.kt
app/src/main/kotlin/com/hedvig/app/util/firebase/FirebaseBreadcrumbTimberTree.kt
app/src/main/kotlin/com/hedvig/app/util/firebase/FirebaseCrashlyticsLogExceptionTree.kt
auth/auth-android/src/main/kotlin/com/hedvig/android/auth/android/AuthenticatedObserver.kt
gradle/libs.versions.toml

The "Logs" tab in Firebase crashlytics is completely empty which sometimes can make it hard to figure out what exactly lead up to the crash.
This can serve as a tool to at least take the logs and put them there, leaving some sort of "breadcrumbs" which can help us figure out which path was taken until they reached the point of the crash.
It will log all timber logs we write down. Follow up PRs can make this more useful by adding more logs in key places.

Put breadcrumbs in firebase crashalytics

---

app/src/main/kotlin/com/hedvig/app/HedvigApplication.kt

This can allow us to get more data on crashes, errors etc even in the staging builds coming from firebase app tester.

Report to Firebase Crashlytics for staging builds

---

app/src/main/kotlin/com/hedvig/app/ui/compose/composables/ChatIcon.kt
build-logic/convention/src/main/kotlin/com/hedvig/android/AndroidCompose.kt
core-design-system/build.gradle.kts
core-resources/build.gradle.kts
core-ui/build.gradle.kts
datadog/build.gradle.kts
feature-odyssey/build.gradle.kts
gradle/libs.versions.toml

With the version bump, there were some workarounds we can now avoid.
Plus fixing the debugLint problem, temporarily for odyssey bringing in koin-test as a transitive dependency, and also temporarily for startup lint having a bug which I reported.

AGP related fixes

---

core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/card/HedvigCard.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/datepicker/HedvigDatePicker.kt

The card to conform to our DS levitation and color The DatePicker to the above, plus removing the unnecessary title part and the empty space for the buttons which we do not use when using this component inline, and not in a Dialog

Add a Hedvig adjusted card and date picker

---

app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/zignsec/SimpleSignAuthenticationViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/zignsec/ui/ZignSecWebViewFragment.kt
datadog/src/main/kotlin/com/hedvig/android/datadog/DatadogLoggingTree.kt

Add replicating datadog logs to logcat which allows us to emulate what logs we will see in datadog to know if they suffice or not.
Plus some fixes due to what  I could see from those.

More auth logs

---

app/src/main/AndroidManifest.xml

Will for now only be visible for phones who have developer options on *AND* they've explicitly opted-in to the preview of this feature in the developer settings. For future OS versions however this will be expected.
Turns out we're not fiddling with back handling almost at all, so migration for us is simply opting in to this feature and we get this functionality for free! https://developer.android.com/guide/navigation/predictive-back-gesture#update-custom
https://user-images.githubusercontent.com/44558292/221212255-18162305-0478-4028-ae31-1fb6d33da395.mov

Offpiste: Predictive back gesture

---

micro-apps/design-showcase/build.gradle.kts
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcaseActivity.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/MaterialComponens.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/TopAppBar.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/DatePicker.kt

Use the new DS buttons, using the updated Hedvig buttons.
Also make it show all components on a very wide screen to more easily compare m2 and m3 side by side
This is just some improvements to the design showcase app which helped with updating the design system components. Namely:
* LargeContainedButton
* LargeOutlinedButton
* LargeTextButton

Update design showcase activity to m3 changes

---

core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeContainedButton.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeOutlinedButton.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeTextButton.kt
micro-apps/design-showcase/build.gradle.kts
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcaseActivity.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/MaterialComponens.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/TopAppBar.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/DatePicker.kt

Use containedButtonContainer and onContainedButtonContainer for the contained button.
Use m3 under the hood for the buttons, while still providing the correct
composition locals so that if m2 components are used in the `content`,
the correct textStyle and contentColor will be used.
Also provide bodyLarge text for m3 button text style as that's what our DS expects on the size of the text inside buttons.

Adjust hedvig buttons to the new changes for M3

---

app/src/main/kotlin/com/hedvig/app/feature/marketing/MarketingActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/marketing/marketpicked/MarketPickedScreen.kt
app/src/main/kotlin/com/hedvig/app/feature/marketing/pickmarket/PickMarketScreen.kt
app/src/main/res/layout/header_item_layout.xml
app/src/main/res/layout/offer_header.xml
app/src/main/res/values/text_themes.xml
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeContainedButton.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeOutlinedButton.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeTextButton.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigMaterial3ColorScheme.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigMaterial3Theme.kt
core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/theme/Colors.kt
micro-apps/design-showcase/build.gradle.kts
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/DesignShowcaseActivity.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/MaterialComponens.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m2/components/TopAppBar.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/Buttons.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/ui/m3/components/DatePicker.kt

For the XML theme setup. The "Discount" text style was removed as it was only used in one spot and that one spot was adjusted accordingly.
Also remove some rogue direct calls on Hedvig styles. Instead use
material's ?textAppearanceFoo to properly fetch from the theme.
---
Change marketing screen to simply use Dark theme style
Instead of manually providing and overriding some color values, do this:
Since the background image right now is dark, it needs content on top
which acts more like what content would act on a dark background,
therefore how the dark theme handles this. Lean into that and "force"
dark theme style for this screen only, while allowing the bottom sheet
to follow the device's theme normally.
---
Provide custom theme for contained buttons
For contained buttons, we got the …

Offpiste: Material2 without theme adapter extras

---

app/src/androidTest/kotlin/com/hedvig/app/TestApplication.kt
app/src/debug/res/values/strings.xml
app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt
app/src/main/kotlin/com/hedvig/app/HedvigApplication.kt
app/src/main/kotlin/com/hedvig/app/feature/home/ui/changeaddress/GetAddressChangeStoryIdUseCase.kt
app/src/main/kotlin/com/hedvig/app/feature/marketing/data/GetInitialMarketPickerValuesUseCase.kt
app/src/main/kotlin/com/hedvig/app/util/apollo/GraphQLQueryHandler.kt
app/src/release/res/values/strings.xml
app/src/staging/res/values/strings.xml
core-common/src/main/kotlin/com/hedvig/android/core/common/di/Qualifiers.kt
feature-terminate-insurance/build.gradle.kts
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/di/TerminateInsuranceModule.kt
notification-badge-data/build.gradle.kts
notification-badge-data/src/main/kotlin/com/hedvig/android/notification/badge/data/di/NotificationBadgeModule.kt

Adds the qualifier to all `get<ApolloClient>()` calls, and creates the octopus client too to be used in the future.
The important bit here is the now we can't do `get<ApolloClient>()` anymore without a qualifier, we need to specify which one it has to be,  a̶n̶d̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶w̶r̶o̶n̶g̶ ̶c̶l̶i̶e̶n̶t̶ ̶i̶s̶ ̶t̶o̶t̶a̶l̶l̶y̶ ̶u̶p̶ ̶t̶o̶ ̶u̶s̶,̶ ̶t̶h̶e̶r̶e̶ ̶i̶s̶n̶'̶t̶ ̶a̶ ̶w̶a̶y̶ ̶t̶o̶ ̶f̶i̶x̶ ̶a̶s̶k̶i̶n̶g̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶w̶r̶o̶n̶g̶ ̶q̶u̶e̶r̶y̶ ̶u̶s̶i̶n̶g̶ ̶t̶h̶e̶ ̶w̶r̶o̶n̶g̶ ̶c̶l̶i̶e̶n̶t̶.̶ This is fixed in https://github.com/HedvigInsurance/android/pull/1452 with :app no longer depending on :apollo:octopus.
The only way to fix this is for a module to *only* depend on `:apollo:giraffe` or only to `:apollo:octopus` which will mean that they *can't* even see the other …

CLX-427: Odyssey schema in android repo pt.2

---

app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt
app/src/main/kotlin/com/hedvig/app/feature/di/KoinInitializer.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/AndroidDatadogProvider.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/di/OdysseyModule.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/di/SubmitClaimModule.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/InputViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/DateOfOccurence.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/InputRoot.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/input/ui/Location.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/repository/ClaimsFlowRepository.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/repository/MockClaimsFlowRepository.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/repository/PhoneNumberRepository.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/resolution/ResolutionViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/resolution/ui/ResolutionRoot.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/CommonClaims.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/GetClaimEntryPointsUseCase.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/GetLocalEntryPointsUseCase.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/GetNetworkClaimEntryPointsUseCase.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchViewState.kt

:app which knows about the prod/dev/debug can provide the
`single<String>(odysseyUrlQualifier) { get<Context>().getString(R.string.ODYSSEY_URL) }`
and then :odyssey can provide everything else.
For now added them all to odysseyModule as I don't have all the right context to know if I should split them up in some other way.
In my opinion, splitting the modules per layer, like viewModel and repository I think doesn't really add any value, since it splits the things that logically are connected to each other (a VM and the Repository it's using for example), so if you want to see what things are together that thing makes it harder.
Think of [viewModelModule](https://github.com/HedvigInsurance/android/blob/f6e2f02260d4c5ce3f0567d77c18cc24710b94dd/app/src/main/kotlin/com/hedvig/app/ApplicationMo …

Fix internal claim search module

---

app/src/main/kotlin/com/hedvig/app/feature/claims/ui/commonclaim/CommonClaimActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilAdapter.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilModel.kt
app/src/main/kotlin/com/hedvig/app/feature/perils/PerilBottomSheet.kt
app/src/main/res/layout/common_claim_first_message.xml
app/src/main/res/layout/peril_icon.xml
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/resolution/ui/PayoutSummary.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchActivity.kt

Common claim bottom sheet redesign - remove the icon from detail activity + bottom sheets according to figma

---

.idea/codeInsightSettings.xml
app/build.gradle.kts
app/src/main/kotlin/com/hedvig/app/feature/claims/ui/commonclaim/CommonClaimActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/claims/ui/commonclaim/EmergencyActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageFragment.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/CoverageViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/GetContractCoverageUseCase.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilAdapter.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/coverage/PerilModel.kt
app/src/main/kotlin/com/hedvig/app/feature/perils/PerilBottomSheet.kt
app/src/main/res/layout/common_claim_first_message.xml
app/src/main/res/layout/peril_icon.xml
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/resolution/ui/PayoutSummary.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/SearchActivity.kt
gradle/libs.versions.toml

Add error screen to the coverage information
Handle insets properly for all orientations + in the error screen Rename "MoreInfo" to "InsurableLimit" to match expectations from other parts of the app.
Do not pass unstable List<> and prefer ImmutableList instead for composables.
Remove firebase's internal ImmutableList from autocompletion to not pollute the namespace.

Little touches to the coverage screen + add error screen.

---

feature-terminate-insurance/build.gradle.kts
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/TerminateInsuranceActivity.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/navigation/TerminateInsuranceGraph.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationfailure/TerminationFailureDestination.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationsuccess/TerminationSuccessDestination.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/unknown/UnknownScreenDestination.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/ui/TerminateInsuranceNavHost.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/ui/TerminationInfo.kt

To do this, allow TerminationInfoScreen to be more flexible Add a slot for the bottom attached buttons, to allow for the termination
screen to give two buttons instead.
And add the open chat button for both the unknown screen case, and the termination failure screen.
The copy is in general weak, but it was decided on just to get something there, might need to explore better options.
| unknown screen | termination failure |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/44558292/224700779-1b2028ad-ca95-4cf9-9d47-1931184591e5.png) | ![image](https://user-images.githubusercontent.com/44558292/224700853-7d79bda2-1632-4cf3-8adc-0f4c350271b6.png) |

Add "open chat" button in the failed termination screens

---

apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/claimflow/FragmentClaimFlowStepFragment.graphql
app/src/main/kotlin/com/hedvig/app/ApplicationModule.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ClaimFlowActivity.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/ClaimFlowRepository.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/ClaimFlowStep.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/OdysseyService.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/di/OdysseyModule.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowGraph.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowNavHost.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingViewModel.kt
navigation/navigation-activity/src/main/kotlin/com/hedvig/android/navigation/activity/Navigator.kt

File uploading now works 🎉
And after it's done uploading, just fixed being able to navigate to the single item screen afterwards, by making its destination class properly serializable.
Use the correct flow ID to be passed in, previously was using the ID from the current step which was wrong.
Also add some rough UI for the case where they've permanently denied microphone access to the app. Otherwise we show the dialog, they press "OK" and nothing happens, which would be super odd for most of our members if I were to guess. I'd like us to have a discussion for these cases, and if we can gracefully let them continue the flow without submitting an audio recording at all. Since we have other data to base our decisions off of now. Or if not, if we can get some more thoughtful copy to explain …

Feature: claim flow file upload

---

core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/button/LargeTextButton.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/ClaimFlowRepository.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/dateofoccurrence/DateOfOccurrenceDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/dateofoccurrence/DateOfOccurrenceViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/dateofoccurrencepluslocation/DateOfOccurrencePlusLocationDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/location/LocationDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/phonenumber/PhoneNumberDestination.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationdate/TerminationDateDestination.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationdate/TerminationDateViewModel.kt

Show the loading indicator in all the screens which did not already have it.
Check so that one is not able to click on items while there is a loading indicator at the same time.

Fix some error and loading states in claim screens

---

app/src/main/kotlin/com/hedvig/app/feature/insurance/data/GetContractsUseCase.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/ContractExt.kt

* Fetch termination data from network
Would otherwise fetch stale data regarding the termination flow right
after coming back from the termination flow.
* Don't show termination flow when already terminated
Simply hide the button for already terminated contracts

Termination flow touches

---

app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/ContractDetailActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/GetContractDetailsUseCase.kt

Avoids showing stale data when just finishing the termination flow which
would also mean the button is shown again.
By using WhileSubscribed, it means that when coming back from the flow, the timeout has occurred, starting the flow again, and triggering the query again to refresh the data automatically, while still showing the old data initially while the new query is being executed.
In practice this basically just means that when you're done terminating your insurance, as you go back to the insurance detail screen, it automatically fetches the latest information, showing that your insurance is terminated, instead of having to go back in the insurance tab and pull to refresh for it to show.

Fix: do not get stale contract detail data

---

feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationsuccess/TerminationSuccessDestination.kt

Before, it felt a bit unintuitive to leave the success screen. You had to either go back, or press the back arrow on the top left, but there wasn't any "ok I am done now" action, and the survey might feel like a dead end, since clicking it doesn't also leave this screen, only opens a website, and going back may feel like they're going back into the flow, so I thought this makes sense.

Also add a "Done" button to more easily exit the screen

---

apollo/core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/GetContractDetailsUseCase.kt

This makes it so that the shared element transition does not look super ugly as the new screen does not have the ready to serve data, but can use what's in the cache already, while still making sure to not show stale data when coming back from the termination flow if the insurance was terminated
What the issue was basically is that as the card was animating to the next screen, it was white until the network request returned, which was ugly. And this was as a result of me recently changing the fetching so that it always hits the network, since we did not want stale data.
Well, apollo gives us the `fetchPolicy(FetchPolicy.CacheAndNetwork)` which does *exactly* what we really want here. Hit the cache to get the latest data instantly, and then also hit the network to get the real latest data. …

Make insurance details read cache first before network

---

feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowGraph.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/singleitempayout/SingleItemPayoutDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/success/ClaimSuccessDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/unknownerror/UnknownErrorDestination.kt

Exact copy and structure from the embark success screen.
Plus prepare for the SingleItemPayoutDestination too, as these two are separate.

Feature: claim success screen

---

app/src/main/kotlin/com/hedvig/app/feature/embark/passages/UpgradeAppFragment.kt
app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/ContractDetailViewModel.kt
app/src/main/kotlin/com/hedvig/app/feature/sunsetting/ForceUpgradeActivity.kt
core-common-android/src/main/kotlin/com/hedvig/android/core/common/android/PlayStoreUtil.kt
feature-odyssey/build.gradle.kts
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ClaimFlowActivity.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowGraph.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowNavHost.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/search/ui/CommonClaims.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/summary/ClaimSummaryDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/unknownerror/UnknownErrorDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/unknownscreen/UnknownScreenDestination.kt
feature-terminate-insurance/build.gradle.kts
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/TerminateInsuranceActivity.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/navigation/TerminateInsuranceGraph.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/navigation/TerminateInsuranceNavHost.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/unknown/UnknownScreenDestination.kt

Moves `tryOpenPlayStore()` to core-common-android to make it accessible in the feature module.
I didn't move the `makeToast()` function but just copied the code as I hope we won't be using this so much anyway in new features.

CLX-468: Termination unknown step and claim unknown step open play store

---

apollo/octopus/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/claimflow/FragmentClaimFlowStepFragment.graphql
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/data/ClaimFlowStep.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/singleitem/SingleItemDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/summary/ClaimSummaryDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/summary/ClaimSummaryViewModel.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ui/SingleSelectDialog.kt

Had an issue with some items not looking disabled while loading
| Before | After |
| --- | --- |
| <img width="244" alt="image" src="https://user-images.githubusercontent.com/44558292/230110954-46255d70-7c8e-4d0b-a073-513dbfe9b5e2.png"> | <img width="244" alt="image" src="https://user-images.githubusercontent.com/44558292/230112065-6920014d-ffbe-4942-9360-22f9502d7366.png"> |
Now allows the user to select multiple items in the damage section, instead of instantly dismissing the dialog as soon as the first selection is done
And replace the title in the summary step with the one coming from the backend as it now exists in the GQL schema
| Before | After |
| --- | --- |
| <img width="191" alt="image" src="https://user-images.githubusercontent.com/44558292/230128843-c72703b3-4d06-4eb9-8a60-4bf …

CLX-456: Claims flow small UI touches

---

app/build.gradle.kts
build-logic/convention/src/main/kotlin/LibraryConventionPlugin.kt
gradle.properties
gradle/libs.versions.toml
micro-apps/design-showcase/build.gradle.kts

buildconfig is now false by default.
Same for renderScript and aidl.
This allows us to use the new capabilities of Android Studio Flamingo which is the current latest stable and remove some workarounds we've had for a couple of little things.
Also, this requires for you to use JDK 17. There's this section which helps with that https://developer.android.com/build/releases/gradle-plugin#jdk-17-agp

Bump to AGP 8.0.0

---

app/src/main/kotlin/com/hedvig/app/MainActivity.kt

The combination of FLAG_ACTIVITY_BROUGHT_TO_FRONT and FLAG_ACTIVITY_RESET_TASK_IF_NEEDED is true when specifically, the app is opened by clicking the home screen icon, while the app was already running and was present in the "recents" view.
All this due to our multi-activity setup, so if we ever manage to use a single activity setup, or at least handle the login screen along with the loggedIn screen in one activity, we can remove this workaround.
We figured this out by testing this together with Anna here https://hedviginsurance.slack.com/archives/CPCUHMMJQ/p1681739007104209?thread_ts=1680765598.502819&cid=CPCUHMMJQ
After this is released we will be able to test this again with her, but for now I've tested the exact same scenario which failed for us and it now worked!
It is a workaround, …

Fix app resetting when opening it from home screen

---

core-common-android/src/main/kotlin/com/hedvig/android/core/common/android/JSONObject.kt
core-ui/src/main/kotlin/com/hedvig/android/core/ui/permission/PermissionDialog.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/navigation/ClaimFlowGraph.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/audiorecording/AudioRecordingDestination.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/step/notificationpermission/NotificationPermissionDestination.kt

Now uses the proper flow of asking for the permission on first action
click, then asking again if we are allowed to give them the rationale,
and allow them to go directly to settings if we are not allowed to show
them a rationale and we've been denied at least once.

Claim flow audio permission

---

app/proguard-rules.pro
app/src/main/kotlin/com/hedvig/app/feature/chat/service/ChatNotificationSender.kt
app/src/main/kotlin/com/hedvig/app/service/push/senders/CrossSellNotificationSender.kt
app/src/main/kotlin/com/hedvig/app/service/push/senders/GenericNotificationSender.kt
app/src/main/kotlin/com/hedvig/app/service/push/senders/PaymentNotificationSender.kt
app/src/main/kotlin/com/hedvig/app/service/push/senders/ReferralsNotificationSender.kt

Add proguard rules for Retrofit + suspend functions
Context:
https://github.com/square/retrofit/issues/3751#issuecomment-1192043644
Add proguard rules for arrow retrofit adapter
Context:
https://github.com/arrow-kt/arrow-integrations/issues/121

Fix minified build crash

---

app/src/main/kotlin/com/hedvig/app/feature/chat/FileUploadOutcome.kt
app/src/main/kotlin/com/hedvig/app/feature/chat/data/ChatRepository.kt
app/src/main/kotlin/com/hedvig/app/feature/chat/service/ReplyWorker.kt
app/src/main/kotlin/com/hedvig/app/feature/chat/ui/ChatActivity.kt
app/src/main/kotlin/com/hedvig/app/feature/chat/viewmodel/ChatViewModel.kt
app/src/main/kotlin/com/hedvig/app/util/extensions/ActivityExtensions.kt

By the way, as I see from the code here, we did not clear the text itself even before my changes here (I didn't touch that part), if the network request failed. So that means that for the folks that were having issues, the network request seemed to work fine, and then the text was cleared. The problem was that even though the network request was OK, the message never arrived, which means it was for sure on the backend, and it also means that this change won't necessarily catch this issue again. Since from our perspective, sending the value worked fine.
Just some context on what I see here, but regardless, this is a good change.
* Add email opening function with hedvig support email prefilled
This does not open a bottom sheet to pick a mail, just opens it directly
* Remove unused …

Chat dialog on send error

---

README.md
app/src/debug/res/values/strings.xml
app/src/debug/res/xml/file_paths.xml
app/src/debug/res/xml/provider_paths.xml
app/src/main/AndroidManifest.xml
app/src/main/kotlin/com/hedvig/app/feature/chat/ui/ChatActivity.kt
app/src/release/res/values/strings.xml
app/src/staging/res/values/strings.xml

This was part of what we wanted to do when we used the contract for fetching a file from the phone without using the permission. This was a tiny bit more involved, but still the same concept applies. No longer have to ask for a permission to see their camera, since we are not accessing anything, just letting their own camera app do the work, and we only get to see the resulting picture if they want to send it to us, we are not allowing ourselves to see anything more than that.
Use the camera activity result contracts instead to fetch a picture.
Rewrite a bit of the logic of where it's saved as a consequence of this change.
All this is explained in a comment inside provider_paths.xml
This change also fixes compared to before that in case we start the picture taking, while we're there our …

Remove all unused permissions, most importantly, the camera one

---

.github/ci-gradle.properties
lokalise-gradle-plugin/lokalise/src/main/kotlin/com/hedvig/android/lokalise/task/DownloadStringsTask.kt

Enable configuration cache in CI too, and fix DownloadTasks to conform to the configuration-cache requirements.
This was the last piece of the puzzle to fully enabling https://docs.gradle.org/current/userguide/configuration_cache.html, which is basically a way for gradle to cache more things, making everything regarding gradle a bit faster.

Fix download task to work with configuration cache

---

core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/datepicker/HedvigDatePicker.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ui/DatePickerRowCard.kt
feature-odyssey/src/main/kotlin/com/hedvig/android/odyssey/ui/SingleSelectDialog.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/TerminateInsuranceActivity.kt
feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/terminationdate/TerminationDateViewModel.kt
gradle/libs.versions.toml

This now removes the workaround we were doing on DatePicker which didn't
fit out needs.
Also removes calling some internal code which is now properly public, to
set the date manually
And now we get a proper DatePickerDialog from the library so we don't have to make our own Dialog to wrap it.

Bump to latest material3 dependency

---

app/proguard-rules.pro

OkHttp 4.11.0 now has all these rules built-in
https://github.com/square/okhttp/compare/parent-4.10.0...parent-4.11.0#diff-2c8b9c303079dd83e7937b68b4074e19bbdcb65a72ed8fb43b4057ab6d8629acR10-R14 We now only need the ones for Retrofit which aren't merged into the main library yet.

Fix proguard rules to new okhttp release

---

.github/workflows/pr.yml

Inspired by this https://hedviginsurance.slack.com/archives/C02FSPVUUA1/p1685107022721769 since we don't have our tickets in Jira anymore

Remove jira ticket updating CI task

---

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/data/travel-certificate/src/main/kotlin/com/hedvig/android/data/travelcertificate/GetTravelCertificateSpecificationsUseCase.kt
app/feature/travel-certificate/src/main/AndroidManifest.xml
app/feature/travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/navigation/GenerateTravelCertificateGraph.kt

Also check for the feature flag properly for travel certificate. It was inverted before by accident.
Turns out we didn't need to do something special to get buildConfig inside the feature module, :app can just give it through the `generateTravelCertificateGraph` function.

Make file provider authority unique across all app variants

---

app/app/src/main/kotlin/com/hedvig/app/feature/loggedin/ui/ReviewDialogViewModel.kt

Before we would try to show the review dialog just once and absolutely never again.
This probably means that most of our members who've had this show at least once will never see it again, even if they never responded. This change should make it so that as the users use the app more, this dialog will trigger again eventually.
We should not be concerned regarding showing this too much, as the review APIs by themselves rate limit when this is shown. In reality they will see it less often than every month for example, as explained here https://developer.android.com/guide/playcore/in-app-review#quotas

Try to show review dialog more than just once

---

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigAppState.kt

With this we can create metrics for errors in claims flow, as well as number of successful claims
Example:  https://app.datadoghq.eu/rum/sessions?query=%40application.id%3A4d7b8355-396d-406e-b543-30a073050e8f%20env%3Adev%20%40type%3Aview&cols=&event=AgAAAYlAK9tYrpuf6QAAAAAAAAAYAAAAAEFZbEFLOXRZQUFBelRkeFFBWHpjNE9lbwAAACQAAAAAMDE4OTQwMmUtYzYwYi00NzJkLTljZTQtZDMwNTg3Y2E0ZmUz&viz=stream&from_ts=1688998380133&to_ts=1688999280133&live=true

Log compose destinations to datadog

---

app/app/src/main/kotlin/com/hedvig/app/feature/insurance/ui/detail/documents/InsuranceDocumentsTab.kt
app/core/design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/card/HedvigCard.kt
app/core/ui/build.gradle.kts
app/core/ui/src/main/kotlin/com/hedvig/android/core/ui/insurance/DocumentRow.kt

Not sure about the colors from the theme here. Should we change those later?

GEN-717: Add composables for documents

---

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigBottomBar.kt
app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigNavRail.kt
app/app/src/main/kotlin/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/appbar/m3/TopAppBar.kt

Make them both use the surface color, with a hairline width divider-like line where the split is between them and the content. Also fix a bit how the insets were consumed in the navigation rail scenario, where the display cutout inset was not consumed. https://issuetracker.google.com/issues/296990873
Also fix cutout insets for the top app bar icons

Fix bottom and navigation rail to new designs

---

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/animation/AnimatePlacement.kt
app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/layout/FixedSizePlaceable.kt
app/feature/feature-home/build.gradle.kts
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/claimstatus/ClaimStatusCards.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeLayout.kt

This kinda shows what happens when there is: only a text, a text with claim cards and some reminder cards, and a text without the claim cards and more reminder cards
https://github.com/HedvigInsurance/android/assets/44558292/584203dc-3bb6-49f3-8cc2-913e75df4726
More states here
| Enough content where it's scrollable | Centered content with cards | Just name | Name + reminder cards |
| --- | --- | --- | --- |
| ![image](https://github.com/HedvigInsurance/android/assets/44558292/765ab89b-e2e3-424c-b49b-9cfc7393d96e) | <img width="317" alt="image" src="https://github.com/HedvigInsurance/android/assets/44558292/fbf38eec-dd7e-4224-8355-9064fec51c45"> | <img width="317" alt="image" src="https://github.com/HedvigInsurance/android/assets/44558292/accdce92-f0f1-4b79-8183-c7f5eeff99cd"> | <img …

Home layout

---

app/core/core-common-public/src/main/kotlin/com/hedvig/android/core/common/preferences/PreferenceKey.kt
app/language/language-core/src/main/kotlin/com/hedvig/android/language/LanguageService.kt
app/language/language-core/src/main/kotlin/com/hedvig/android/language/di/LanguageModule.kt
app/market/market-core/src/main/kotlin/com/hedvig/android/market/Language.kt

We've had this migration since 2022-09-19. By now everyone must've run this code to migrate their specified language. And if not, what will happen for them is that the sharedprefs will store the old choice but it will not be used in any way, and en-SE will be automatically chosen for them.
Should simplify some code a bit as I am touching these classes

Remove language sharedpref migration

---

app/language/language-core/src/main/kotlin/com/hedvig/android/language/Language.kt

We do face scenarios where people have locales like en-US, especially from the play store testers, which this fix should accommodate for adequately.

Default to a language instead of crashing

---

app/app/src/main/kotlin/com/hedvig/app/feature/chat/data/ChatRepositoryNew.kt
app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/card/HedvigInfoCard.kt
app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/card/ExpandablePlusCard.kt
app/feature/feature-changeaddress/build.gradle.kts
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ChangeAddressUiState.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ChangeAddressViewModel.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/Address.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/ChangeAddressRepository.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/ExtraBuilding.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/MoveIntent.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/MoveQuote.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/QuoteInput.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressEnterNewAddressDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressEnterVillaInformationDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressOfferDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressResultDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/destination/ChangeAddressSelectHousingTypeDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/navigation/ChangeAddressDestination.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/navigation/ChangeAddressGraph.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/InputTextField.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/Switch.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/extrabuildings/ExtraBuildingBottomSheet.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/extrabuildings/ExtraBuildingContainer.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/extrabuildings/ExtraBuildingTypeContainer.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/offer/ContractTermsOverview.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/offer/QuoteCard.kt
app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/OptionChipsFlowRow.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/documents/DocumentsTab.kt
app/hanalytics/hanalytics-feature-flags-public/src/main/kotlin/com/hedvig/android/hanalytics/featureflags/flags/HAnalyticsFeatureFlagProvider.kt

Mostly UI fixes
Fix all the navigation handling so that going back does not exit the entire moving flow
Use movingFlowClient as a feature flag for this feature.

Moving flow fixes before release

---

app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatPresenter.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryImpl.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatDestination.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt

Keep the ChatMessage model as-is, and for the UI needs introduce a new one named UiChatMessage, which contains the domain model plus some UI-only information regarding which one of the messages is the one that should be marked as delivered.
The requirements for this is that when the member sends a message, when it is successfully sent to the backend, it should be marked as delivered. This can only be shown in the last delivered message, as all the ones above it are then expected to be also delivered. If there are any failed messages in the process, they do not interfere with this marking. If there are any messages coming from Hope, those are never expected to be marked as delivered, since they are incoming messages.

Add the "delivered" mark at the end of the last member sent message

---

app/hanalytics/hanalytics-android/build.gradle.kts
app/hanalytics/hanalytics-core/build.gradle.kts
app/hanalytics/hanalytics-feature-flags-public/build.gradle.kts
app/hanalytics/hanalytics-feature-flags-test/build.gradle.kts

Since we no longer need access to HAnalytics in various screens in order to log some events, we can avoid using `api` which previously let other modules know about the HAnalytics type

Contain HAnalytics to some specific modules

---

build-logic/convention/src/main/kotlin/KotlinLibraryConventionPlugin.kt
build-logic/convention/src/main/kotlin/com/hedvig/android/KotlinAndroid.kt

I was playing with installing JDK 20 on my machine and I figured that it started failing the build since we did not have java toolchain setup properly in our gradle configuration.
Mainly `toolchain.languageVersion.set(JavaLanguageVersion.of(17))``
Build-logic inspired by
https://github.com/apollographql/apollokotlin/blob/e0e32d7a05095ec4ccfa98402ab97f44e773dc84/build-logic/src/main/kotlin/CompilerOptions.kt#L73
Putting this here to see that CI passes, if yes should be fine to merge

Allow building the app with newer JDK versions

---

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/compose/LogCompositions.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatDestination.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt

Initially, when there is nothing in the lazy list, the messages are
empty, and what shows in the lazy list is the loading indicator and a
spacer here.
https://github.com/HedvigInsurance/android/blob/c1d80d089e9cf7af184e94503fddcc09c70f67f5/app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt#L277-L308
Then after the messages show, what LazyList tries to do when new items
come into the list is to see the unique ID of each of the items that
were showing before, and still keep those items in view, because
otherwise it looks super odd to have new items come in and suddenly what
you were looking at just disappears.
Now what that means is that all the chat messages come first in the
list, but it tries to keep the loading indicator in the screen too, so …

Fix chat scrolling to top bug

---

app/apollo/apollo-octopus-public/build.gradle.kts

This fixes CI which always fails too since apollo crashes when it realizes the latest schema simply does not have the `Upload` scalar in it at all

Remove Upload scalar mapping since it's no longer in the schema

---

app/feature/feature-payments/build.gradle.kts
app/feature/feature-profile/build.gradle.kts
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/aboutapp/LicensesDestination.kt
gradle/libs.versions.toml

Just saw that we still have this in the dependency bump PR and I realized we do not need to anymore. That library is deprecated https://google.github.io/accompanist/web/ and they encourage people to just copy it and adjust as needed.

Remove accompanist web view dependency

---

app/apollo/apollo-octopus-public/build.gradle.kts
app/apollo/apollo-octopus-public/src/main/kotlin/com/hedvig/android/apollo/octopus/MarkdownAdapter.kt
app/core/core-markdown/build.gradle.kts
app/core/core-markdown/src/main/AndroidManifest.xml
app/core/core-markdown/src/main/kotlin/com/hedvig/android/core/markdown/MarkdownString.kt
app/feature/feature-chat/build.gradle.kts
app/feature/feature-chat/src/main/graphql/QueryChatMessages.graphql
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatPresenter.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/ChatRepositoryImpl.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatBanner.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatDestination.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt
app/tracking/tracking-core/src/main/kotlin/com/hedvig/android/core/tracking/ActionLogger.kt
app/tracking/tracking-core/src/main/kotlin/com/hedvig/android/core/tracking/LogAction.kt
app/tracking/tracking-datadog/src/main/kotlin/com/hedvig/android/tracking/datadog/DatadogActionLogger.kt
hedvig-lint/lint-baseline/lint-baseline-core-markdown.xml

Adds a module which will contain just a simple Markdown type, which is necessary for GQL to know what to map the `Markdown` scalar that now exists on the supergraph's scehma.
A small change in ChatLoadedScreen composable so that it takes in a slot for the chat input composable. This is because that composable sets up a state object which requires an activity to be present, which made it impossible to create in a @Preview

Chat banner from backend

---

app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatPresenter.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/navigation/ChatGraph.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatBanner.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatDestination.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ui/ChatLoadedScreen.kt

This can be used to determine how often people go to the chat but end up first checking out the help center instead, or if they have chatted and then also decided to check out the help center
If a message has been sent is determined by the Presenter, exposing that information in the UI state. If one exits the chat and comes back into it again, that state is cleared, but that is working as intended, we do not plan to make this flag be tracked across app-starts or something more intricate than what we have in place here

Augment link handling for chat banner to logAction the navigation to HC

---

app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/data/GetInsuranceContractsUseCase.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/data/GetInsuranceContractsUseCaseDemo.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenter.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailViewModel.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/terminatedcontracts/TerminatedContractsViewModel.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt

Make GetInsuranceContractsUseCase return a flow of results. Now by default hits the cache *and* the network afterwards, which means that when one goes back to that screen after they've terminated their insurance, the cached value will immediatelly show, but then the real value will also be fetched from the network.
This also allows us to properly use the values from unleash, through listening to the value changes, and not just getting the first value and stopping there.

Fix insurance details view not showing up to date data

---

app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/aboutapp/AboutAppDestination.kt

The diff is quite a lot, but the only change is removing an extra column inthere which was no longer needed since HedvigScaffold provides a ColumnScope, and then adding a weight(1f) between the top items and the "report technical issue" button. And finally changing from the small button to the big button.
All this was after Julia got some feedback from William that the button should be bottom attached + have the `HedvigSecondaryContainedButton` style. We had to fix on both platforms

Update report technical issue button to be bottom attached

---

app/app/src/main/kotlin/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt

Filed a bug report:
https://issuetracker.google.com/issues/326356902
Before:
After:

Fix system nav bar not being transparent

---

app/datadog/datadog-core/build.gradle.kts
app/datadog/datadog-core/src/main/kotlin/com/hedvig/android/datadog/core/di/DatadogModule.kt
app/datadog/datadog-core/src/main/kotlin/com/hedvig/android/datadog/core/memberid/DatadogMemberIdUpdater.kt

Make it work exactly like DatadogDemoModeTracking does which properly shows up on the logs.
This was an oversight on my end when we re-wrote this class a bit.
The `init` block was the one that was supposed to kick-start the process. And we did wire the class in our koin graph, so Koin knew how to construct it. The problem was that nobody was asking for it, so it never was constructed in the first place, so this code simply never was called, resulting in not attaching the member id at all for the past few releases

Make sure that AuthEventBroadcaster runs on startup

---

app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/fileupload/FileUploadViewModel.kt

Fixes a crash reported in crashlytics
If the same local file is chosen again, it's best if we simply do not add it to the list in the first place, since it's already there. The existing behavior tries to add it to the list, but since the list assumes that all items are unique the app crashes
Context:
https://console.firebase.google.com/u/0/project/hedvig-app/crashlytics/app/android:com.hedvig.app/issues/fdc7606afb67952bbd76416f7674461a?time=last-thirty-days&types=crash&versions=12.5.2%20(1708595525)&sessionEventKey=65DE3CBD00B700010D3FAFD41DC34EFF_1918818661704692052

Fix crash when choosing the same file again

---

app/core/core-ui/src/main/kotlin/com/hedvig/android/core/ui/appbar/m3/TopAppBar.kt

WindowInsets.systemBars does properly take into account to only use the horizontal and the top insets. The change to use
WindowInsets.systemBars here did not account for it, so this needs to be reverted back.
TopAppBarDefaults.windowInsets is using
WindowInsets.systemBars.only(WindowInsetsSides.Horizontal + WindowInsetsSides.Top) anyway, and we add the cutout to it as mentioned here https://issuetracker.google.com/issues/326526714

Fix top app bar using insets from the bottom

---

app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/summary/ClaimSummaryDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/ui/ClaimFlowScaffold.kt

Fix a custom layout which always ensures that the grid takes up at least
160.dp worth of height, while still taking up as much space as it can
when there is enough space available which the other elements in the
layout are not taking up by themselves.

Claim overview files audio grid fix

---

app/datadog/datadog-core/src/main/kotlin/com/hedvig/android/datadog/core/memberid/DatadogMemberIdUpdater.kt
app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/generatewho/TravelCertificateTravellersInput.kt

When we were in the `UrlFetched` state of this screen, there was no UI emitted. This actually ends up making the content of the NavHost go down to showing no UI, so since the entire space is not needed, it only takes up 0 pixel and clips the rest of the content. This is done with a center alignment by default in the NavHost. This results in the when navigating away from this screen, the next screen as it animates into view, it also animates the content size accidentally, expanding from the center towards the edges, making it look like it's clipped. This wraps the entire screen in a simple box which fills max size to ensure that no matter which state the screen is in, it always takes up the entire screen size as it should, and this fixes the navigation clipping issue.
Also run ktlintFormat

Fix the screen clipping its size when navigating away from UrlFetched

---

app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/history/TravelCertificateHistory.kt

Context:
https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1709542445052319?thread_ts=1709542084.378979&cid=C03U9C6Q7TP

Make travel certificate history show the start date of the certificate

---

app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceGraph.kt
app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt

Without this change, a link to `{baseUrl}/contract` crashed the app since it was unable to take a null string and turn it into the `String` type that the destination was expecting.

Add fallback for contract deep links that do not have a contractId

---

app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigMaterial3Theme.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectCarOtherDamageDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectGlassDamageDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectTowingDestination.kt

Closing the claim flow when going to browser to open Eir link (other car damage claims) after 3 min delay (just decided). And small design changes, pointed out by William

close claim flow when opening the browser for Eir

---

app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/genericauth/GenericAuthDestination.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/genericauth/GenericAuthViewModel.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/genericauth/SsnInputScreen.kt

Otherwise since both DK and NO use the same login method one could try to login to DK when they've picked a NO locale (but not the other way around due to the max digit limit, by coincidence). This disallows sending it in the first place unless the ssn size is just right.

Stop allowing to submit the wrong number of ssn digits

---

app/app/src/main/kotlin/com/hedvig/app/HedvigApplication.kt
app/app/src/main/kotlin/com/hedvig/app/feature/loggedin/ui/LoggedInActivity.kt
app/language/language-core/src/main/kotlin/com/hedvig/android/language/LanguageService.kt

These sources talk a bit more about this.
https://developer.android.com/guide/topics/resources/app-languages#androidx-impl https://cs.android.com/androidx/platform/frameworks/support/+/336a1f14a9e8e6729e833b3022ad3ffa8a3f0433:appcompat/appcompat/src/main/java/androidx/appcompat/app/AppCompatDelegate.java;l=733-734
I suspect us doing it in the Application is the reason it simply didn't properly select the language for people who did not go ahead and do a language selection manually which has confused me for a very long time.
This along with getting rid of the other activities should meant that this happens just fine for all members soon.

Move the language migration from Application to LIActivity

---

app/app/proguard-rules.pro
app/core/core-file-upload/src/main/kotlin/com/hedvig/android/core/fileupload/FileUploadModule.kt
app/data/data-claim-flow/src/main/kotlin/com/hedvig/android/data/claimflow/di/ClaimFlowDataModule.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/di/ChatModule.kt
gradle/libs.versions.toml

Use the kotlinx serialization converter shipped with the library now
https://github.com/square/retrofit/tree/dfdad425e9d1c47dbce335c9808c75c72ef912cc/retrofit-converters/kotlinx-serialization
Also remove the proguard rules that are now shipped with the library
https://github.com/square/retrofit/issues/3751#issuecomment-1911000730

Bump retrofit

---

app/app/src/main/kotlin/com/hedvig/android/app/MainActivity.kt
app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigApp.kt
app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigAppUi.kt

Moves most of the things outside of the activity so that it can serve as a place to grab the things from DI and then delegate as much as possible to composables.
Things around the splash screen and the theme applying stay there, along with the integration with the recents deep link url sharing

Cleanup: remove clutter from main activity

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/icon/flag/FlagUk.kt

Fix clipping by using the clipPathData parameter on group https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/vector/ImageVector.Builder#addGroup(kotlin.String,kotlin.Float,kotlin.Float,kotlin.Float,kotlin.Float,kotlin.Float,kotlin.Float,kotlin.Float,kotlin.collections.List)
Remove some wrong foreground color in the UK flag

Fix crooked uk flag

---

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/navigation/HomeGraph.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/data/GetHomeUseCaseTest.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileDestination.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileGraph.kt
app/feature/feature-profile/src/test/kotlin/com/hedvig/android/feature/profile/tab/ProfileViewModelTest.kt
app/member-reminders/member-reminders-public/src/main/graphql/QueryGetPayinMethodStatus.graphql
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/GetConnectPaymentReminderUseCase.kt
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/GetMemberRemindersUseCase.kt
app/member-reminders/member-reminders-public/src/test/kotlin/com/hedvig/android/memberreminders/GetMemberRemindersUseCaseTest.kt
app/member-reminders/member-reminders-ui/src/main/kotlin/com/hedvig/android/memberreminders/ui/MemberReminderCards.kt

Fix wrong reminder (we showed 'connect payment' when there were missed payments causing member's  insurance to be cancelled soon)
[description in the ticket](https://www.notion.so/hedviginsurance/Connect-payment-banner-text-when-we-have-missed-payments-2b2316d35ab34dcea505aea7fb07bcbd)

GEN-1994: Fix/missing payment info

---

.github/workflows/pr.yml
.github/workflows/staging.yml
.github/workflows/unused-resources.yml
.github/workflows/upload-to-play-store.yml

https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation

ci updates

---

app/core/core-common-public/src/main/kotlin/com/hedvig/android/core/common/PersonalInfoStringBuilders.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/FetchCoInsuredPersonalInformationUseCase.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt

The bug was: incorrectly written SSN with impossible date (like 31st of April), which of course empty info when fetching personal info, then we try to convert it to the date, but it crashes bc of the date being impossible.

fix incorrect ssn crash

---

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/claims/FragmentClaimFragment.graphql
app/app/build.gradle.kts
app/feature/feature-claim-details/build.gradle.kts
app/feature/feature-claim-details/src/main/graphql/QueryClaims.graphql
app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/data/GetClaimDetailUiStateUseCase.kt
app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/di/FeatureClaimDetailsModule.kt

Turns out making it nullable on the client is not enough and the backend still returns a hard error when it tries to return it as null even though the client would be okay with it

Fix asking for conversation in some places where we should not. And only ask for it when the flag is on

---

app/apollo/apollo-core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt

After feedback by Martin here
https://github.com/apollographql/apollo-kotlin/issues/6129 Replace the implementation which relied on the isLast to a much more robust implementation which should cover what the previous implementation did plus more.

Stop relying on isLast

---

app/design-system/design-system-hedvig/build.gradle.kts
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Notification.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-insurances/build.gradle.kts
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenter.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/navigation/InsuranceGraph.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt
app/ui/cross-sells/src/main/kotlin/com/hedvig/android/crosssells/CrossSells.kt

https://www.notion.so/hedviginsurance/Insurances-info-box-for-the-moving-flow-90db1ff1bd5b4dd3b38c7f102c47cd04?p=b32af0bcf40d46c183a0a47ef377ecfe&pm=s
Turns out the notification DS component also has a one button version. I added it here!
Also, so cool to just use a DS component now, plug and play, so smooth on the call site 😊

GEN-2519 moving flow in insurances screen

---

app/app/src/main/kotlin/com/hedvig/android/app/apollo/LoggingInterceptor.kt
app/feature/feature-home/src/main/graphql/QueryNumberOfChatMessages.graphql
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCase.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/data/GetHomeDataUseCaseDemo.kt
app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/data/GetHomeUseCaseTest.kt
app/feature/feature-home/src/test/kotlin/com/hedvig/android/feature/home/home/ui/HomePresenterTest.kt

Log EVERYTHING around GQL requests, and make home query keep the ApolloOperationResponse signature so when it's logged it should hopefully contain the information of what went wrong.

Home screen shenanigans

---

app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt
app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigApp.kt
app/compose/compose-ui/src/main/kotlin/com/hedvig/android/compose/ui/UseSimplerShapesForOldAndroidVersions.kt
app/core/core-build-constants/src/main/kotlin/com/hedvig/android/core/buildconstants/HedvigBuildConstants.kt
app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/bottomsheet/HedvigBottomSheet.kt
app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/card/HedvigCard.kt
app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/component/tokens/HedvigShapeKeyTokens.kt
app/core/core-design-system/src/main/kotlin/com/hedvig/android/core/designsystem/material3/HedvigShapes.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Shapes.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Toggle.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/ShapeTokens.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddOrRemoveDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/YourInfoTab.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/marketing/MarketingDestination.kt
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/discounts/DiscountsDestination.kt
app/member-reminders/member-reminders-public/src/test/kotlin/com/hedvig/android/memberreminders/EnableNotificationsReminderManagerTest.kt
gradle/libs.versions.toml

Done by a hacky composition local which is just provided by the :app module through 
`UseSimplerShapesForOldAndroidVersions provides (hedvigBuildConstants.buildApiVersion <= 27),`
Then in the token resolution path, where we still have access to composition locals we grab it and branch to the right path.
Don't love it but I hope they do just fix it anyway at some point so we can just remove this local completely.
This has some unrelated material3 changes as I bumped to latest compose BOM to make sure they didn't just fix it in the latest release anyway.

Fix Android <= 8.1 not rendering clipped content properly

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/RadioGroup.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/inbox/InboxDestination.kt
app/feature/feature-edit-coinsured/build.gradle.kts
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddOrRemoveDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoinsuredSuccessDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/InsuredRow.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/RemoveCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/test/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenterTest.kt

That bug affects not only the ssn, name also stays if you switch back from manual. I added some if-else at first, but then it seems that the most reliable thing to do would be just to clean the state ssn, birthday and name entirely. Tell me wdyt:)

GEN-2638 nullify coinsured info

---

app/apollo/apollo-core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt
app/member-reminders/member-reminders-public/src/test/kotlin/com/hedvig/android/memberreminders/GetConnectPaymentReminderUseCaseTest.kt
app/member-reminders/member-reminders-public/src/test/kotlin/com/hedvig/android/memberreminders/GetUpcomingRenewalRemindersUseCaseTest.kt

Very important note here, that this is just done internally, but everything is still returned as Either, to keep the app running just as it used to. We can consider changing this at a later point. This PR is just to make it possible in the first place.
Use iorNel which instead of `Either<Error, Data>` returns `Ior<Nel<Error>, Data>`
Ior is basically an `Either` which can have *both* left and right at the same time, which is exactly what we want when we get partial responses.
This is for problems like when we've had the entire home screen error out on some members when one field failed, when we could've just had that one field be null and still showed all the rest of the data
See also articles like:
https://adambennett.dev/2024/09/using-feature-flags-in-graphql/ About how such partial …

Start potentially supporting partial gql responses

---

app/feature/feature-changeaddress/src/test/kotlin/com/hedvig/android/feature/changeaddress/destination/TestFakes.kt
app/feature/feature-choose-tier/src/main/graphql/AgreementFragment.graphql
app/feature/feature-choose-tier/src/main/graphql/CurrentContractQuery.graphql
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/data/GetCurrentContractDataUseCase.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepcustomize/SelectCoverageViewModel.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailPresenterTest.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/terminatedcontracts/TerminatedContractsPresenterTest.kt

We display current tier/deductible by default. Now I've changed a little bit what this"current" is: if we have the upcoming change (for example, we have already gone through Tier change flow, now we want to do it again, while the first change is not yet activated), the current will be the tier and deductible for the upcoming agreement (because it's what BE counts as the base to give us available tiers/ deductibles).
Converting it to draft now; discussing possible API change

check if there is not already a change of Tier in the upcoming agreement

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Typography.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/TypographyTokens.kt
app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt

Issue: https://www.notion.so/hedviginsurance/130c3f71cb0a80249219eb8a7589a637?v=130c3f71cb0a81d6bc17000c33cc9b68&p=130c3f71cb0a80e0bc0be32d4a4b202b&pm=s
After discussion here:
https://www.notion.so/hedviginsurance/It-looks-quite-compact-between-the-different-documents-hard-to-differentiate-them-Even-without-wie-130c3f71cb0a80ff877dfa94074ef806?d=131c3f71cb0a8073a6a2001c5f3676e1
And:
https://www.notion.so/hedviginsurance/Arrow-Icons-are-a-bit-off-not-aligned-with-text-on-Show-details-11cc3f71cb0a80ce8b1cdaedf3c4d158?d=11cc3f71cb0a8074a6c2001cf7f90322
regarding how the spacing works in this area, especially due to the close proximity of many clickable items together

Fix documents UI according to Figma specs

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigErrorSection.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigScaffold.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/inbox/InboxDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/addhouseinformation/AddHouseInformationDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/successfulmove/SuccessfulMoveDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt

https://www.notion.so/hedviginsurance/130c3f71cb0a80249219eb8a7589a637?v=130c3f71cb0a81d6bc17000c33cc9b68&p=130c3f71cb0a8028b114de7c4bdd05f1&pm=s
Also fix some bugs with how we were consuming or not consuming some window insets in this process.
The reason this is often something we miss is that the error text message is long enough that in normal-sized screens it requires the entire width of the screen already, and it looks correct. Given bigger screens (or landscape mode), us missing a `fillMaxWidth()` becomes obvious.
It's possible we've missed this in more places, but we can fix those as they surface.

Go full width/height in some places where we did not

---

app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt

Dialogs have some default internal padding so we don't need to do anything on the call-site besides just rendering the content we want
https://www.notion.so/hedviginsurance/Do-we-really-need-the-info-dialog-to-be-full-screen-130c3f71cb0a802ebab9cab1c78f1b55?pvs=4

Fix dialog taking more space than it needed

---

app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt

No frosted glass, but the best we can do with minimal effort is a simple bottom-attached surface
https://www.notion.so/hedviginsurance/Open-details-pushes-down-continue-button-price-to-scroll-Let-s-have-it-static-with-frosted-backgr-130c3f71cb0a806da632c649d36c7f2a?pvs=4

Make confirm changes section bottom attached

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigPreview.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/OverlaidIndicationConnection.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/OverlaidIndicationState.kt

overlaidIndicationConnection serves as the modifier to be added to the
places where the source of the indication comes from, which syncs all
interactions back to the interaction source which is used in the
OverlaidIndication.
The normal `clickable` modifier is then used in the rows since that one
correctly passes all interaction events, including hover events, long
clicks etc, which are otherwise harder to do manually with a pointerInput
I basically also used this as an opportunity to learn how to work with
custom modifiers. I followed the docs here if you're curious:
https://developer.android.com/develop/ui/compose/custom-modifiers#implement_a_custom_modifier_using_modifiernode

Introduce OverlaidIndication to handle the full row indication logic

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/ColorScheme.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/TableStyle.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/ColorDarkTokens.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/ColorLightTokens.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/ColorSchemeKeyTokens.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/TableTokens.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt

With this, add the shadow color which is transparent for dark mode.
Also fixes the text font accidentally changing to label in the bottom sheet too
It also uses LocalMinimumInteractiveComponentSize to make all rows tall enough for comfortable clicking
This surely is the last table PR

Make table use tokens from DS

---

.idea/codeInsightSettings.xml
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/EmptyState.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/NavigationBar.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Tab.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-insurances/build.gradle.kts
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/InsuranceDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/documents/DocumentsTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/EditInsuranceBottomSheetContent.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/UpcomingChangesBottomSheetContent.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/YourInfoTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/navigation/InsuranceGraph.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/terminatedcontracts/TerminatedContractsDestination.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/marketing/MarketingDestination.kt
app/feature/feature-profile/src/test/kotlin/com/hedvig/android/feature/profile/myinfo/MyInfoPresenterTest.kt
app/ui/cross-sells/build.gradle.kts
app/ui/cross-sells/src/main/kotlin/com/hedvig/android/crosssells/CrossSells.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/tabs/Tabs.kt

I changed one thing which might affect other screens which was the default padding around the entire bottom sheet.
With previous implementation, if we passed nothing in the `sheetPadding` value it would also move the sheet up above the bottom navigation bar, which is never what we want to do anyway.
This might have affected other callers as well, but I will try to go through them to make sure they look OK

GEN-2542 Ds/insurances

---

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/insurance/FragmentProductVariantFragment.graphql
app/data/data-product-variant/data-product-variant-android/src/main/kotlin/com/hedvig/android/data/productVariant/android/ProductVariantAndroid.kt
app/data/data-product-variant/data-product-variant-public/src/main/kotlin/com/hedvig/android/data/productvariant/ProductVariant.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/data/MoveQuote.kt
app/feature/feature-changeaddress/src/test/kotlin/com/hedvig/android/feature/changeaddress/destination/TestFakes.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt
app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt

https://hedviginsurance.slack.com/archives/C03U9C6Q7TP/p1731677844676929

Remove unused `type` from InsurableLimit

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/FetchCoInsuredPersonalInformationUseCase.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/EditCodeBottomSheet.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverDestination.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverExplanationBottomSheet.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverViewModel.kt
app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt

Same thing, but with HedvigBottomSheetState to control when the sheet shows or not.

New design/forever feature shared bottom with sheet state

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigBottomSheet.kt
app/feature/feature-changeaddress/src/main/kotlin/com/hedvig/android/feature/changeaddress/ui/extrabuildings/ExtraBuildingBottomSheet.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddOrRemoveDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/RemoveCoInsuredBottomSheetContent.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/EditInsuranceBottomSheetContent.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/yourinfo/UpcomingChangesBottomSheetContent.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/marketing/MarketingDestination.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/ui/TerminationScaffold.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/EditCodeBottomSheet.kt
app/shared/forever-ui/src/main/kotlin/com/hedvig/android/shared/foreverui/ui/ui/ForeverExplanationBottomSheet.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt

Make sure that modal bottom sheets don't give focus on appearance
Due to how he modal sheet is implemented
https://github.com/oleksandrbalan/modalsheet/blob/519938d25af1b9f41a409c5514f36a6cce0f4cb0/modalsheet/src/main/java/eu/wewox/modalsheet/FullscreenPopup.kt#L135
[ModalSheet] automatically requests focus on appearance. This means that if there is a focusable child available,
it gets focus immediately. This commonly is a TextField, which also brings the keyboard up. The keyboard ends up
coming up way too early, before the sheet manages to show, which results in a very awkward and janky animation
where the keyboard and the sheet are coming up in different timings, hiding each other while the insets are not
quick enough to catch up to make them go up in sync.
Making this box focusable …

Fix bottom sheet universal inset handling

---

app/apollo/apollo-core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt

This exposes the new 
`fun <D : Operation.Data> ApolloCall<D>.safeFlowAllowingPartialResponses(): Flow<Ior<ApolloOperationError, D>>`
function singature, for future potential callers who are interested in partial data too.
On the call site, this would practically look something like this
```
val homeQueryData: HomeQuery.Data = when (homeQueryDataResult) {
is Both<ApolloOperationError, HomeQuery.Data> -> {
logcat(WARN) {
"HomeQuery() responded with a partial result. ApolloOperationError:${homeQueryDataResult.leftValue}"
}
homeQueryDataResult.rightValue
}
is Left<ApolloOperationError> -> raise(homeQueryDataResult.value)
is Right<HomeQuery.Data> -> homeQueryDataResult.value
}
```
so we can move forward with partial data if it's there, and raise/log appropriately

Add an API to receive partial responses if the caller wants them

---

app/core/core-design-system/build.gradle.kts
app/core/core-resources/build.gradle.kts
app/data/data-contract/data-contract-android/build.gradle.kts
app/feature/feature-changeaddress/build.gradle.kts
app/feature/feature-help-center/build.gradle.kts
app/feature/feature-login/build.gradle.kts
build-logic/convention/src/main/kotlin/LibraryConventionPlugin.kt
build-logic/convention/src/main/kotlin/com/hedvig/android/HedvigGradlePluginExtension.kt

Keep it on only for the select few that have any resources in them We go from `gw build --dry-run --console=plain | grep SKIPPED | wc -l` returning 1765 tasks to now returning only 1490 tasks! Reference:
https://github.com/cashapp/redwood/pull/1326
In scans:
Before: https://scans.gradle.com/s/iga2y7d7nj322
1740 tasks, 904 transforms executed in 107 projects in 2m 50s
After: https://scans.gradle.com/s/mje5wlkusb3ay
1465 tasks, 904 transforms executed in 107 projects in 2m 4s
Don't focus too much on the time taken, since that one fluctuates for other reasons too, but removing ~300 tasks is just a great net benefit for changing nothing in functionality.
The android libraries that do have a `res` directory now need to opt-in to get their resources generated, but luckily that's just 4 modules …

Disable generating androidResources for 50+ android library modules

---

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigAppState.kt
app/app/src/main/kotlin/com/hedvig/android/app/ui/IsTopLevelGraphInHierarchy.kt
app/navigation/navigation-compose/src/main/kotlin/com/hedvig/android/navigation/compose/TypedAlternatives.kt

Clearing the backstack does not by itself clear the saved stack on the
top level graphs. Trying to navigate back to them with 
`restoreState = true` still does try to reset the backstack and as a
consequence the ViewModels as well.
This has the unfortunate side effect that for a moment the old UI state
is shown which could be the information for the wrong member.
It only happens for a frame or two, but we might as well fix this this
way for now

Clear the backstack of all top level graphs on logout

---

app/datadog/datadog-android/src/main/kotlin/com/hedvig/android/datadog/core/OkHttpDatadogUtil.kt

So since there was nothing to do in the code itself, I at least took the time to remove two constructors we were using which were deprecated in the latest versions. They migrated to use builders instead.

Migrate from the deprecated constructors

---

app/ui/pullrefresh/build.gradle.kts
app/ui/pullrefresh/src/main/kotlin/com/hedvig/android/pullrefresh/PullRefreshIndicator.kt

Looks to be just fine this way.
The Hedvig progress bar looks a tiny bit different, but it's consistent with the rest of the app at least.
It's such a small difference that I think it's fine this way.

GEN-2551 Remove m3 from pullrefresh

---

app/apollo/apollo-core/src/main/kotlin/com/hedvig/android/apollo/ApolloCallExt.kt
app/data/data-conversations/src/main/kotlin/com/hedvig/android/data/conversations/HasAnyActiveConversationUseCase.kt

This stops logging "isEligibleToShowTheChatIcon cant determine if the chat icon should be shown" for real this time when we are just not logged in yet

Retain the "Unathenticated" information even after merging all errors

---

app/feature/feature-terminate-insurance/src/main/graphql/FragmentTerminationFlowStepFragment.graphql
app/feature/feature-terminate-insurance/src/main/graphql/MutationFlowTerminationDateNext.graphql
app/feature/feature-terminate-insurance/src/main/graphql/MutationFlowTerminationDeletionNext.graphql
app/feature/feature-terminate-insurance/src/main/graphql/MutationFlowTerminationStart.graphql
app/feature/feature-terminate-insurance/src/main/graphql/MutationFlowTerminationSurveyNext.graphql
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceRepository.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt
app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceRepositoryImplTest.kt

The `$tiersEnabled` field is automagically propagated down in the fragments, even though we don't quite get autocompletion for it. But this works :D

Get extra information only when tiers flag is on

---

app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectGlassDamageDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectPestsDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/informdeflect/DeflectTowingDestination.kt
app/ui/ui-emergency/src/main/kotlin/com/hedvig/android/ui/emergency/EmergencyScreen.kt

Made them all do `backgroundPrimary` with the 0.95f alpha trick as surface color, and `fillPrimary` as the content color.
They are all wrapped in the forced dark theme wrapper, so it's always the right color in the background, which then allows for items using the normal `surfacePrimary` color to still be visible on top of them (simmer card does this), and the content remains readable and properly accessible this way.
It also makes sure that all such cards across the screens look the same, as opposed to the emergency screens which were using the surfacePrimary color which was a little bit different.

Align all always-dark-mode cards in deflect screens

---

app/datadog/datadog-android/src/main/kotlin/com/hedvig/android/datadog/core/DatadogInitializer.kt

Context:
https://github.com/DataDog/dd-sdk-android/issues/2426#issuecomment-2527646874
Tested by adding an interceptor which cancels all requests
```
val okHttpBuilder = get<OkHttpClient.Builder>().addInterceptor(get<AuthTokenRefreshingInterceptor>())
.addInterceptor {
it.call().cancel()
it.proceed(it.request())
}
```
and seeing what that error looks like for the event mapper.
Then we simply drop the error event as suggested in the linked discussion

Filter out cancellation exceptions for RUM errors

---

app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/data/MovingFlowQuotes.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/chosecoveragelevelanddeductible/ChoseCoverageLevelAndDeductibleDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt

| Before | After |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/a67eb386-894c-4cdc-9199-c780e874240a) | ![image](https://github.com/user-attachments/assets/3cf0dd62-fb12-4ecf-ad35-d76aa24dae36) |
I re-used most of what was there to make it easier to work with.
When backend exists for this, we can populate this list.
If it turns out that what we get from backend does not match the shape of a `Quote` that can change.
If it turns out that it needs additional information, they can be added to `AddonQuote` as needed.
I made sure to use the QuoteCard overload where I pass in a null `contractGroup` so that the pillow image does not show.
All the saving/restoring from Datastore still should work since we take the object and store it as a Json, and the new addon is also …

GEN-2988: T&A in moving flow summary screen

---

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigApp.kt
app/data/data-changetier/src/main/kotlin/com/hedvig/android/data/changetier/data/CreateChangeTierDeductibleIntentUseCase.kt
app/data/data-changetier/src/test/kotlin/data/CreateChangeTierDeductibleIntentUseCaseImplTest.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/summary/AddonSummaryDestination.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/data/GetCurrentContractDataUseCase.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/data/GetCustomizableInsurancesUseCase.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/di/ChooseTierModule.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepcustomize/SelectCoverageViewModel.kt
app/feature/feature-choose-tier/src/test/kotlin/data/GetCustomizableInsurancesUseCase.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt
app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetMemberActionsUseCase.kt
app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/data/GetQuickLinksUseCase.kt
app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/model/Question.kt
app/feature/feature-help-center/src/test/kotlin/GetMemberActionsUseCaseImpl.kt
app/feature/feature-help-center/src/test/kotlin/GetQuickLinksUseCaseTest.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/data/GetInsuranceContractsUseCase.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/data/GetInsuranceContractsUseCaseImplTest.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceRepository.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt
app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceRepositoryImplTest.kt
app/featureflags/feature-flags-public/src/main/kotlin/com/hedvig/android/featureflags/flags/Feature.kt
app/featureflags/feature-flags-public/src/main/kotlin/com/hedvig/android/featureflags/flags/UnleashFeatureFlagProvider.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/data/GetCoverageComparisonUseCase.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/di/ComparisonModule.kt

Replace all callers with the code path which would be taken if the result was always `true`.
Tests that are testing true/false have their title changed and the test which was testing for `false` is simply deleted.

Remove Feature.TIER entirely

---

app/app/src/main/kotlin/com/hedvig/android/app/ui/HedvigApp.kt
app/compose/compose-ui/src/main/kotlin/com/hedvig/android/compose/ui/SharedElements.kt
app/ui/ui-claim-flow/build.gradle.kts
app/ui/ui-claim-flow/src/main/kotlin/com/hedvig/android/ui/claimflow/ClaimFlowScaffold.kt
build-logic/convention/src/main/kotlin/com/hedvig/android/ConfigureKotlinCommonCompilerOptions.kt

This makes this top app bar stick around as the video showcases
https://github.com/user-attachments/assets/0ca796cc-5d68-40b0-86ce-f55e7b3e17ab
This just wraps the entire app with a `SharedTransitionLayout`, and sets up the local.
And then uses the AnimatedContent local from the navigation itself to sync up the bar.
It's a successor to https://github.com/HedvigInsurance/android/pull/2071 but much cleaner since we use the locals to make it all work instead of polluting the entire codebase with scopes and such.

Make claim-flow navigation bar a shared element

---

app/data/data-addons/build.gradle.kts
app/data/data-addons/src/main/kotlin/com/hedvig/android/data/addons/data/GetTravelAddonBannerInfoUseCase.kt
app/data/data-addons/src/test/kotlin/GetTravelAddonBannerInfoUseCaseImplTest.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenter.kt
app/feature/feature-insurances/src/test/kotlin/com/hedvig/android/feature/insurances/insurance/presentation/InsurancePresenterTest.kt
app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/history/CertificateHistoryViewModel.kt

Prevents old cache persisting the banner despite having already signed up for the addon
Adjust the callers to work on the reactive data instead of the one shot call
From: https://www.notion.so/hedviginsurance/Travel-Addon-17cc3f71cb0a8043ba45cc9d7d6006a5?p=17dc3f71cb0a8092863fd7383dea306f&pm=s
And: https://hedviginsurance.slack.com/archives/C03HT2JRDPG/p1736943683086899

Make travel addon banner fetch from network

---

app/compose/compose-ui/src/main/kotlin/com/hedvig/android/compose/ui/SharedElements.kt
app/navigation/navigation-compose/src/main/kotlin/com/hedvig/android/navigation/compose/LocalNavAnimatedVisibilityScope.kt

This makes previews easier to work with as they don't need to know about those locals nor set them up in any way.

Make shared element APIs a no-op when the locals are not set

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Peril.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseNavGraph.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/travelinsuranceplusexplanation/TravelInsurancePlusExplanationDestination.kt

The "learn more" button now takes you to a screen where we render all the peril information instead of showing a simpler text about it. The perils are picked up from the currently selected addon in the dropdown
| entrypoint | extra screen |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/05f6aa40-abf1-49b5-8ff9-ea59660242b1) | ![image](https://github.com/user-attachments/assets/68917430-feb9-475f-9cef-8c9cfd0bcc90) |

Add travel plus explanation screen

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Dropdown.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseNavGraph.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonViewModel.kt
app/feature/feature-addon-purchase/src/test/kotlin/ui/AddonSummaryPresenterTest.kt
app/feature/feature-addon-purchase/src/test/kotlin/ui/CustomizeTravelAddonPresenterTest.kt

We no longer want to skip it, even if there is only 1 option.
That option must be pre-selected, the dropdown must be disabled, and the
member now has the option to learn more about the option before moving
forward.
Context: https://hedviginsurance.slack.com/archives/C087K3U2EDU/p1737466488102509?thread_ts=1737387896.103079&cid=C087K3U2EDU

Always show addon choice screen to allow reviewing the perils before summary

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigCard.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/summary/AddonSummaryDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt
app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt

The diff in QuoteCard.kt is ugly but comes mostly from moving things around.
The important part is exposing `QuoteCardState` so that the summary screen is allowed to force the card to always show. It also uses `underDetailsContent`
to not show the "show details" button at all
Context:
https://hedviginsurance.slack.com/archives/C087K3U2EDU/p1737467303293259?thread_ts=1737387896.103079&cid=C087K3U2EDU

Always show details in addon purchase

---

app/apollo/apollo-octopus-public/src/main/graphql/com/hedvig/android/apollo/octopus/graphql/AddonVariantFragment.graphql
app/compose/compose-ui/src/main/kotlin/com/hedvig/android/compose/ui/SharedElements.kt
app/data/data-product-variant/data-product-variant-public/src/main/kotlin/com/hedvig/android/data/productvariant/AddonVariant.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigScaffold.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/customize/CustomizeTravelAddonDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/summary/AddonSummaryDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/travelinsuranceplusexplanation/TravelInsurancePlusExplanationDestination.kt
app/feature/feature-addon-purchase/src/test/kotlin/data/GetTravelAddonOfferUseCaseImplTest.kt
app/feature/feature-addon-purchase/src/test/kotlin/ui/AddonSummaryPresenterTest.kt
app/feature/feature-addon-purchase/src/test/kotlin/ui/CustomizeTravelAddonPresenterTest.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepsummary/SummaryDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/coverage/CoverageTab.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/documents/DocumentsTab.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/summary/SummaryDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/selectcontract/SelectContractDestination.kt
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/selectcontract/SelectContractViewModel.kt
app/ui/ui-tiers-and-addons/src/main/kotlin/com/hedvig/android/tiersandaddons/QuoteCard.kt

https://hedviginsurance.slack.com/archives/C07MM6F0DK2/p1737638802028819?thread_ts=1737038997.141969&cid=C07MM6F0DK2
This also has https://github.com/HedvigInsurance/android/pull/2388 merged since it contains a fix for the padding of the button in there

Fix: Excluded addons should stay shrinked and non-interactive

---

app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/pdfrenderer/PdfDecoder.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/ChatLoadedScreen.kt

I first started to implement a bigger solution where we actually rendered a pdf file inside the app on a separate screen as a lazy list of pages, but then I thought that we maybe need just a preview of the pdf file in the chat itself for better readability, and the actual pdf opening is probably better in the browser for the same reasons you mentioned when we talked about opening image in browser. Then a decoder for coil (first page of the pdf) would already suffice for this purpose. 
Pls let me know if you agree, if not - I'll continue with separate screen whole file rendering :)

add pdf decoder

---

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/feature/feature-edit-coinsured/src/main/graphql/QueryEligibleContractsForEditCoInsured.graphql
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/GetInsurancesForEditCoInsuredUseCase.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/di/EditCoInsuredModule.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/navigation/EditCoInsuredDestinations.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/navigation/EditCoInsuredGraph.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/triage/EditCoInsuredTriageDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/triage/EditCoInsuredTriageViewModel.kt
app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/HelpCenterGraph.kt
app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt

Deeplink to edit coInsured, with and without arguments.
Not sure what to do with navigation here, again. if I move triage into the graph and make it graph's startDestination, scaffold back Icon drom missinginfo/addOrRemove destination recreates the startDestination, so I have to press button twice; if I move outside the graph, set startDestination back to AddMissingInfo and get there by deeplink with no arguments, it crashes bc it tries to recreate graph with no argument in the start destination.

GEN-3228 Feature/coinsured deeplink

---

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/feature/feature-addon-purchase/build.gradle.kts
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/di/AddonPurchaseModule.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/navigation/AddonPurchaseNavGraph.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/triage/TravelAddonTriageDestination.kt
app/feature/feature-addon-purchase/src/main/kotlin/com/hedvig/android/feature/addon/purchase/ui/triage/TravelAddonTriageViewModel.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/model/Sender.kt
app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt

not sure about navigateUp vs popBackStack here

GEN-3226 Feature/travel addon deeplink

---

app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/navigation/TravelCertificateGraph.kt
app/navigation/navigation-core/src/main/kotlin/com/hedvig/android/navigation/core/HedvigDeepLinkContainer.kt

From:
https://hedviginsurance.slack.com/archives/C08C1DG4TFD/p1739365049499809?thread_ts=1739364938.167379&cid=C08C1DG4TFD
Looks like there is a deep link which we did not yet support.
Tested by running
```
adb shell am start -a android.intent.action.VIEW -d "https://dev.hedvigit.com/deeplinks/travelCertificate"
```

Feature travel certificates history deep link

---

app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt
app/app/src/main/kotlin/com/hedvig/android/app/logginginterceptor/HedvigLoggingInterceptor.kt
app/core/core-file-upload/src/main/kotlin/com/hedvig/android/core/fileupload/FileService.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/CbmChatRepository.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/model/Sender.kt

With these changes, when we comment out
`requireFileSizeWithinBackendLimits(uri)`
the logger just skips the content so we avoid the OOM error.
The process however still tries to upload the entire thing, and the backend eventually returns with a 413.
With `requireFileSizeWithinBackendLimits(uri)` in place, it simply short-circuits early and does not try to upload.
Consolidated the size checks by removing it from `uploadMediaToBotService` explicitly since the check happens anyway from the body we get from `fileService.createFormData`

Omit multipart from logs and add hardcoded 48 MB file size upload limit

---

app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/history/PaymentHistoryDestination.kt

Change ordering of payment entries in payment history. Show latest payment first instead of last.

Change ordering of payment entries

---

app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceStep.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminationSurveyOption.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyViewModel.kt
app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/data/TerminateInsuranceRepositoryImplTest.kt
app/feature/feature-terminate-insurance/src/test/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyPresenterTest.kt

We split the suggestions first in known/unknown to have non-null description and infoType. And then we split them into actionable ones with non-null button text, and the info one which does not require the button text at all.
This allows us to simplify the `continueAllowed` as:
```
val continueAllowed: Boolean = selectedOption != null &&
(selectedOption.suggestion == null || selectedOption.suggestion !is SurveyOptionSuggestion.Known.Action)
```
So that we know we only can move forward if we do not have a suggestion
which requires an action.
We also are able to now simply render nothing in the `Unknown` case
instead of having a card with no text inside it

Fix nullable button text modeling

---

app/app/src/debug/AndroidManifest.xml

Thought we might as well keep this in here, to uncomment when we want to test, and comment it back when we don't want it.
Otherwise we need to look it up each time we want to do this :D
And it's in the debug manifest, for extra safety if we ever accidentally commit it uncommented.
Otherwise I think this won't have any other side effects

Add code to easily test notifications locally

---

app/feature/feature-payments/src/main/graphql/QueryUpcomingPayment.graphql
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/data/PaymentConnection.kt
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/data/PaymentOverview.kt
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/overview/data/GetUpcomingPaymentUseCase.kt
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/payments/PaymentsDestination.kt
app/feature/feature-payments/src/main/kotlin/com/hedvig/android/feature/payments/ui/payments/PaymentsPresenter.kt

We were wrongly deriving that there were failing charges if there was no payment connection and there was an upcoming charge. We now instead find the termination date of the first contract which is terminated due to failed charges, and use that date as the marker of when the contract will be terminated to show to the UI

GEN-3402 Fix bug with showing upcoming termination due to failed charges wrongly

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Tab.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/tokens/TabTokens.kt
app/feature/feature-insurances/src/main/kotlin/com/hedvig/android/feature/insurances/insurancedetail/ContractDetailDestination.kt
app/feature/feature-login/src/main/kotlin/com/hedvig/android/feature/login/marketing/MarketingDestination.kt
app/shared/tier-comparison/src/main/kotlin/com/hedvig/android/shared/tier/comparison/ui/ComparisonDestination.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/tabs/Tabs.kt

The core change is that we can use textMeasurer to do this part
```
val (minItemWidth, fixedItemHeight) = remember(textMeasurer, tabTitles, density) {
var width = 0
var height = 0
for (title in tabTitles) {
val textLayoutResult = textMeasurer.measure(title, textStyle, maxLines = 1)
width = maxOf(width, textLayoutResult.size.width)
height = maxOf(height, textLayoutResult.size.height)
}
with(density) {
val extraHorizontalSpace = tabInternalPadding.calculateStartPadding(layoutDirection)
.plus(tabInternalPadding.calculateEndPadding(layoutDirection))
val extraVerticalSpace = tabInternalPadding.calculateTopPadding() + tabInternalPadding.calculateBottomPadding()
DpSize(width.toDp() + extraHorizontalSpace, height.toDp() + extraVerticalSpace)
}
}
```
Which lets us get the real size immediately …

Design: Tab row fit in one line

---

app/app/build.gradle.kts
app/feature/feature-odyssey/src/main/kotlin/com/hedvig/android/feature/odyssey/step/honestypledge/PledgeAcceptingSlider.kt

The background being draggable takes over and makes it all work as
expected anyway. This way there is no conflict of who takes over the
click resulting in the circle not being draggable itself

Hotfix 12.10.12: Remove the drag handler for the circle itself

---

app/feature/feature-claim-details/src/main/kotlin/com/hedvig/android/feature/claim/details/ui/ClaimDetailsDestination.kt

small change where we don't show the upper part of status card if we have no text for it

not show upper part of status card if claim is undetermined

---

.github/workflows/pr.yml
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt

Now it will wait until we've settled back to the home screen before it considers showing the bottom sheet.
There are no changes required as to when we mark the cross sells as seen, since that step is linked with the sheet actually being actually shown, which now simply happens a bit later.

Fix bottom sheet showing before properly navigating back

---

app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Dialog.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/Dropdown.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigErrorSection.kt
app/design-system/design-system-hedvig/src/main/kotlin/com/hedvig/android/design/system/hedvig/HedvigPreview.kt
app/feature/feature-choose-tier/src/main/kotlin/com/hedvig/android/feature/change/tier/ui/stepsummary/SummaryDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-help-center/src/main/kotlin/com/hedvig/android/feature/help/center/home/HelpCenterHomeDestination.kt
app/feature/feature-insurance-certificate/src/main/kotlin/com/hedvig/android/feature/insurance/certificate/ui/email/InsuranceEvidenceEmailInputDestination.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/MovingFlowTopAppBar.kt
app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/addhouseinformation/AddHouseInformationDestination.kt
app/feature/feature-terminate-insurance/src/main/kotlin/com/hedvig/android/feature/terminateinsurance/step/survey/TerminationSurveyDestination.kt
app/feature/feature-travel-certificate/src/main/kotlin/com/hedvig/android/feature/travelcertificate/ui/history/TravelCertificateHistory.kt
micro-apps/design-showcase/src/main/kotlin/com/hedvig/android/sample/design/showcase/dialog/ShowcaseDialog.kt

Fixed the scroll in the places where I noticed that, applying scroll actively in the dialogs (bc we have a few dialogs with lazyList - I think it's better to explicitly set it every time). AlertDialog and ErrorDialog will have vertical scroll by default.
Also added HedvigVerySmallScreenPreview to make it easier not to forget about these cases (it does not entirely make up for huge fonts scenarios, but it's close), and HedvigShortMultiScreenPreview (bc HedvigMultiScreenPreview is a bit excessive I think in most cases).

a11y: unscrollable screens

---

app/member-reminders/member-reminders-public/src/main/graphql/QueryNeedsCoInsuredInfoReminder.graphql
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/GetNeedsCoInsuredInfoRemindersUseCase.kt

We previously hadn't check for allowEditCoInsured when showing banners (neither did we check for the termination date not being null, so we prompted members to add coInsured where they cannot be added - in contracts terminating in the future). 
Now I changed `supportsCoInsured` from the [backend](https://github.com/HedvigInsurance/underwriter/pull/1526) so we only would need to check for it.

no coinsured reminder for expiring contracts

---

.idea/codeStyles/Project.xml
app/app/src/main/kotlin/com/hedvig/android/app/navigation/HedvigNavHost.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/navigation/HomeGraph.kt
app/feature/feature-home/src/main/kotlin/com/hedvig/android/feature/home/home/ui/HomeDestination.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/contactinfo/ContactInfoDestination.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/navigation/ProfileDestinations.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileDestination.kt
app/feature/feature-profile/src/main/kotlin/com/hedvig/android/feature/profile/tab/ProfileGraph.kt
app/member-reminders/member-reminders-public/src/main/graphql/QueryNeedsContactInfoUpdateReminder.graphql
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/GetContactInfoUpdateIsNeededUseCase.kt
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/GetMemberRemindersUseCase.kt
app/member-reminders/member-reminders-public/src/main/kotlin/com/hedvig/android/memberreminders/di/MemberRemindersModule.kt
app/member-reminders/member-reminders-public/src/test/kotlin/com/hedvig/android/memberreminders/GetMemberRemindersUseCaseTest.kt
app/member-reminders/member-reminders-ui/src/main/kotlin/com/hedvig/android/memberreminders/ui/MemberReminderCards.kt

[ticket](https://www.notion.so/hedviginsurance/Phone-number-action-for-nulled-phone-numbers-in-app-1edc3f71cb0a8070b1ffeb3dc5265532?pvs=4)
[figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/UX-Improvements--Small-Projects-?node-id=853-19288&m=dev)
Made [updates in member-service](https://github.com/HedvigInsurance/member-service/pull/1034), so we now have a new mutation `memberUpdateContactInfo` and a new property in MemberActions `isContactInfoUpdateNeeded` (true if phone number is missing or was added/reviewed more than one year). 
In this PR, if `MemberActions.isContactInfoUpdateNeeded` is true, we show a reminder on Home and Profile screens, that leads to Contact screen. The UI of Contact screen is also updated.
Will update the mutation used for contact screen to the new …

GEN-3713 Feature/contact UI update

---

app/data/data-chat/build.gradle.kts
app/data/data-chat/src/main/kotlin/com/hedvig/android/data/chat/database/ChatDao.kt
app/data/data-chat/src/main/kotlin/com/hedvig/android/data/chat/database/ChatMessageEntity.kt
app/data/data-chat/src/test/kotlin/com/hedvig/android/data/chat/database/ChatDaoTest.kt
app/database/database-core/src/main/kotlin/com/hedvig/android/database/AppDatabase.kt
app/database/schemas/com.hedvig.android.database.AppDatabase/3.json
app/feature/feature-chat/src/main/graphql/MutationConversationSendMessage.graphql
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/CbmChatRepository.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/data/CbmChatRepositoryDemo.kt
app/feature/feature-chat/src/main/kotlin/com/hedvig/android/feature/chat/model/CbmChatMessage.kt
gradle/libs.versions.toml

Mark ongoing messages to the backend as `isSending` in the DB.
Use the fact that the ID has to be unique to then override that message with either the error version of that message, or the real version of that message when it arrives back from the backend

Client generated message ID

---

app/feature/feature-movingflow/src/main/kotlin/com/hedvig/android/feature/movingflow/ui/enternewaddress/EnterNewAddressDestination.kt

This allows input like "12 3 45" to be taken as "12345"

Allow whitespaces in postal code input

---

app/feature/feature-claim-triaging/src/main/kotlin/com/hedvig/android/feature/claimtriaging/OptionChipsFlowRow.kt
app/ui/ui-claim-flow/src/main/kotlin/com/hedvig/android/ui/claimflow/HedvigChip.kt

Also merge the item semantics themselves so that it functions as one selectable item
Now announces for example when focusing on the first out of 6 chips with the text label "My home":
"(Not) Selected. My home. 1 out of 6. In list. 6 items. Double tap to toggle"

GEN-3819: Make chip flow row items part of a selectable group

---

app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/CoInsured.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/data/GetCoInsuredUseCase.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/AddCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/CoInsuredList.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddMissingInfoDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredAddOrRemoveDestination.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/EditCoInsuredPresenter.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/InsuredRow.kt
app/feature/feature-edit-coinsured/src/main/kotlin/com/hedvig/android/feature/editcoinsured/ui/RemoveCoInsuredBottomSheetContent.kt
app/feature/feature-edit-coinsured/src/test/kotlin/com/hedvig/android/feature/editcoinsured/ui/data/TestData.kt

[figma](https://www.figma.com/design/zItETkT4mu5ANVDYED5gEm/UX-Improvements--Small-Projects-?node-id=1638-1469&m=dev)
Added missing "activatesOn", "terminatesOn" labels that are there in design and ios.

GEN-4132 Add labels in edit-coinsured

---

app/apollo/apollo-octopus-public/src/commonMain/graphql/com/hedvig/android/apollo/octopus/schema.graphqls
app/app/build.gradle.kts
app/app/src/main/kotlin/com/hedvig/android/app/di/ApplicationModule.kt
app/logging/logging-device-model/build.gradle.kts
app/logging/logging-device-model/src/main/AndroidManifest.xml
app/logging/logging-device-model/src/main/graphql/MutationMemberLogDevice.graphql
app/logging/logging-device-model/src/main/kotlin/com/hedvig/android/logging/device/model/DefaultAndroidInfoProvider.kt
app/logging/logging-device-model/src/main/kotlin/com/hedvig/android/logging/device/model/DeviceNameLoggingAuthListener.kt
app/logging/logging-device-model/src/main/kotlin/com/hedvig/android/logging/device/model/di/LoggingDeviceModelModule.kt

Introduce a new module `logging-device-model` that logs device information (OS version, brand, model) upon user login.
- Add `DeviceNameLoggingAuthListener` to trigger device logging on login.
- Create `AndroidInfoProvider` to fetch device details.
- Define `MemberLogDeviceMutation` GraphQL mutation to send device info to the backend.
- Integrate the new module into the main application.
- Update GraphQL schema with `MemberLogDeviceInput` and `memberLogDevice` mutation.

Add device name logging
